force-app/main/default/objects/Pickup_Delivery_Route__c/Pickup_Delivery_Route__c.object-meta.xml
<CustomObject>
    <label>Pickup &amp; Delivery Route</label>
    <nameField>
        <label>Route Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pickup &amp; Delivery Routes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Pickup_Delivery_Route__c/fields/Delivery_Route_Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Route_Assigned_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Delivery Route Assigned To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Pickup_Delivery_Routes2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pickup_Delivery_Route__c/fields/Delivery_Route_Number__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Route_Number__c</fullName>
    <label>Delivery Route Number</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shipment__c/Shipment__c.object-meta.xml
<CustomObject>
    <description>Shipment object stores shipments requested against a pickup.</description>
    <label>Shipment</label>
    <nameField>
        <displayFormat>ST-{0000000}</displayFormat>
        <label>Shipment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipment__c/fields/Consignee_Name_TMS__c.field-meta.xml
<CustomField>
    <fullName>Consignee_Name_TMS__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Consignee Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Shipping</value>
        </filterItems>
        <filterItems>
            <field>Account.Customer_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Shipments (Consignee Name)</relationshipLabel>
    <relationshipName>Shipments4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Delivery_Route_Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Route_Assigned_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Delivery Route Assigned To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Delivery_Route_Assigned_To</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Delivery_Route_Number__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Route_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Delivery Route Number</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Pickup_Delivery_Route__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Delivery</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Pickup_Delivery_Route__c</referenceTo>
    <relationshipLabel>Shipments</relationshipLabel>
    <relationshipName>Shipments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Destination_Address_City__c.field-meta.xml
<CustomField>
    <fullName>Destination_Address_City__c</fullName>
    <formula>TEXT(Destination_Address_Name__r.Active_Pincode__r.City__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Destination Address City</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Destination_Address_Line1__c.field-meta.xml
<CustomField>
    <fullName>Destination_Address_Line1__c</fullName>
    <formula>Destination_Address_Name__r.ADDRESS1__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Destination Address Line 1</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Number_of_Packages__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Packages__c</fullName>
    <label>Number of Packages</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Shipment_Date__c.field-meta.xml
<CustomField>
    <fullName>Shipment_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <description>This is the Shipment date for Domestic</description>
    <label>Shipment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Shipping_Note_Number__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Note_Number__c</fullName>
    <description>This is the Domestic Shipping Note number</description>
    <label>Shipping Note Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Tracking_Status__c.field-meta.xml
<CustomField>
    <fullName>Tracking_Status__c</fullName>
    <label>Tracking Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
                <default>true</default>
                <label>Created</label>
            </value>
            <value>
                <fullName>Out for Pickup</fullName>
            </value>
            <value>
                <fullName>Picked Up</fullName>
            </value>
            <value>
                <fullName>Origin Hub</fullName>
            </value>
            <value>
                <fullName>Origin Port</fullName>
            </value>
            <value>
                <fullName>Transit Hub</fullName>
            </value>
            <value>
                <fullName>Transit Port</fullName>
            </value>
            <value>
                <fullName>Destination Port</fullName>
            </value>
            <value>
                <fullName>Destination Hub</fullName>
            </value>
            <value>
                <fullName>Out for Delivery</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Out of Linehaul</fullName>
            </value>
            <value>
                <fullName>Linehaul Deposit</fullName>
            </value>
            <value>
                <fullName>Linehaul In-Transit</fullName>
            </value>
            <value>
                <fullName>Linehaul Retrieved</fullName>
            </value>
            <value>
                <fullName>At Destination Airport</fullName>
                <isActive>false</isActive>
                <label>At Destination Airport</label>
            </value>
            <value>
                <fullName>At Origin Airport</fullName>
                <isActive>false</isActive>
                <label>At Origin Airport</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <isActive>false</isActive>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>In Transit</fullName>
                <isActive>false</isActive>
                <label>In Transit</label>
            </value>
            <value>
                <fullName>Source Hub</fullName>
                <isActive>false</isActive>
                <label>Source Hub</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AccountDataController.cls
public with sharing class AccountDataController {
    public AccountDataController() {
        
    }
    @AuraEnabled (cacheable=true)
        public static List<Shipment__c> fetchShipments(){
            return [ SELECT Id, Name, Shipping_Note_Number__c, Shipment_Date__c, Destination_Address_Line1__c,Delivery_Route_Number__c,Delivery_Route_Number__r.Name, Delivery_Route_Assigned_To__c,
            Consignee_Name_TMS__c,Consignee_Name_TMS__r.Name,Number_of_Packages__c,Delivery_Route_Assigned_To__r.Name, Destination_Address_City__c FROM Shipment__c WHERE 
            Shipping_Note_Number__c != null AND Tracking_Status__c='Destination Hub' LIMIT 10000];       
    }
    @AuraEnabled (cacheable=true)
        public static List<Shipment__c> searchShipments(String searcchKey){
            return [SELECT Id, Name, Shipping_Note_Number__c, Shipment_Date__c, Destination_Address_Line1__c,Delivery_Route_Number__c,Delivery_Route_Number__r.Name, Delivery_Route_Assigned_To__c,
            Consignee_Name_TMS__c,Consignee_Name_TMS__r.Name,Number_of_Packages__c,Delivery_Route_Assigned_To__r.Name, Destination_Address_City__c FROM Shipment__c WHERE Shipping_Note_Number__c != null AND Shipping_Note_Number__c =: searcchKey AND Tracking_Status__c='Destination Hub'];
        }
        @AuraEnabled
        public static List<Shipment__c> updateShipments(List<Shipment__c> shipdata, String searcchKey){
            System.debug('shipdata--'+shipdata);
            System.debug('searcchKey---'+searcchKey);
            List<Shipment__c> shipdatalist = new List<Shipment__c>();
            if(searcchKey != null){
                for(Shipment__c s:shipdata){
                    s.Delivery_Route_Assigned_To__c = searcchKey;
                    shipdatalist.add(s);
                }                
            }
            update shipdatalist;
            return shipdatalist; 

        }    
}