force-app/main/default/objects/ContentVersion/recordTypes/Upload.recordType-meta.xml
<RecordType>
    <fullName>Upload</fullName>
    <active>true</active>
    <label>Upload</label>
</RecordType>

force-app/main/default/objects/Delivery__c/Delivery__c.object-meta.xml
<CustomObject>
    <label>Delivery</label>
    <nameField>
        <displayFormat>D-{0000000}</displayFormat>
        <label>Delivery Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deliveries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery__c/fields/Shipment__c.field-meta.xml
<CustomField>
    <fullName>Shipment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shipment</label>
    <referenceTo>Shipment__c</referenceTo>
    <relationshipLabel>Deliveries</relationshipLabel>
    <relationshipName>Deliveries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Secure_Bag__c/Secure_Bag__c.object-meta.xml
<CustomObject>
    <label>Secure Bag</label>
    <nameField>
        <displayFormat>SB-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Secure Bags</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Secure_Bag__c/fields/POD__c.field-meta.xml
<CustomField>
    <fullName>POD__c</fullName>
    <defaultValue>false</defaultValue>
    <label>SecureBag Photo Id</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Secure_Bag__c/fields/Secure_Bag__c.field-meta.xml
<CustomField>
    <fullName>Secure_Bag__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Secure Bag</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Secure_Packaging__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Secure Bag</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Secure_Packaging__c</referenceTo>
    <relationshipLabel>Secure Bags</relationshipLabel>
    <relationshipName>Secure_Bags</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Secure_Bag__c/fields/Shipment__c.field-meta.xml
<CustomField>
    <fullName>Shipment__c</fullName>
    <label>Shipment</label>
    <referenceTo>Shipment__c</referenceTo>
    <relationshipLabel>Secure Bags</relationshipLabel>
    <relationshipName>SecureBags</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Shipment__c/Shipment__c.object-meta.xml
<CustomObject>
    <description>Shipment object stores shipments requested against a pickup.</description>
    <label>Shipment</label>
    <nameField>
        <displayFormat>ST-{0000000}</displayFormat>
        <label>Shipment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipment__c/fields/POD__c.field-meta.xml
<CustomField>
    <fullName>POD__c</fullName>
    <defaultValue>false</defaultValue>
    <label>POD</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/POD_Link_Url__c.field-meta.xml
<CustomField>
    <fullName>POD_Link_Url__c</fullName>
    <label>POD Link Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/SecurebagPhoto__c.field-meta.xml
<CustomField>
    <fullName>SecurebagPhoto__c</fullName>
    <defaultValue>false</defaultValue>
    <label>SecurebagPhoto</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/SignaturePhoto__c.field-meta.xml
<CustomField>
    <fullName>SignaturePhoto__c</fullName>
    <defaultValue>false</defaultValue>
    <label>SignaturePhoto</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ContentDocumentLinkTriggerHelper.cls
public class ContentDocumentLinkTriggerHelper 
{
    public static void Perform(List<ContentDocumentLink> cdlList)
    {
        System.debug('<====== Inside ContentDocumentLinkTriggerHelper ======>');
        List<Delivery__c> DList = new List<Delivery__c>();
        List<Shipment__c> ShipList = new List<Shipment__c>();
        for(ContentDocumentLink cdl :cdlList)
        {             
            System.debug('cdl.ContentDocumentId :'+cdl.ContentDocumentId);        
            Delivery__c d = [select Id,POD__c,POD_Link_Url__c,Shipment__c from Delivery__c where Id=:cdl.LinkedEntityId limit 1];
            //Shipment__c ship = [select Id,POD__c from Shipment__c where Id=:d.Shipment__c limit 1];
            //ContentVersion cv = [select ContentDocumentId,Versiondataurl from ContentVersion where ContentDocumentId =: cdl.ContentDocumentId limit 1]  ;
			//System.debug('CV :'+cv.Versiondataurl); 
            //ContentDistribution cd = [select ContentDownloadUrl, DistributionPublicUrl from ContentDistribution where ContentDocumentId=:cv.ContentDocumentId limit 1];                       
           // System.debug('ContentDownloadUrl  :'+cd.ContentDownloadUrl);            
           // System.debug('DistributionPublicUrl :'+cd.DistributionPublicUrl);            
            System.debug('ContentDocumentLinkTriggerHelper D :'+d);            
           // d.POD_Link_Url__c = cd.ContentDownloadurl;
          // d.POD_Link_Url__c = cv.Versiondataurl;
            d.POD__c = true; 
           // ship.POD__c = true;
            DList.add(d);
            //ShipList.add(ship);
        }
        if(DList.size()>0)
        {
            System.debug('Update Ddelivery ob 11');
            update DList;
            System.debug('Update Ddelivery ob 11');
        }
        if(ShipList.size()>0)
        {
           // update ShipList;
        }
    }
    public static void updateSBPod(List<ContentDocumentLink> cdlList)
    {
        System.debug('<====== Inside ContentDocumentLinkTriggerHelper ======>');
        List<Secure_Bag__c> SBList = new List<Secure_Bag__c>();
        List<Shipment__c> ShipList1 = new List<Shipment__c>();
        for(ContentDocumentLink cdl :cdlList)
        {            
            //ContentDistribution cd = [select ContentDownloadurl from ContentDistribution where ContentDocumentId=: cdl.ContentDocumentId limit 1];
            //System.debug('ContentDocumentLinkTriggerHelper CD :'+cd);    
            System.debug('cdl.ContentDocumentId :'+cdl.ContentDocumentId);        
            Secure_Bag__c sb = [select Id,POD__c,Shipment__c from Secure_Bag__c where Id=:cdl.LinkedEntityId limit 1];
            Shipment__c ship = [select Id,SecurebagPhoto__c from Shipment__c where Id=:sb.Shipment__c limit 1];
            System.debug('ContentDocumentLinkTriggerHelper D :'+sb); 
            System.debug('ContentDocumentLinkTriggerHelper ship :'+ship); 
            // d.POD_Link_Url__c = cd.ContentDownloadurl;
            sb.POD__c = true; 
            SBList.add(sb);
            ship.SecurebagPhoto__c = true;
            ShipList1.add(ship);
            
        }
        if(SBList.size()>0)
        {
            update SBList;
            if(ShipList1.size()>0)
            {
                System.debug('SHIPMENT UPLOAD');
                //update ShipList1;
            } 
        }
        
    }  
    
    public static void updateShip(List<ContentDocumentLink> cdlList)
    {
        System.debug('<====== Inside updateShip ======>');
         System.debug('<====== Inside updateShip ======> cdlList :'+cdlList);
        List<Shipment__c> ShipList1 = new List<Shipment__c>();
        for(ContentDocumentLink cdl :cdlList)
        {   
            System.debug('cdl.ContentDocumentId :'+cdl.ContentDocumentId);             
            ContentDocument cdoc = [select Title from ContentDocument where Id=:cdl.ContentDocumentId limit 1];
            System.debug('cdl.cdoc :'+cdoc);
            if(cdoc.title.contains('Signature'))
            {
                System.debug('Signature Matches Here');                
                Shipment__c ship = [select Id,SignaturePhoto__c from Shipment__c where Id=:cdl.LinkedEntityId limit 1];
                System.debug('ContentDocumentLinkTriggerHelper ship :'+ship); 
                ship.SignaturePhoto__c = true;
                ShipList1.add(ship);                
            }
        }
        if(ShipList1.size()>0)
        {
            System.debug('SHIPMENT UPLOAD');
            update ShipList1;
        }        
    }      
}