force-app/main/default/objects/Case/fields/Shipment__c.field-meta.xml
<CustomField>
    <fullName>Shipment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shipment</label>
    <referenceTo>Shipment__c</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipment__c/Shipment__c.object-meta.xml
<CustomObject>
    <description>Shipment object stores shipments requested against a pickup.</description>
    <label>Shipment</label>
    <nameField>
        <displayFormat>ST-{0000000}</displayFormat>
        <label>Shipment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipment__c/fields/Customer_Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Customer_Product_Category__c</fullName>
    <label>BVC Service</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ValSHIP</fullName>
            </value>
            <value>
                <fullName>GoldSHIP</fullName>
            </value>
            <value>
                <fullName>SilverSHIP</fullName>
            </value>
            <value>
                <fullName>LuxeSHIP</fullName>
            </value>
            <value>
                <fullName>GenSHIP</fullName>
            </value>
            <value>
                <fullName>BATH</fullName>
            </value>
            <value>
                <fullName>eSHIP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Insurance_By__c.field-meta.xml
<CustomField>
    <fullName>Insurance_By__c</fullName>
    <label>Insurance By</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BVC</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Consignee</fullName>
                <isActive>false</isActive>
                <label>Consignee</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Net_Weight__c.field-meta.xml
<CustomField>
    <fullName>Net_Weight__c</fullName>
    <description>All</description>
    <label>Net Weight</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Product_Description__c.field-meta.xml
<CustomField>
    <fullName>Product_Description__c</fullName>
    <label>Product Description</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Customer_Product_Category__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Machinery</fullName>
            </value>
            <value>
                <fullName>Packing Material</fullName>
            </value>
            <value>
                <fullName>Coloured &amp; Gem Stones</fullName>
            </value>
            <value>
                <fullName>Cut &amp; Polished Diamonds</fullName>
            </value>
            <value>
                <fullName>Diamond Jewellery</fullName>
                <label>DIAMOND JEWELLERY</label>
            </value>
            <value>
                <fullName>Dore Bar</fullName>
            </value>
            <value>
                <fullName>Gold Bar</fullName>
                <label>GOLD BAR</label>
            </value>
            <value>
                <fullName>Gold Coin</fullName>
            </value>
            <value>
                <fullName>Gold Jewellery</fullName>
                <label>GOLD JEWELLERY</label>
            </value>
            <value>
                <fullName>Platinum Jewellery</fullName>
            </value>
            <value>
                <fullName>Diamond Powder</fullName>
            </value>
            <value>
                <fullName>Imitation Jewellery</fullName>
            </value>
            <value>
                <fullName>Silver Bar</fullName>
            </value>
            <value>
                <fullName>Silver Coin</fullName>
            </value>
            <value>
                <fullName>Silver Jewellery</fullName>
                <label>SILVER JEWELLERY</label>
            </value>
            <value>
                <fullName>Rough Diamond</fullName>
                <label>ROUGH DIAMOND</label>
            </value>
            <value>
                <fullName>Silver Article</fullName>
                <label>SILVER ARTICLE</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Shipment_Value__c.field-meta.xml
<CustomField>
    <fullName>Shipment_Value__c</fullName>
    <label>Shipment Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/SendShipementPDFViaEmaiTest.cls
@isTest
public class SendShipementPDFViaEmaiTest {
    
    // Create test records in setup method
    // We only have one test method in this case so it's not necessary to create test data here.
    // We could create test records in the test method itself but this could be useful if you want to have
    // additional test methods to test other things
    
    @TestSetup static void testSetup(){
        Shipment__c testShipment = new Shipment__c();
        testShipment.Customer_Product_Category__c = 'GoldSHIP';
        testShipment.Shipper_Email__c = 'test@gmail.com';
        testShipment.Product_Description__c = 'GOLD BAR';
        testShipment.Insurance_By__c = 'BVC';
        testShipment.Net_Weight__c = 12;
        testShipment.Shipment_Value__c = 12;
        
        insert testShipment;
       system.debug('testShipment:::'+testShipment);       
    }
	
    // Test email is sent
    @isTest static void testEmailIsSent(){
        // Retrieve shipment record
        // I usually  retrieve records in a list since it protects against a QueryException (Probably not needed in this case
        // since you know that the shipment record was created and inserted by the setup method.) Just check the list for data before using it
        
        List<Shipment__c> testShipmentList = [Select Id,shipper_email__c FROM shipment__c WHERE Shipper_Email__c = 'test@gmail.com'];
        
        // Check that the test account was actually inserted by the setup method. Again, probably not necessary...
        System.assertEquals(false, testShipmentList.isEmpty(), 'Test Account record does not exist.');
        
        // Create and populate args List of Lists
        List<List<String>> args = new List<List<String>>();
        
        // Email value is expected first
        // shipment record Id value is expected second
        args.add(new List<String>{'test@test.com', testShipmentList[0].Id});
        
        // This creates new set of gov limits and executes all async processes upon the stopTest function call.
        Test.startTest();
        
        // Add shipmentID param for SendShipementPDFViaEmail class
        ApexPages.currentPage().getParameters().put('Id', testShipmentList[0].Id);
                  
        // Call generatePDF method
        SendShipementPDFViaEmail.sendPDF(args);
        
        Integer emailInvocations = Limits.getEmailInvocations();
        Test.stopTest();
        
        // Check that an email was sent
        System.assertEquals(1, emailInvocations, 'Email was not sent.');

    }
}