force-app/main/default/objects/BVC_CB_PreTaxBill__c/BVC_CB_PreTaxBill__c.object-meta.xml
<CustomObject>
    <label>PreTaxBill</label>
    <nameField>
        <label>PreTaxBill Table</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PreTaxBills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BVC_CB_PreTaxBill__c/fields/BVC_CB_Invoice_Generated_in_Salesforce__c.field-meta.xml
<CustomField>
    <fullName>BVC_CB_Invoice_Generated_in_Salesforce__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Invoice Generated in Salesforce</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BVC_CB_PreTaxBill__c/fields/BVC_CB_Is_Order_Created__c.field-meta.xml
<CustomField>
    <fullName>BVC_CB_Is_Order_Created__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Order Created</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/Billing_Address__c.field-meta.xml
<CustomField>
    <fullName>Billing_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing Address</label>
    <referenceTo>AddressBook__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/BVC_CB_PreTaxBill__c.field-meta.xml
<CustomField>
    <fullName>BVC_CB_PreTaxBill__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PreTaxBill</label>
    <referenceTo>BVC_CB_PreTaxBill__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CBOrderActivationBatch.cls
public class CBOrderActivationBatch implements Database.Batchable<sObject>{
	public final String Query;
    public CBOrderActivationBatch(){
          Query='SELECT id,Status FROM Order where Status = \'Draft\' and BVC_CB_PreTaxBill__c != null and Billing_Address__c != null and BVC_CB_PreTaxBill__r.BVC_CB_Invoice_Generated_in_Salesforce__c = false and BVC_CB_PreTaxBill__r.BVC_CB_Is_Order_Created__c = true ';  
       }
    public Database.QueryLocator start(Database.BatchableContext BC){
      return Database.getQueryLocator(query);
   	}
    public void execute(Database.BatchableContext BC, List<Order> scope){
        for(Order s:scope){
       		s.Status = 'Activated';
       }
        Update scope;   
    }
    public void finish(Database.BatchableContext BC){
       
   }
 public static void Method2(){
        integer i = 0;
          
            i++;
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;
        i++;
      i++;
      i++;
        i++;
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;
        i++;
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;
       i++;
      
        i++;
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;
       i++;
      
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;
     i++;} 
}