force-app/main/default/objects/Active_Pincode__c/Active_Pincode__c.object-meta.xml
<CustomObject>
    <label>Active Pincode</label>
    <nameField>
        <label>Pincode</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Active Pincodes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Active_Pincode__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Cities</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/AddressBook__c/AddressBook__c.object-meta.xml
<CustomObject>
    <description>Primarily stores multiple shipping and billing addresses.</description>
    <label>Address Book</label>
    <nameField>
        <label>Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AddressBook__c/fields/CITY__c.field-meta.xml
<CustomField>
    <fullName>CITY__c</fullName>
    <label>City</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AddressBook__c/fields/PINCODE__c.field-meta.xml
<CustomField>
    <fullName>PINCODE__c</fullName>
    <label>Pincode</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AddressBook__c/fields/STATE__c.field-meta.xml
<CustomField>
    <fullName>STATE__c</fullName>
    <label>State</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Bill_To_GSTIN__c.field-meta.xml
<CustomField>
    <fullName>Bill_To_GSTIN__c</fullName>
    <label>Bill To GSTIN</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Number_of_Packages__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Packages__c</fullName>
    <label>Number of Packages</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/fields/Shipment__c.field-meta.xml
<CustomField>
    <fullName>Shipment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shipment</label>
    <referenceTo>Shipment__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Shipment_Date__c.field-meta.xml
<CustomField>
    <fullName>Shipment_Date__c</fullName>
    <label>Shipment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/Shipment_Type__c.field-meta.xml
<CustomField>
    <fullName>Shipment_Type__c</fullName>
    <label>Shipment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Collect</fullName>
            </value>
            <value>
                <fullName>Prepaid</fullName>
            </value>
            <value>
                <fullName>All</fullName>
            </value>
            <value>
                <fullName>Intercity</fullName>
            </value>
            <value>
                <fullName>Forward</fullName>
            </value>
            <value>
                <fullName>RTO</fullName>
            </value>
            <value>
                <fullName>Reverse</fullName>
            </value>
            <value>
                <fullName>Intracity</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Shipment_Value__c.field-meta.xml
<CustomField>
    <fullName>Shipment_Value__c</fullName>
    <label>Shipment Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Secure_Packaging__c/Secure_Packaging__c.object-meta.xml
<CustomObject>
    <label>Secure Packaging</label>
    <nameField>
        <label>Shipping Note Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Secure Packagings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Secure_Packaging__c/fields/Shipment__c.field-meta.xml
<CustomField>
    <fullName>Shipment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shipment</label>
    <referenceTo>Shipment__c</referenceTo>
    <relationshipLabel>Secure Packagings</relationshipLabel>
    <relationshipName>Secure_Packagings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipment__c/Shipment__c.object-meta.xml
<CustomObject>
    <description>Shipment object stores shipments requested against a pickup.</description>
    <label>Shipment</label>
    <nameField>
        <displayFormat>ST-{0000000}</displayFormat>
        <label>Shipment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipment__c/fields/Bill_To_GSTIN__c.field-meta.xml
<CustomField>
    <fullName>Bill_To_GSTIN__c</fullName>
    <label>Bill To GSTIN</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Bill_To_Party__c.field-meta.xml
<CustomField>
    <fullName>Bill_To_Party__c</fullName>
    <label>Bill To Party</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Bill_To_Party_PAN__c.field-meta.xml
<CustomField>
    <fullName>Bill_To_Party_PAN__c</fullName>
    <label>Bill To Party PAN</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Consignee_Name_TMS__c.field-meta.xml
<CustomField>
    <fullName>Consignee_Name_TMS__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Consignee Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Shipping</value>
        </filterItems>
        <filterItems>
            <field>Account.Customer_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Shipments (Consignee Name)</relationshipLabel>
    <relationshipName>Shipments4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Consignee_PAN_TMS__c.field-meta.xml
<CustomField>
    <fullName>Consignee_PAN_TMS__c</fullName>
    <formula>Consignee_Name_TMS__r.PAN_Number_of_Entity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Consignee PAN</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Destination_Address_City__c.field-meta.xml
<CustomField>
    <fullName>Destination_Address_City__c</fullName>
    <formula>TEXT(Destination_Address_Name__r.Active_Pincode__r.City__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Destination Address City</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Destination_Address_Line1__c.field-meta.xml
<CustomField>
    <fullName>Destination_Address_Line1__c</fullName>
    <formula>Destination_Address_Name__r.ADDRESS1__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Destination Address Line 1</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Destination_Address_Line_2__c.field-meta.xml
<CustomField>
    <fullName>Destination_Address_Line_2__c</fullName>
    <formula>Destination_Address_Name__r.ADDRESS2__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Destination Address Line 2</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Destination_Address_Pincode__c.field-meta.xml
<CustomField>
    <fullName>Destination_Address_Pincode__c</fullName>
    <formula>/*Destination_Address_Name__r.PINCODE__c*/
IF( Destination_Address_Name__c != null,Destination_Address_Name__r.PINCODE__c,  Destination_Pincode__c  )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Destination Address Pincode</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Destination_Address_State__c.field-meta.xml
<CustomField>
    <fullName>Destination_Address_State__c</fullName>
    <formula>Destination_Address_Name__r.STATE__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Destination Address State</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Net_weight_in_Gram__c.field-meta.xml
<CustomField>
    <fullName>Net_weight_in_Gram__c</fullName>
    <formula>CASE( TEXT(Net_Weight_UOM_TMS__c), &apos;KG&apos;, Net_Weight__c * 1000,
				&apos;Carat&apos;, Net_Weight__c * 0.20, Net_Weight__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Net weight in Gram</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Number_of_Packages__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Packages__c</fullName>
    <label>Number of Packages</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Origin_Address_City__c.field-meta.xml
<CustomField>
    <fullName>Origin_Address_City__c</fullName>
    <formula>TEXT(Origin_Address_Name__r.Active_Pincode__r.City__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Origin Address City</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Origin_Address_Line_1__c.field-meta.xml
<CustomField>
    <fullName>Origin_Address_Line_1__c</fullName>
    <formula>Origin_Address_Name__r.ADDRESS1__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Origin Address Line_1</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Origin_Address_Line_2__c.field-meta.xml
<CustomField>
    <fullName>Origin_Address_Line_2__c</fullName>
    <formula>Origin_Address_Name__r.ADDRESS2__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Origin Address Line 2</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Origin_Address_Phone__c.field-meta.xml
<CustomField>
    <fullName>Origin_Address_Phone__c</fullName>
    <formula>Origin_Address_Name__r.MOBILE1__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Origin Address Phone</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Origin_Address_Pincode__c.field-meta.xml
<CustomField>
    <fullName>Origin_Address_Pincode__c</fullName>
    <formula>Origin_Address_Name__r.PINCODE__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Origin Address Pincode</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Origin_Address_State__c.field-meta.xml
<CustomField>
    <fullName>Origin_Address_State__c</fullName>
    <formula>Origin_Address_Name__r.STATE__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Origin Address State</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Pincode__c.field-meta.xml
<CustomField>
    <fullName>Pincode__c</fullName>
    <label>Pincode</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Shipment_Date__c.field-meta.xml
<CustomField>
    <fullName>Shipment_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <description>This is the Shipment date for Domestic</description>
    <label>Shipment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Shipment_Value__c.field-meta.xml
<CustomField>
    <fullName>Shipment_Value__c</fullName>
    <label>Shipment Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Shipper_Name_TMS__c.field-meta.xml
<CustomField>
    <fullName>Shipper_Name_TMS__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shipper Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Shipping, Shipping</value>
        </filterItems>
        <filterItems>
            <field>Account.Customer_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Shipments (Shipper Name)</relationshipLabel>
    <relationshipName>Shipments3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Shipper_PAN_TMS__c.field-meta.xml
<CustomField>
    <fullName>Shipper_PAN_TMS__c</fullName>
    <formula>Shipper_Name_TMS__r.PAN_Number_of_Entity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Shipper PAN</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Shipping_Note_Number__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Note_Number__c</fullName>
    <description>This is the Domestic Shipping Note number</description>
    <label>Shipping Note Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/SNN_Bar_Code__c.field-meta.xml
<CustomField>
    <fullName>SNN_Bar_Code__c</fullName>
    <formula>/*&quot;https://barcode.tec-it.com/barcode.ashx?data=&quot;+Shipping_Note_Number__c+&quot;&amp;code=Code128&amp;dpi=96&amp;dataseparator=&quot;*/
&quot;https://barcode.tec-it.com/barcode.ashx?data=&quot;+Shipping_Note_Number__c+&quot;&amp;code=Code128&amp;translate-esc=on&quot;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SNN Bar Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TMS_ShipmentPdfController.cls
/**
* @description       : 
* @author            : ChangeMeIn@UserSettingsUnder.SFDoc
* @group             : 
* @last modified on  : 03-16-2022
* @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public class TMS_ShipmentPdfController {
    public List<Secure_Packaging__c> SelectedLabelList {get;set;}
    public static  List<Shipment__c> shipmentList{get;set;}
    public TMS_ShipmentPdfController(){
        String ShipId = ApexPages.currentPage().getParameters().get('id');
        system.debug('@@@@@@@ ::'+ShipId);
        shipmentList = new List<Shipment__c>();
        if(string.isNotBlank(ShipId)){
            Shipment__c ship = new Shipment__c();
            ship = [Select Id, name, Shipment_Date__c,Origin_Address_City__c, Origin_Address_Line_1__c,Origin_Address_Line_2__c,
                    Origin_Address_State__c,Shipper_PAN_TMS__c,Origin_Address_Pincode__c,Origin_Address_Phone__c,
                    Number_of_Packages__c, Shipment_Value__c, CreatedDate,Shipper_Name_TMS__c,Shipper_Name_TMS__r.name,
                    Shipping_Note_Number__c, Consignee_Name_TMS__r.name, Destination_Address_Line1__c,
                    Destination_Address_Line_2__c,Destination_Address_City__c, Destination_Address_State__c,Destination_Address_Phone__c,
                    Destination_Address_Pincode__c,Bill_To_GSTIN__c,Bill_To_Party__c,Bill_To_Party_PAN__c, Consignee_PAN_TMS__c,Net_weight_in_Gram__c,
                    SNN_Bar_Code__c,Shipment_Type__c,Gross_Weight__c,Product_Description__c, Billing_Account__r.name,
                    Billing_Address__r.ADDRESS1__c,Billing_Address__r.ADDRESS2__c,Billing_Address__r.CITY__c,Billing_Address__r.STATE__c,Billing_Address__r.MOBILE1__c,
                    Billing_Address__r.PINCODE__c,Billing_Address__r.Active_Pincode__c,Insurance_By_BVC__c,Customer_Product_Category__c,Invoice_Number__c,Insurance_By__c
                    FROM Shipment__c WHERE Id =:ShipId limit 1];
            system.debug('@@@@@@@ ::'+ShipId);
            if(ship.Invoice_Number__c!=null&&ship.Invoice_Number__c.length()>40){
                Integer ir=0;
                ir=ship.Invoice_Number__c.length()/35;
                for(Integer i=1;i<=ir;i++){
                    ship.Invoice_Number__c=ship.Invoice_Number__c.substring(0, i*35) + ' ' + ship.Invoice_Number__c.substring(i*35);  
                }
            }
            shipmentList.add(ship);
            shipmentList.add(ship);
            
        }else{
            string pageType = ApexPages.currentPage().getParameters().get('type');
            if(pageType=='pre'){
                String[] ids = ApexPages.currentPage().getParameters().get('list').split(',');
                SelectedLabelList = [select id, name,Status__c FROM Secure_Packaging__c WHERE id=:ids];
            }
            else if(pageType=='post'){
                String[] ids = ApexPages.currentPage().getParameters().get('list').split(',');
                List<Shipment__c> ShipList = new List<Shipment__c>();
                ShipList = [Select Id, name,Shipment_Date__c, Origin_Address_City__c, Origin_Address_Line_1__c,Origin_Address_Line_2__c,
                            Origin_Address_State__c,Shipper_PAN_TMS__c,Origin_Address_Pincode__c,Origin_Address_Phone__c,
                            Number_of_Packages__c, Shipment_Value__c, CreatedDate,Shipper_Name_TMS__c,Shipper_Name_TMS__r.name,
                            Shipping_Note_Number__c, Consignee_Name_TMS__r.name, Destination_Address_Line1__c,
                            Destination_Address_Line_2__c,Destination_Address_City__c, Destination_Address_State__c,Destination_Address_Phone__c,
                            Destination_Address_Pincode__c,Bill_To_GSTIN__c,Bill_To_Party__c,Bill_To_Party_PAN__c, Consignee_PAN_TMS__c,Net_weight_in_Gram__c,
                            SNN_Bar_Code__c,Shipment_Type__c,Gross_Weight__c,Product_Description__c,Billing_Account__r.name,
                            Billing_Address__r.ADDRESS1__c,Billing_Address__r.ADDRESS2__c,Billing_Address__r.CITY__c,Billing_Address__r.STATE__c,Billing_Address__r.MOBILE1__c,
                            Billing_Address__r.PINCODE__c,Billing_Address__r.Active_Pincode__c,Insurance_By_BVC__c,Customer_Product_Category__c,Invoice_Number__c,Insurance_By__c
                            FROM Shipment__c WHERE Id in:ids  order by createddate DESC limit 50000];
                for(Shipment__c sh:ShipList){
                    if(sh.Invoice_Number__c!=null&&sh.Invoice_Number__c.length()>40){
                        Integer ir=0;
                        ir=sh.Invoice_Number__c.length()/35;
                        for(Integer i=1;i<=ir;i++){
                            sh.Invoice_Number__c=sh.Invoice_Number__c.substring(0, i*35) + ' ' + sh.Invoice_Number__c.substring(i*35);  
                        }
                        
                    }
                    shipmentList.add(sh);
                    shipmentList.add(sh); 
                }
            }
        }
    }
}