force-app/main/default/objects/Active_Pincode__c/Active_Pincode__c.object-meta.xml
<CustomObject>
    <label>Active Pincode</label>
    <nameField>
        <label>Pincode</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Active Pincodes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Active_Pincode__c/fields/Hub__c.field-meta.xml
<CustomField>
    <fullName>Hub__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hub</label>
    <referenceTo>Hub__c</referenceTo>
    <relationshipLabel>Active Pincodes</relationshipLabel>
    <relationshipName>Active_Pincodes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AddressBook__c/AddressBook__c.object-meta.xml
<CustomObject>
    <description>Primarily stores multiple shipping and billing addresses.</description>
    <label>Address Book</label>
    <nameField>
        <label>Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AddressBook__c/fields/Active_Pincode__c.field-meta.xml
<CustomField>
    <fullName>Active_Pincode__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Active Pincode</label>
    <referenceTo>Active_Pincode__c</referenceTo>
    <relationshipLabel>Addresses (Active Pincode)</relationshipLabel>
    <relationshipName>Addresses1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AddressBook__c/recordTypes/Billing.recordType-meta.xml
<RecordType>
    <fullName>Billing</fullName>
    <active>true</active>
    <label>Billing</label>
</RecordType>

force-app/main/default/objects/AddressBook__c/recordTypes/Shipping.recordType-meta.xml
<RecordType>
    <fullName>Shipping</fullName>
    <active>true</active>
    <label>Shipping</label>
</RecordType>

force-app/main/default/objects/FSE_Sales__c/FSE_Sales__c.object-meta.xml
<CustomObject>
    <label>Hub Employee</label>
    <nameField>
        <displayFormat>FS-{000000}</displayFormat>
        <label>FSE &amp; Sales Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hub Employees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FSE_Sales__c/fields/Hub__c.field-meta.xml
<CustomField>
    <fullName>Hub__c</fullName>
    <label>Hub</label>
    <referenceTo>Hub__c</referenceTo>
    <relationshipLabel>FSE &amp; Sales</relationshipLabel>
    <relationshipName>FSE_Sales</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Secure_Bag__c/Secure_Bag__c.object-meta.xml
<CustomObject>
    <label>Secure Bag</label>
    <nameField>
        <displayFormat>SB-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Secure Bags</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Secure_Bag__c/fields/Current_Scan_Hub__c.field-meta.xml
<CustomField>
    <fullName>Current_Scan_Hub__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Current Scan Hub</label>
    <referenceTo>Hub__c</referenceTo>
    <relationshipLabel>Secure Bags</relationshipLabel>
    <relationshipName>Secure_Bags</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Secure_Bag__c/fields/Current_Scan_Loction__c.field-meta.xml
<CustomField>
    <fullName>Current_Scan_Loction__c</fullName>
    <label>Current Scan Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
            </value>
            <value>
                <fullName>Out for Pickup</fullName>
            </value>
            <value>
                <fullName>Picked Up</fullName>
            </value>
            <value>
                <fullName>Origin Hub</fullName>
            </value>
            <value>
                <fullName>Origin Port</fullName>
            </value>
            <value>
                <fullName>Transit Hub</fullName>
            </value>
            <value>
                <fullName>Transit Port</fullName>
            </value>
            <value>
                <fullName>Destination Port</fullName>
            </value>
            <value>
                <fullName>Destination Hub</fullName>
            </value>
            <value>
                <fullName>Out for Delivery</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Secure_Bag__c/fields/Finalised_Linehaul_Number__c.field-meta.xml
<CustomField>
    <fullName>Finalised_Linehaul_Number__c</fullName>
    <label>Finalised Linehaul Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Secure_Bag__c/fields/Flight_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Flight_Schedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Flight Schedule</label>
    <referenceTo>Flight_Schedule__c</referenceTo>
    <relationshipLabel>Secure Bags</relationshipLabel>
    <relationshipName>Secure_Bags</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Secure_Bag__c/fields/Linehaul_Type__c.field-meta.xml
<CustomField>
    <fullName>Linehaul_Type__c</fullName>
    <label>Linehaul Type</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Secure_Bag__c/fields/Next_Destination__c.field-meta.xml
<CustomField>
    <fullName>Next_Destination__c</fullName>
    <label>Next Destination</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Branch</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Secure_Bag__c/fields/Seal_Id__c.field-meta.xml
<CustomField>
    <fullName>Seal_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Seal Id</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Secure_Packaging__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Secure Seal</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Secure_Packaging__c</referenceTo>
    <relationshipLabel>Secure Bags (Seal Id)</relationshipLabel>
    <relationshipName>Secure_Bags2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Secure_Bag__c/fields/Secure_Bag__c.field-meta.xml
<CustomField>
    <fullName>Secure_Bag__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Secure Bag</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Secure_Packaging__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Secure Bag</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Secure_Packaging__c</referenceTo>
    <relationshipLabel>Secure Bags</relationshipLabel>
    <relationshipName>Secure_Bags</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Secure_Bag__c/fields/Shipment__c.field-meta.xml
<CustomField>
    <fullName>Shipment__c</fullName>
    <label>Shipment</label>
    <referenceTo>Shipment__c</referenceTo>
    <relationshipLabel>Secure Bags</relationshipLabel>
    <relationshipName>SecureBags</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Secure_Bag__c/fields/Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Transport__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>BVC Vehicle</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Transport__c</referenceTo>
    <relationshipLabel>Secure Bags</relationshipLabel>
    <relationshipName>Secure_Bags</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Secure_Packaging__c/Secure_Packaging__c.object-meta.xml
<CustomObject>
    <label>Secure Packaging</label>
    <nameField>
        <label>Shipping Note Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Secure Packagings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Secure_Packaging__c/fields/Finalised_Linehaul_Number__c.field-meta.xml
<CustomField>
    <fullName>Finalised_Linehaul_Number__c</fullName>
    <label>Finalised Linehaul Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Secure_Packaging__c/fields/Linehaul_Type__c.field-meta.xml
<CustomField>
    <fullName>Linehaul_Type__c</fullName>
    <label>Linehaul Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Secure_Packaging__c/fields/Shipment__c.field-meta.xml
<CustomField>
    <fullName>Shipment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shipment</label>
    <referenceTo>Shipment__c</referenceTo>
    <relationshipLabel>Secure Packagings</relationshipLabel>
    <relationshipName>Secure_Packagings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipment__c/Shipment__c.object-meta.xml
<CustomObject>
    <description>Shipment object stores shipments requested against a pickup.</description>
    <label>Shipment</label>
    <nameField>
        <displayFormat>ST-{0000000}</displayFormat>
        <label>Shipment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipment__c/fields/AddressBook__c.field-meta.xml
<CustomField>
    <fullName>AddressBook__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Address</label>
    <referenceTo>AddressBook__c</referenceTo>
    <relationshipLabel>Shipments</relationshipLabel>
    <relationshipName>Shipments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Product_Description__c.field-meta.xml
<CustomField>
    <fullName>Product_Description__c</fullName>
    <label>Product Description</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Customer_Product_Category__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Machinery</fullName>
            </value>
            <value>
                <fullName>Packing Material</fullName>
            </value>
            <value>
                <fullName>Coloured &amp; Gem Stones</fullName>
            </value>
            <value>
                <fullName>Cut &amp; Polished Diamonds</fullName>
            </value>
            <value>
                <fullName>Diamond Jewellery</fullName>
                <label>DIAMOND JEWELLERY</label>
            </value>
            <value>
                <fullName>Dore Bar</fullName>
            </value>
            <value>
                <fullName>Gold Bar</fullName>
                <label>GOLD BAR</label>
            </value>
            <value>
                <fullName>Gold Coin</fullName>
            </value>
            <value>
                <fullName>Gold Jewellery</fullName>
                <label>GOLD JEWELLERY</label>
            </value>
            <value>
                <fullName>Platinum Jewellery</fullName>
            </value>
            <value>
                <fullName>Diamond Powder</fullName>
            </value>
            <value>
                <fullName>Imitation Jewellery</fullName>
            </value>
            <value>
                <fullName>Silver Bar</fullName>
            </value>
            <value>
                <fullName>Silver Coin</fullName>
            </value>
            <value>
                <fullName>Silver Jewellery</fullName>
                <label>SILVER JEWELLERY</label>
            </value>
            <value>
                <fullName>Rough Diamond</fullName>
                <label>ROUGH DIAMOND</label>
            </value>
            <value>
                <fullName>Silver Article</fullName>
                <label>SILVER ARTICLE</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TMS_DLHN__c/TMS_DLHN__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>TMS_DLHN</label>
</CustomObject>

force-app/main/default/objects/TMS_DLHN__c/fields/Finalized_Number__c.field-meta.xml
<CustomField>
    <fullName>Finalized_Number__c</fullName>
    <label>Finalized Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TMS_DLHN__c/fields/Last_Number__c.field-meta.xml
<CustomField>
    <fullName>Last_Number__c</fullName>
    <label>Last Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TMS_LinehaulClass_Test.cls
@isTest
public class TMS_LinehaulClass_Test {
    Public static testmethod void testShipments(){
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator'];
        User u = new User(Alias = 'standt', Email='standarduser@testorg.com',
                          EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
                          LocaleSidKey='en_US', ProfileId = p.Id,
                          TimeZoneSidKey='America/Los_Angeles',
                          UserName='testuser@bvcl.com');
        insert u;
        
        Account BillingAcc = BVCL_TestDataFactory.createCustomer('BVCLBill Customer','Billing',true);
        Account ShipperAcc = BVCL_TestDataFactory.createCustomer('BVCLShipp Customer','Shipping',true);
        Hub__c DelhiHub = BVCL_TestDataFactory.CreateHub('Delhi', true, 'DELHI');
        FSE_Sales__c fse = BVCL_TestDataFactory.createFSE(DelhiHub.id,u.id,'Manager',true,true);
        Active_Pincode__c DelhiPin = BVCL_TestDataFactory.CreatePincode('110025', DelhiHub.id, 'Delhi', 'South', true);
        AddressBook__c ShipperAddress = BVCL_TestDataFactory.CreateAddress('Shipping',ShipperAcc.id,'Line 1',DelhiPin.id,'Cityyy',true);
        
        Shipment__c Ship1 = BVCL_TestDataFactory.CreateShipment(BillingAcc.id, ShipperAcc.id, ShipperAddress.id, ShipperAcc.id, ShipperAddress.id, false);
        ship1.Product_Description__c = 'Gold Jewellery';
        insert Ship1;
        
        Secure_Packaging__c SP_Bag = BVCL_TestDataFactory.createPackaging('Secure Bag','EZ000333','Available',true);
        Secure_Packaging__c Seal = BVCL_TestDataFactory.createPackaging('Secure Seal','EZ333','Available',true);
        
        
        Secure_Bag__c bag1 = new Secure_Bag__c();
        bag1.Shipment__c = Ship1.id;
        bag1.Secure_Bag__c = SP_Bag.id;
        bag1.Linehaul_Type__c = 'Road';
        bag1.Finalised_Linehaul_Number__c = 'sss';
        bag1.Seal_Id__c = Seal.id;
        bag1.Current_Scan_Loction__c = 'Created';
        bag1.Next_Destination__c = 'Delhi';
        //bag1.Current_Scan_Hub__c = DelhiHub.id;
        insert bag1;
        
        //update bag1;
        System.runAs(u){
            TMS_LinehaulClass.Shipments('Finalised',DelhiHub.name);
            test.startTest();
            TMS_LinehaulClass.Shipments('Inbound',DelhiHub.name);
            bag1.Current_Scan_Hub__c = DelhiHub.id;
            bag1.Finalised_Linehaul_Number__c = null;
            
            update bag1;
            TMS_LinehaulClass.Shipments('Outbound',DelhiHub.name);
            Transport__c DelhiAir = BVCL_TestDataFactory.CreateAirport('Delhi Airport', true);
            Flight_Schedule__c flight = BVCL_TestDataFactory.createFlight('Delhi-Delhi', DelhiAir.id, DelhiAir.id, true);
            Transport__c Vehicle = BVCL_TestDataFactory.CreateVehicle('Honda12',true);
            TMS_DLHN__c dhln = new TMS_DLHN__c();
            
            bag1.Finalised_Linehaul_Number__c = 'FL2222';
            bag1.Flight_Schedule__c = flight.id;
            bag1.Vehicle__c = Vehicle.id;
            update bag1;
            List<Secure_Bag__c> baglist = new List<Secure_Bag__c>();
            baglist.add(bag1);
            TMS_LinehaulClass.SecureBagWrapper sbWrap = new TMS_LinehaulClass.SecureBagWrapper();
            sbWrap.sb = bag1;
            sbWrap.process = true;
            List<TMS_LinehaulClass.SecureBagWrapper> WrapList = new List<TMS_LinehaulClass.SecureBagWrapper>();
            WrapList.add(sbWrap);
            string bagjson = JSON.serialize(WrapList);
            
            
            TMS_LinehaulClass.SecureBagsList(baglist);
            TMS_LinehaulClass.FilteredBagList(baglist, 'Delhi', 'Completed', 'Valuable');
            TMS_LinehaulClass.FilteredBagByDest(baglist, 'Del');
            /*Secure_Packaging__c Seal2 = BVCL_TestDataFactory.createPackaging('Secure Seal','EZ0023232','Available',true);
            TMS_LinehaulClass.AddBox(bagjson, 'EZ333', Seal2.id, 'Delhi');
            
            TMS_LinehaulClass.currentUserHub();
            
            dhln.Name = 'Final Num';
            dhln.Last_Number__c = 1;
            dhln.Finalized_Number__c = 1;
            insert dhln;
            TMS_LinehaulClass.SaveProcess(bagjson, 'Air', 'FL1111', Flight.id, System.now(), '');
            TMS_LinehaulClass.SaveProcess(bagjson, 'Road', 'FL1111', '', System.now(), Vehicle.id);
            TMS_LinehaulClass.AddBagToLineHaul(bagjson);
            Ship1.Tracking_Status__c = 'Destination Port';
            update Ship1;*/
        }
        test.stopTest();
    }
    Public static testmethod void testShipments2(){
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator'];
        User u = new User(Alias = 'standt', Email='standarduser@testorg.com',
                          EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
                          LocaleSidKey='en_US', ProfileId = p.Id,
                          TimeZoneSidKey='America/Los_Angeles',
                          UserName='testuser@bvcl.com');
        insert u;
        
        Account BillingAcc = BVCL_TestDataFactory.createCustomer('BVCLBill Customer','Billing',true);
        Account ShipperAcc = BVCL_TestDataFactory.createCustomer('BVCLShipp Customer','Shipping',true);
        Hub__c DelhiHub = BVCL_TestDataFactory.CreateHub('Delhi', true, 'DELHI');
        FSE_Sales__c fse = BVCL_TestDataFactory.createFSE(DelhiHub.id,u.id,'Manager',true,true);
        Active_Pincode__c DelhiPin = BVCL_TestDataFactory.CreatePincode('110025', DelhiHub.id, 'Delhi', 'South', true);
        AddressBook__c ShipperAddress = BVCL_TestDataFactory.CreateAddress('Shipping',ShipperAcc.id,'Line 1',DelhiPin.id,'Cityyy',true);
        
        Shipment__c Ship1 = BVCL_TestDataFactory.CreateShipment(BillingAcc.id, ShipperAcc.id, ShipperAddress.id, ShipperAcc.id, ShipperAddress.id, false);
        ship1.Product_Description__c = 'Gold Jewellery';
        insert Ship1;
        
        Secure_Packaging__c SP_Bag = BVCL_TestDataFactory.createPackaging('Secure Bag','EZ000333','Available',true);
        Secure_Packaging__c Seal = BVCL_TestDataFactory.createPackaging('Secure Seal','EZ333','Available',true);
        
        
        Secure_Bag__c bag1 = new Secure_Bag__c();
        bag1.Shipment__c = Ship1.id;
        bag1.Secure_Bag__c = SP_Bag.id;
        bag1.Linehaul_Type__c = 'Road';
        bag1.Finalised_Linehaul_Number__c = 'sss';
        bag1.Seal_Id__c = Seal.id;
        bag1.Current_Scan_Loction__c = 'Created';
        bag1.Next_Destination__c = 'Delhi';
        //bag1.Current_Scan_Hub__c = DelhiHub.id;
        insert bag1;
        
        //update bag1;
        System.runAs(u){
            //TMS_LinehaulClass.Shipments('Finalised',DelhiHub.name);
            //TMS_LinehaulClass.Shipments('Inbound',DelhiHub.name);
            bag1.Current_Scan_Hub__c = DelhiHub.id;
            bag1.Finalised_Linehaul_Number__c = null;
            //update bag1;
            //TMS_LinehaulClass.Shipments('Outbound',DelhiHub.name);
            
            test.startTest();
            Transport__c DelhiAir = BVCL_TestDataFactory.CreateAirport('Delhi Airport', true);
            Flight_Schedule__c flight = BVCL_TestDataFactory.createFlight('Delhi-Delhi', DelhiAir.id, DelhiAir.id, true);
            Transport__c Vehicle = BVCL_TestDataFactory.CreateVehicle('Honda12',true);
            TMS_DLHN__c dhln = new TMS_DLHN__c();
            
            bag1.Finalised_Linehaul_Number__c = 'FL2222';
            bag1.Flight_Schedule__c = flight.id;
            bag1.Vehicle__c = Vehicle.id;
            update bag1;
            List<Secure_Bag__c> baglist = new List<Secure_Bag__c>();
            baglist.add(bag1);
            TMS_LinehaulClass.SecureBagWrapper sbWrap = new TMS_LinehaulClass.SecureBagWrapper();
            sbWrap.sb = bag1;
            sbWrap.process = true;
            List<TMS_LinehaulClass.SecureBagWrapper> WrapList = new List<TMS_LinehaulClass.SecureBagWrapper>();
            WrapList.add(sbWrap);
            string bagjson = JSON.serialize(WrapList);
            
            
            //TMS_LinehaulClass.SecureBagsList(baglist);
            //TMS_LinehaulClass.FilteredBagList(baglist, 'Delhi', 'Completed', 'Valuable');
            //TMS_LinehaulClass.FilteredBagByDest(baglist, 'Del');
            Secure_Packaging__c Seal2 = BVCL_TestDataFactory.createPackaging('Secure Seal','EZ0023232','Available',true);
            TMS_LinehaulClass.AddBox(bagjson, 'EZ333', Seal2.id, 'Delhi');
            
            TMS_LinehaulClass.currentUserHub();
            
            dhln.Name = 'Final Num';
            dhln.Last_Number__c = 1;
            dhln.Finalized_Number__c = 1;
            insert dhln;
            TMS_LinehaulClass.SaveProcess(bagjson, 'Air', 'FL1111', Flight.id, System.now(), '');
            TMS_LinehaulClass.SaveProcess(bagjson, 'Road', 'FL1111', '', System.now(), Vehicle.id);
            TMS_LinehaulClass.AddBagToLineHaul(bagjson);
            Ship1.Tracking_Status__c = 'Destination Port';
            update Ship1;
            TMS_LinehaulClass.LoggedInUserHub();
            TMS_LinehaulClass.FilteredByBagNo(bagjson,baglist,'33');
        }
        test.stopTest();
    }
}