force-app/main/default/objects/Order/fields/blng__BillNow__c.field-meta.xml
<CustomField>
    <fullName>blng__BillNow__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bill Now</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/ST_Bill_Now__c.field-meta.xml
<CustomField>
    <fullName>ST_Bill_Now__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bill Now</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/UpdateOrderBillnow.cls
global class UpdateOrderBillnow {

@InvocableMethod(label='Update Order Billnow' description='Update Billnow' category='order')
    public static void orderBillnow(List<Id> orderids) {
        List<order> listOrder = [Select Id, ST_Bill_Now__c, blng__BillNow__c FROM order WHERE Id In :orderids];
        
        for(order Orders : listOrder){
            Orders.blng__BillNow__c = true;
        }        
        Database.update(listOrder, false);
    } 
}