force-app/main/default/objects/Account/recordTypes/Billing.recordType-meta.xml
<RecordType>
    <fullName>Billing</fullName>
    <active>true</active>
    <description>Record Type for Domestic Customers.</description>
    <label>Billing</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Shipping.recordType-meta.xml
<RecordType>
    <fullName>Shipping</fullName>
    <active>true</active>
    <description>Record Type for Shipping Customers.</description>
    <label>Shipping</label>
</RecordType>

force-app/main/default/objects/Active_Pincode__c/Active_Pincode__c.object-meta.xml
<CustomObject>
    <label>Active Pincode</label>
    <nameField>
        <label>Pincode</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Active Pincodes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Active_Pincode__c/fields/Hub__c.field-meta.xml
<CustomField>
    <fullName>Hub__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hub</label>
    <referenceTo>Hub__c</referenceTo>
    <relationshipLabel>Active Pincodes</relationshipLabel>
    <relationshipName>Active_Pincodes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AddressBook__c/AddressBook__c.object-meta.xml
<CustomObject>
    <description>Primarily stores multiple shipping and billing addresses.</description>
    <label>Address Book</label>
    <nameField>
        <label>Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AddressBook__c/fields/Active_Pincode__c.field-meta.xml
<CustomField>
    <fullName>Active_Pincode__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Active Pincode</label>
    <referenceTo>Active_Pincode__c</referenceTo>
    <relationshipLabel>Addresses (Active Pincode)</relationshipLabel>
    <relationshipName>Addresses1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AddressBook__c/recordTypes/Billing.recordType-meta.xml
<RecordType>
    <fullName>Billing</fullName>
    <active>true</active>
    <label>Billing</label>
</RecordType>

force-app/main/default/objects/AddressBook__c/recordTypes/Shipping.recordType-meta.xml
<RecordType>
    <fullName>Shipping</fullName>
    <active>true</active>
    <label>Shipping</label>
</RecordType>

force-app/main/default/objects/Delivery__c/Delivery__c.object-meta.xml
<CustomObject>
    <label>Delivery</label>
    <nameField>
        <displayFormat>D-{0000000}</displayFormat>
        <label>Delivery Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deliveries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Address</label>
    <referenceTo>AddressBook__c</referenceTo>
    <relationshipLabel>Deliveries</relationshipLabel>
    <relationshipName>Deliveries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Delivery__c/fields/Shipment__c.field-meta.xml
<CustomField>
    <fullName>Shipment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shipment</label>
    <referenceTo>Shipment__c</referenceTo>
    <relationshipLabel>Deliveries</relationshipLabel>
    <relationshipName>Deliveries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Delivery__c/fields/Shipping_Note_Number__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Note_Number__c</fullName>
    <formula>Shipment__r.Shipping_Note_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Shipping Note Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Delivery__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
                <default>true</default>
                <label>Assigned</label>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FSE_Sales__c/FSE_Sales__c.object-meta.xml
<CustomObject>
    <label>Hub Employee</label>
    <nameField>
        <displayFormat>FS-{000000}</displayFormat>
        <label>FSE &amp; Sales Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hub Employees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FSE_Sales__c/fields/Hub__c.field-meta.xml
<CustomField>
    <fullName>Hub__c</fullName>
    <label>Hub</label>
    <referenceTo>Hub__c</referenceTo>
    <relationshipLabel>FSE &amp; Sales</relationshipLabel>
    <relationshipName>FSE_Sales</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Hub__c/Hub__c.object-meta.xml
<CustomObject>
    <label>Hub</label>
    <nameField>
        <label>Hub Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hubs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Hub__c/fields/Airport__c.field-meta.xml
<CustomField>
    <fullName>Airport__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Airport</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Transport__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Airport</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Transport__c</referenceTo>
    <relationshipLabel>Hubs</relationshipLabel>
    <relationshipName>Hubs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Secure_Bag__c/Secure_Bag__c.object-meta.xml
<CustomObject>
    <label>Secure Bag</label>
    <nameField>
        <displayFormat>SB-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Secure Bags</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Secure_Bag__c/fields/Secure_Bag__c.field-meta.xml
<CustomField>
    <fullName>Secure_Bag__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Secure Bag</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Secure_Packaging__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Secure Bag</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Secure_Packaging__c</referenceTo>
    <relationshipLabel>Secure Bags</relationshipLabel>
    <relationshipName>Secure_Bags</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Secure_Bag__c/fields/Shipment__c.field-meta.xml
<CustomField>
    <fullName>Shipment__c</fullName>
    <label>Shipment</label>
    <referenceTo>Shipment__c</referenceTo>
    <relationshipLabel>Secure Bags</relationshipLabel>
    <relationshipName>SecureBags</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Secure_Packaging__c/Secure_Packaging__c.object-meta.xml
<CustomObject>
    <label>Secure Packaging</label>
    <nameField>
        <label>Shipping Note Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Secure Packagings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Secure_Packaging__c/fields/Shipment__c.field-meta.xml
<CustomField>
    <fullName>Shipment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shipment</label>
    <referenceTo>Shipment__c</referenceTo>
    <relationshipLabel>Secure Packagings</relationshipLabel>
    <relationshipName>Secure_Packagings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Secure_Packaging__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Consumed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Shipment__c/Shipment__c.object-meta.xml
<CustomObject>
    <description>Shipment object stores shipments requested against a pickup.</description>
    <label>Shipment</label>
    <nameField>
        <displayFormat>ST-{0000000}</displayFormat>
        <label>Shipment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipment__c/fields/AddressBook__c.field-meta.xml
<CustomField>
    <fullName>AddressBook__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Address</label>
    <referenceTo>AddressBook__c</referenceTo>
    <relationshipLabel>Shipments</relationshipLabel>
    <relationshipName>Shipments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Destination_Address_Name__c.field-meta.xml
<CustomField>
    <fullName>Destination_Address_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Destination Address Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Consignee_Name_TMS__c</field>
            <operation>equals</operation>
            <valueField>AddressBook__c.Customer__c</valueField>
        </filterItems>
        <filterItems>
            <field>AddressBook__c.Is_Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>AddressBook__c</referenceTo>
    <relationshipLabel>Shipment Delivery</relationshipLabel>
    <relationshipName>ShipmentsDelivery</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Shipping_Note_Number__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Note_Number__c</fullName>
    <description>This is the Domestic Shipping Note number</description>
    <label>Shipping Note Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Pending Billing</fullName>
            </value>
            <value>
                <fullName>Verified For Billing</fullName>
            </value>
            <value>
                <fullName>Picked for Billing</fullName>
            </value>
            <value>
                <fullName>ACR Consumed</fullName>
            </value>
            <value>
                <fullName>Billed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Shipment_Tracking__c/Shipment_Tracking__c.object-meta.xml
<CustomObject>
    <label>Tracking</label>
    <nameField>
        <displayFormat>STN-{000000}</displayFormat>
        <label>Shipment Tracking Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tracking</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipment_Tracking__c/fields/Airport__c.field-meta.xml
<CustomField>
    <fullName>Airport__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Airport</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Transport__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Airport</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Transport__c</referenceTo>
    <relationshipName>Shipment_Trackings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipment_Tracking__c/fields/Hub__c.field-meta.xml
<CustomField>
    <fullName>Hub__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Name of Hub</label>
    <referenceTo>Hub__c</referenceTo>
    <relationshipName>Shipment_Trackings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipment_Tracking__c/fields/Shipment__c.field-meta.xml
<CustomField>
    <fullName>Shipment__c</fullName>
    <label>Shipment</label>
    <referenceTo>Shipment__c</referenceTo>
    <relationshipLabel>Tracking</relationshipLabel>
    <relationshipName>Shipment_Trackings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Transport__c/Transport__c.object-meta.xml
<CustomObject>
    <description>Transport Master</description>
    <label>Transport</label>
    <nameField>
        <label>Airport/BVC Vehicle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transport__c/recordTypes/Airport.recordType-meta.xml
<RecordType>
    <fullName>Airport</fullName>
    <active>true</active>
    <label>Airport</label>
</RecordType>

force-app/main/default/classes/TMS_DeliveryControllerTest.cls
@isTest
public class TMS_DeliveryControllerTest {
    
    @isTest
    public static void test1(){
        Account BillingAcc = BVCL_TestDataFactory.createCustomer('BVCLBill Customer','Billing',true);
        Account ShipperAcc = BVCL_TestDataFactory.createCustomer('BVCLShipp Customer','Shipping',true);
        Transport__c DelhiAir = BVCL_TestDataFactory.CreateAirport('Delhi Airport', true);
        Hub__c DelhiHub = BVCL_TestDataFactory.CreateHub('Delhi', true, 'DELHI');
        FSE_Sales__c fse = BVCL_TestDataFactory.createFSE(DelhiHub.id,userInfo.getUserId(),'Manager',true,true);
        Active_Pincode__c DelhiPin = BVCL_TestDataFactory.CreatePincode('110025', DelhiHub.id, 'Delhi', 'South', true);
        AddressBook__c ShipperAddress = BVCL_TestDataFactory.CreateAddress('Shipping',ShipperAcc.id,'Line 1',DelhiPin.id,'Cityyy',true);
        Secure_Packaging__c Label = BVCL_TestDataFactory.createPackaging('Shipping Label', 'YYY7777', 'Available', true);
        Shipment__c Ship1 = BVCL_TestDataFactory.CreateShipment(BillingAcc.id, ShipperAcc.id, ShipperAddress.id, ShipperAcc.id, ShipperAddress.id, false);
        Ship1.Shipping_Note_Number__c = 'EB78464734';
        //system.debug('SNN'+Ship1.Shipping_Note_Number__c);
        insert Ship1;
        
        ship1.Destination_Address_Name__c= ShipperAddress.id;
        Update Ship1;
        
        Delivery__c delivery = new Delivery__c();
        delivery.Shipment__c = Ship1.Id;
        delivery.Status__c = 'Accepted';
        delivery.Address__c = ShipperAddress.id;
        
        Insert delivery;
        
        
        //system.debug('SNN'+Ship1.Shipping_Note_Number__c);
        Secure_Packaging__c SP_Bag = BVCL_TestDataFactory.createPackaging('Secure Bag','EZ000333','Available',true);
        Secure_Bag__c bag1 = new Secure_Bag__c();
        bag1.Shipment__c = Ship1.id;
        bag1.Secure_Bag__c = SP_Bag.id;
        insert bag1;
        //system.debug('SNN'+Ship1.Shipping_Note_Number__c);
        test.startTest();
        TMS_DeliveryController.allSecureBagGet(delivery.Id);
        Shipment_Tracking__c st = new Shipment_Tracking__c(); 
        st.Hub__c = DelhiHub.id;
        st.Airport__c = DelhiAir.id;
        TMS_DeliveryController.insertUpdateRecord(st, new List<Secure_Bag__c>{bag1});
        TMS_DeliveryListView.viewAllDelivery();
        TMS_DeliveryListView.updateDelivery(new List<delivery__c>{delivery});
        test.stopTest();
    }
    
}