force-app/main/default/objects/Account/recordTypes/Billing.recordType-meta.xml
<RecordType>
    <fullName>Billing</fullName>
    <active>true</active>
    <description>Record Type for Domestic Customers.</description>
    <label>Billing</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Shipping.recordType-meta.xml
<RecordType>
    <fullName>Shipping</fullName>
    <active>true</active>
    <description>Record Type for Shipping Customers.</description>
    <label>Shipping</label>
</RecordType>

force-app/main/default/objects/Flight_Schedule__c/Flight_Schedule__c.object-meta.xml
<CustomObject>
    <description>Flight Schedule Master</description>
    <label>Flight Schedule</label>
    <nameField>
        <label>Flight Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flight Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Hub__c/Hub__c.object-meta.xml
<CustomObject>
    <label>Hub</label>
    <nameField>
        <label>Hub Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hubs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Secure_Bag__c/Secure_Bag__c.object-meta.xml
<CustomObject>
    <label>Secure Bag</label>
    <nameField>
        <displayFormat>SB-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Secure Bags</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Secure_Bag__c/fields/Current_Origin_City__c.field-meta.xml
<CustomField>
    <fullName>Current_Origin_City__c</fullName>
    <label>Current Origin City</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Secure_Bag__c/fields/Current_Scan_Hub__c.field-meta.xml
<CustomField>
    <fullName>Current_Scan_Hub__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Current Scan Hub</label>
    <referenceTo>Hub__c</referenceTo>
    <relationshipLabel>Secure Bags</relationshipLabel>
    <relationshipName>Secure_Bags</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Secure_Bag__c/fields/Finalised_Linehaul_Number__c.field-meta.xml
<CustomField>
    <fullName>Finalised_Linehaul_Number__c</fullName>
    <label>Finalised Linehaul Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Secure_Bag__c/fields/Finalized_Time__c.field-meta.xml
<CustomField>
    <fullName>Finalized_Time__c</fullName>
    <label>Finalized Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Secure_Bag__c/fields/Flight_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Flight_Date_Time__c</fullName>
    <label>Flight Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Secure_Bag__c/fields/Flight_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Flight_Schedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Flight Schedule</label>
    <referenceTo>Flight_Schedule__c</referenceTo>
    <relationshipLabel>Secure Bags</relationshipLabel>
    <relationshipName>Secure_Bags</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Secure_Bag__c/fields/Linehaul_Type__c.field-meta.xml
<CustomField>
    <fullName>Linehaul_Type__c</fullName>
    <label>Linehaul Type</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Secure_Bag__c/fields/Lock_Status__c.field-meta.xml
<CustomField>
    <fullName>Lock_Status__c</fullName>
    <label>Lock Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Lock</fullName>
            </value>
            <value>
                <fullName>Unlock</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Secure_Bag__c/fields/Next_Destination__c.field-meta.xml
<CustomField>
    <fullName>Next_Destination__c</fullName>
    <label>Next Destination</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Branch</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Secure_Bag__c/fields/Seal_Id__c.field-meta.xml
<CustomField>
    <fullName>Seal_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Seal Id</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Secure_Packaging__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Secure Seal</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Secure_Packaging__c</referenceTo>
    <relationshipLabel>Secure Bags (Seal Id)</relationshipLabel>
    <relationshipName>Secure_Bags2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Secure_Bag__c/fields/Secure_Bag__c.field-meta.xml
<CustomField>
    <fullName>Secure_Bag__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Secure Bag</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Secure_Packaging__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Secure Bag</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Secure_Packaging__c</referenceTo>
    <relationshipLabel>Secure Bags</relationshipLabel>
    <relationshipName>Secure_Bags</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Secure_Bag__c/fields/Shipment__c.field-meta.xml
<CustomField>
    <fullName>Shipment__c</fullName>
    <label>Shipment</label>
    <referenceTo>Shipment__c</referenceTo>
    <relationshipLabel>Secure Bags</relationshipLabel>
    <relationshipName>SecureBags</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Shipment__c/Shipment__c.object-meta.xml
<CustomObject>
    <description>Shipment object stores shipments requested against a pickup.</description>
    <label>Shipment</label>
    <nameField>
        <displayFormat>ST-{0000000}</displayFormat>
        <label>Shipment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/TmsUpdateSecureBagTriggerTest.cls
@IsTest
public class TmsUpdateSecureBagTriggerTest {
    @IsTest
    public static void test1() {
        Hub__c hub1 = new Hub__c();
        hub1 = BVCL_TestDataFactory.CreateHub('name', true, 'MUMBAI');
        
        Hub__c hub2 = new Hub__c();
        hub2 = BVCL_TestDataFactory.CreateHub('name1', true, 'DELHI');
        
        Account BillingAcc = BVCL_TestDataFactory.createCustomer('BVCLBill Customer','Billing',true);
        Account ShipperAcc = BVCL_TestDataFactory.createCustomer('BVCLShipp Customer','Shipping',true);
        Shipment__c Ship1 = BVCL_TestDataFactory.CreateShipment(BillingAcc.id, ShipperAcc.id, null, ShipperAcc.id, null, true);
        
        Flight_Schedule__c testFlightSchedule = new Flight_Schedule__c();
        insert testFlightSchedule;
        
        Secure_Bag__c testSecureBag = new Secure_Bag__c();
        testSecureBag.Shipment__c = Ship1.Id;
        testSecureBag.Current_Scan_Hub__c = hub1.Id;
        testSecureBag.Current_Origin_City__c = 'Delhi';
        testSecureBag.Finalised_Linehaul_Number__c = null;
        testSecureBag.Flight_Schedule__c = null;
        testSecureBag.Linehaul_Type__c = null;
        testSecureBag.Next_Destination__c = null;
        testSecureBag.Flight_Date_Time__c = null;
        testSecureBag.Finalized_Time__c = null;
        
        insert testSecureBag;
        
        Secure_Bag__c testSecureBagToUpdate = [SELECT Id, Current_Scan_Hub__c FROM Secure_Bag__c LIMIT 1];
        testSecureBagToUpdate.Current_Scan_Hub__c = hub2.Id;
        
        Test.startTest();
        update testSecureBagToUpdate;
        Test.stopTest();
        
        
    }
    
    
    
    /*
    @IsTest
    public static void test2() {
        
        Shipment__c testShipment = new Shipment__c();
        insert testShipment;
        
        Secure_Bag__c testSecureBag = new Secure_Bag__c();
        testSecureBag.Shipment__c = testShipment.Id;
        testSecureBag.Lock_Status__c = 'Lock';
        
        insert testSecureBag;
        
        Secure_Bag__c testSecureBagToUpdate = [SELECT Id, Lock_Status__c, Seal_Id__c FROM Secure_Bag__c LIMIT 1];
        testSecureBagToUpdate.Lock_Status__c = 'Unlock';
        
        Test.startTest();
        update testSecureBagToUpdate;
        Test.stopTest();
        
        Secure_Bag__c updatedSecureBag = [SELECT Id, Lock_Status__c, Seal_Id__c FROM Secure_Bag__c WHERE Id = :testSecureBagToUpdate.Id];
        System.assertEquals('Unlock', updatedSecureBag.Lock_Status__c);
        System.assertEquals(null, updatedSecureBag.Seal_Id__c);
    }
    
    @IsTest
    public static void test3() {
        
        Shipment__c testShipment = new Shipment__c();
        insert testShipment;
        
        Secure_Bag__c testSecureBag = new Secure_Bag__c();
        testSecureBag.Shipment__c = testShipment.Id;
        testSecureBag.Lock_Status__c = 'Unlock';
        insert testSecureBag;
        
        Secure_Bag__c testSecureBagToUpdate = [SELECT Id, Lock_Status__c, Seal_Id__c FROM Secure_Bag__c LIMIT 1];
        //testSecureBagToUpdate.Seal_Id__c = 'X0737103';
        testSecureBagToUpdate.Lock_Status__c = 'Lock';
        
        Test.startTest();
        update testSecureBagToUpdate;
        Test.stopTest();
        
        Secure_Bag__c updatedSecureBag = [SELECT Id, Lock_Status__c, Seal_Id__c FROM Secure_Bag__c WHERE Id = :testSecureBagToUpdate.Id];
        System.assertEquals('Lock', updatedSecureBag.Lock_Status__c);
        System.assertEquals(null, updatedSecureBag.Seal_Id__c);
    }
    
    @IsTest
    public static void test4() {
        
        Shipment__c testShipment = new Shipment__c();
        insert testShipment;
        
        Secure_Bag__c testSecureBag = new Secure_Bag__c();
        testSecureBag.Next_Destination__c = 'MUMBAI';
        testSecureBag.Shipment__c = testShipment.Id;
        insert testSecureBag;
        
        Secure_Bag__c testSecureBagToUpdate = [SELECT Id, Next_Destination__c FROM Secure_Bag__c LIMIT 1];
        testSecureBagToUpdate.Next_Destination__c = 'MUMBAI';
        
        Test.startTest();
        update testSecureBagToUpdate;
        Test.stopTest();
        
        Secure_Bag__c updatedSecureBag = [SELECT Id, Next_Destination__c FROM Secure_Bag__c WHERE Id = :testSecureBagToUpdate.Id];
        System.assertEquals('MUMBAI', updatedSecureBag.Next_Destination__c);
    }*/
}