force-app/main/default/objects/Account/recordTypes/Billing.recordType-meta.xml
<RecordType>
    <fullName>Billing</fullName>
    <active>true</active>
    <description>Record Type for Domestic Customers.</description>
    <label>Billing</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Shipping.recordType-meta.xml
<RecordType>
    <fullName>Shipping</fullName>
    <active>true</active>
    <description>Record Type for Shipping Customers.</description>
    <label>Shipping</label>
</RecordType>

force-app/main/default/objects/Hub__c/Hub__c.object-meta.xml
<CustomObject>
    <label>Hub</label>
    <nameField>
        <label>Hub Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hubs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Hub__c/fields/Airport__c.field-meta.xml
<CustomField>
    <fullName>Airport__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Airport</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Transport__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Airport</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Transport__c</referenceTo>
    <relationshipLabel>Hubs</relationshipLabel>
    <relationshipName>Hubs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Secure_Bag__c/Secure_Bag__c.object-meta.xml
<CustomObject>
    <label>Secure Bag</label>
    <nameField>
        <displayFormat>SB-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Secure Bags</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Secure_Bag__c/fields/Current_Scan_Airport__c.field-meta.xml
<CustomField>
    <fullName>Current_Scan_Airport__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Current scan Airport</label>
    <referenceTo>Transport__c</referenceTo>
    <relationshipLabel>Secure Bags (Airport)</relationshipLabel>
    <relationshipName>Secure_Bags1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Secure_Bag__c/fields/Current_Scan_Hub__c.field-meta.xml
<CustomField>
    <fullName>Current_Scan_Hub__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Current Scan Hub</label>
    <referenceTo>Hub__c</referenceTo>
    <relationshipLabel>Secure Bags</relationshipLabel>
    <relationshipName>Secure_Bags</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Secure_Bag__c/fields/Current_Scan_Loction__c.field-meta.xml
<CustomField>
    <fullName>Current_Scan_Loction__c</fullName>
    <label>Current Scan Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
            </value>
            <value>
                <fullName>Out for Pickup</fullName>
            </value>
            <value>
                <fullName>Picked Up</fullName>
            </value>
            <value>
                <fullName>Origin Hub</fullName>
            </value>
            <value>
                <fullName>Origin Port</fullName>
            </value>
            <value>
                <fullName>Transit Hub</fullName>
            </value>
            <value>
                <fullName>Transit Port</fullName>
            </value>
            <value>
                <fullName>Destination Port</fullName>
            </value>
            <value>
                <fullName>Destination Hub</fullName>
            </value>
            <value>
                <fullName>Out for Delivery</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Secure_Bag__c/fields/Seal_Id__c.field-meta.xml
<CustomField>
    <fullName>Seal_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Seal Id</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Secure_Packaging__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Secure Seal</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Secure_Packaging__c</referenceTo>
    <relationshipLabel>Secure Bags (Seal Id)</relationshipLabel>
    <relationshipName>Secure_Bags2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Secure_Bag__c/fields/Secure_Bag__c.field-meta.xml
<CustomField>
    <fullName>Secure_Bag__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Secure Bag</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Secure_Packaging__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Secure Bag</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Secure_Packaging__c</referenceTo>
    <relationshipLabel>Secure Bags</relationshipLabel>
    <relationshipName>Secure_Bags</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Secure_Bag__c/fields/Shipment__c.field-meta.xml
<CustomField>
    <fullName>Shipment__c</fullName>
    <label>Shipment</label>
    <referenceTo>Shipment__c</referenceTo>
    <relationshipLabel>Secure Bags</relationshipLabel>
    <relationshipName>SecureBags</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Secure_Packaging__c/Secure_Packaging__c.object-meta.xml
<CustomObject>
    <label>Secure Packaging</label>
    <nameField>
        <label>Shipping Note Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Secure Packagings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Secure_Packaging__c/fields/Shipment__c.field-meta.xml
<CustomField>
    <fullName>Shipment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shipment</label>
    <referenceTo>Shipment__c</referenceTo>
    <relationshipLabel>Secure Packagings</relationshipLabel>
    <relationshipName>Secure_Packagings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipment__c/Shipment__c.object-meta.xml
<CustomObject>
    <description>Shipment object stores shipments requested against a pickup.</description>
    <label>Shipment</label>
    <nameField>
        <displayFormat>ST-{0000000}</displayFormat>
        <label>Shipment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipment__c/fields/Scan_Time__c.field-meta.xml
<CustomField>
    <fullName>Scan_Time__c</fullName>
    <label>Scan Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Shipment_Tracking__c/Shipment_Tracking__c.object-meta.xml
<CustomObject>
    <label>Tracking</label>
    <nameField>
        <displayFormat>STN-{000000}</displayFormat>
        <label>Shipment Tracking Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tracking</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipment_Tracking__c/fields/Airport__c.field-meta.xml
<CustomField>
    <fullName>Airport__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Airport</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Transport__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Airport</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Transport__c</referenceTo>
    <relationshipName>Shipment_Trackings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipment_Tracking__c/fields/Hub__c.field-meta.xml
<CustomField>
    <fullName>Hub__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Name of Hub</label>
    <referenceTo>Hub__c</referenceTo>
    <relationshipName>Shipment_Trackings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipment_Tracking__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
                <default>true</default>
                <label>Created</label>
            </value>
            <value>
                <fullName>Out for Pickup</fullName>
            </value>
            <value>
                <fullName>Picked Up</fullName>
            </value>
            <value>
                <fullName>Origin Hub</fullName>
            </value>
            <value>
                <fullName>Origin Port</fullName>
            </value>
            <value>
                <fullName>Transit Hub</fullName>
            </value>
            <value>
                <fullName>Transit Port</fullName>
            </value>
            <value>
                <fullName>Destination Port</fullName>
            </value>
            <value>
                <fullName>Destination Hub</fullName>
            </value>
            <value>
                <fullName>Out for Delivery</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Out of Linehaul</fullName>
            </value>
            <value>
                <fullName>Linehaul Deposit</fullName>
            </value>
            <value>
                <fullName>Linehaul In-Transit</fullName>
            </value>
            <value>
                <fullName>Linehaul Retrieved</fullName>
            </value>
            <value>
                <fullName>Airline Deposited</fullName>
            </value>
            <value>
                <fullName>AWB Booked</fullName>
            </value>
            <value>
                <fullName>AWB Finalized</fullName>
            </value>
            <value>
                <fullName>Flight Arrived</fullName>
            </value>
            <value>
                <fullName>Flight Departed</fullName>
            </value>
            <value>
                <fullName>On-Route Airport</fullName>
            </value>
            <value>
                <fullName>Pre-Flight at Airport</fullName>
            </value>
            <value>
                <fullName>Pre-Retrieval at Airport</fullName>
            </value>
            <value>
                <fullName>Retrieved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Shipment_Tracking__c/fields/Scan_Time__c.field-meta.xml
<CustomField>
    <fullName>Scan_Time__c</fullName>
    <label>Scan Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Shipment_Tracking__c/fields/Shipment__c.field-meta.xml
<CustomField>
    <fullName>Shipment__c</fullName>
    <label>Shipment</label>
    <referenceTo>Shipment__c</referenceTo>
    <relationshipLabel>Tracking</relationshipLabel>
    <relationshipName>Shipment_Trackings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Transport__c/Transport__c.object-meta.xml
<CustomObject>
    <description>Transport Master</description>
    <label>Transport</label>
    <nameField>
        <label>Airport/BVC Vehicle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transport__c/recordTypes/Airport.recordType-meta.xml
<RecordType>
    <fullName>Airport</fullName>
    <active>true</active>
    <label>Airport</label>
</RecordType>

force-app/main/default/classes/TM_ShipmentTrackerController_Test.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 12-11-2021
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
@isTest
public class TM_ShipmentTrackerController_Test {
    @isTest

    public static void Test1(){
        Transport__c Airport = BVCL_TestDataFactory.CreateAirport('Delhi Airport',true);
        Hub__c hub = BVCL_TestDataFactory.CreateHub('DELHI',false,'DELHI');
        hub.Airport__c = Airport.id;
        insert hub;
        Secure_Packaging__c Seal = BVCL_TestDataFactory.createPackaging('Secure Seal','EZ333','Available',true);
        Secure_Packaging__c SP_Bag = BVCL_TestDataFactory.createPackaging('Secure Bag','EZ000333','Available',true);
        
        Account BillingAcc = BVCL_TestDataFactory.createCustomer('BVCLBill Customer','Billing',true);
        Account ShipperAcc = BVCL_TestDataFactory.createCustomer('BVCLShipp Customer','Shipping',true);
        Shipment__c Ship1 = BVCL_TestDataFactory.CreateShipment(BillingAcc.id, ShipperAcc.id, null, ShipperAcc.id, null, true);
        
        
        Secure_Bag__c bag1 = new Secure_Bag__c();
        bag1.Shipment__c = Ship1.id;
        bag1.Secure_Bag__c = SP_Bag.id;
        bag1.Seal_Id__c = Seal.id;
        bag1.Current_Scan_Loction__c = 'Created';
        bag1.Current_Scan_Hub__c = hub.id;
        //bag1.Current_Scan_Airport__c = Airport.id;
        insert bag1;
        List<Secure_Bag__c> BagList = new List<Secure_Bag__c>();
        BagList.add(bag1);
        
        Map<string,Secure_Bag__c> bagMap = new Map<string,Secure_Bag__c>();
        bagMap.put(SP_Bag.name, bag1);
        TM_ShipmentTrackerController.bagBySealId(Seal.name);
        
        TM_ShipmentTrackerController.ShipmetWrap wr= new TM_ShipmentTrackerController.ShipmetWrap();
        wr.shipmentRecordMap = bagMap;
        TM_ShipmentTrackerController.scanningInProgress(wr);
        
        Shipment_Tracking__c st = new Shipment_Tracking__c();
        st.Shipment__c = Ship1.id;
        st.Location__c = 'Origin Hub';
        st.Hub__c = hub.id; 
        st.Scan_Time__c = system.now();
        //insert st;
        Test.startTest();
        TM_ShipmentTrackerController.bagBySecureBagId(SP_Bag.name,st,'');
        TM_ShipmentTrackerController.bagBySecureBagId(SP_Bag.name,st,'Misrouted');
        TM_ShipmentTrackerController.updateSecureBag(st, BagList, wr, 'Unlock');
        TM_ShipmentTrackerController.updateNormalBag(st, BagList);
        Test.stopTest();
    }

    @isTest    
    public static void Test2(){
        Transport__c Airport = BVCL_TestDataFactory.CreateAirport('Delhi Airport',true);
        Hub__c hub = BVCL_TestDataFactory.CreateHub('DELHI',false,'DELHI');
        hub.Airport__c = Airport.id;
        insert hub;

        Secure_Packaging__c Seal = BVCL_TestDataFactory.createPackaging('Secure Seal','EZ333','Available',true);
        Secure_Packaging__c SP_Bag = BVCL_TestDataFactory.createPackaging('Secure Bag','EZ000333','Available',true);
        
        Account BillingAcc = BVCL_TestDataFactory.createCustomer('BVCLBill Customer','Billing',true);
        Account ShipperAcc = BVCL_TestDataFactory.createCustomer('BVCLShipp Customer','Shipping',true);
        Shipment__c Ship1 = BVCL_TestDataFactory.CreateShipment(BillingAcc.id, ShipperAcc.id, null, ShipperAcc.id, null, true);

        //Shipment__c Ship2 = BVCL_TestDataFactory.CreateShipment(BillingAcc.id, ShipperAcc.id, null, ShipperAcc.id, null, true);
        
        Secure_Bag__c bag1 = new Secure_Bag__c();
        bag1.Shipment__c = Ship1.id;
        bag1.Secure_Bag__c = SP_Bag.id;
        bag1.Seal_Id__c = Seal.id;
        bag1.Current_Scan_Loction__c = 'Created'; 
        insert bag1;

        Secure_Bag__c bag2 = new Secure_Bag__c();
        bag2.Shipment__c = Ship1.id;
        bag2.Secure_Bag__c = SP_Bag.id;
        bag2.Seal_Id__c = Seal.id;
        bag2.Current_Scan_Loction__c = 'Created'; 
        bag1.Current_Scan_Airport__c = Airport.id;
        insert bag2;

        List<Secure_Bag__c> BagList = new List<Secure_Bag__c>();
        BagList.add(bag2);
        
        Map<string,Secure_Bag__c> bagMap = new Map<string,Secure_Bag__c>();
        bagMap.put(SP_Bag.name, bag1);
        
        TM_ShipmentTrackerController.ShipmetWrap wr= new TM_ShipmentTrackerController.ShipmetWrap();
        wr.shipmentRecordMap = bagMap;
        
        Shipment_Tracking__c st = new Shipment_Tracking__c();
        st.Shipment__c = Ship1.id;
        st.Location__c = 'Origin Hub';
        st.hub__c= hub.id;  
 
        Test.startTest();
        TM_ShipmentTrackerController.secureBagGet(SP_Bag.name);
        TM_ShipmentTrackerController.updateSecureBag(st, BagList, wr, 'Unlock');
        BagList = new List<Secure_Bag__c>();
        TM_ShipmentTrackerController.updateSecureBag(st, BagList, wr, 'Unlock');
        Test.stopTest();
    }

    @isTest    
    public static void Test3(){
        Transport__c Airport = BVCL_TestDataFactory.CreateAirport('Delhi Airport',true);
        Hub__c hub = BVCL_TestDataFactory.CreateHub('DELHI',false,'DELHI');
        hub.Airport__c = Airport.id;
        insert hub;
        Secure_Packaging__c Seal = BVCL_TestDataFactory.createPackaging('Secure Seal','EZ333','Available',true);
        Secure_Packaging__c SP_Bag = BVCL_TestDataFactory.createPackaging('Secure Bag','EZ000333','Available',true);
        
        Account BillingAcc = BVCL_TestDataFactory.createCustomer('BVCLBill Customer','Billing',true);
        Account ShipperAcc = BVCL_TestDataFactory.createCustomer('BVCLShipp Customer','Shipping',true);
        Shipment__c Ship1 = BVCL_TestDataFactory.CreateShipment(BillingAcc.id, ShipperAcc.id, null, ShipperAcc.id, null, true);
 
        Secure_Bag__c bag1 = new Secure_Bag__c();
        bag1.Shipment__c = Ship1.id;
        bag1.Secure_Bag__c = SP_Bag.id;
        bag1.Seal_Id__c = Seal.id;
        bag1.Current_Scan_Loction__c = 'Created';
        insert bag1;

        Secure_Bag__c bag2 = new Secure_Bag__c();
        bag2.Shipment__c = Ship1.id;
        bag2.Secure_Bag__c = SP_Bag.id;
        bag2.Seal_Id__c = Seal.id;
        bag2.Current_Scan_Loction__c = 'Created'; 
        bag1.Current_Scan_Airport__c = Airport.id;
        insert bag2;

        List<Secure_Bag__c> BagList = new List<Secure_Bag__c>();
        BagList.add(bag2);
        
        Map<string,Secure_Bag__c> bagMap = new Map<string,Secure_Bag__c>();
        bagMap.put(SP_Bag.name, bag1);
        
        TM_ShipmentTrackerController.ShipmetWrap wr= new TM_ShipmentTrackerController.ShipmetWrap();
        wr.shipmentRecordMap = bagMap;
        
        Shipment_Tracking__c st = new Shipment_Tracking__c();
        st.Shipment__c = Ship1.id; 
        st.Location__c = 'Out for Delivery';

        Test.startTest();
        TM_ShipmentTrackerController.secureBagGet(SP_Bag.name);
        TM_ShipmentTrackerController.updateSecureBag(st, BagList, wr, 'Unlock');
        BagList = new List<Secure_Bag__c>();
        TM_ShipmentTrackerController.updateSecureBag(st, BagList, wr, 'Unlock');
        TM_ShipmentTrackerController.LoggedInUserHub();
        Test.stopTest();
    }



}