force-app/main/default/objects/Account/recordTypes/Billing.recordType-meta.xml
<RecordType>
    <fullName>Billing</fullName>
    <active>true</active>
    <description>Record Type for Domestic Customers.</description>
    <label>Billing</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Shipping.recordType-meta.xml
<RecordType>
    <fullName>Shipping</fullName>
    <active>true</active>
    <description>Record Type for Shipping Customers.</description>
    <label>Shipping</label>
</RecordType>

force-app/main/default/objects/AddressBook__c/AddressBook__c.object-meta.xml
<CustomObject>
    <description>Primarily stores multiple shipping and billing addresses.</description>
    <label>Address Book</label>
    <nameField>
        <label>Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AddressBook__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Customer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Customer_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Addresses</relationshipLabel>
    <relationshipName>Addresses</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AddressBook__c/recordTypes/Billing.recordType-meta.xml
<RecordType>
    <fullName>Billing</fullName>
    <active>true</active>
    <label>Billing</label>
</RecordType>

force-app/main/default/objects/AddressBook__c/recordTypes/Shipping.recordType-meta.xml
<RecordType>
    <fullName>Shipping</fullName>
    <active>true</active>
    <label>Shipping</label>
</RecordType>

force-app/main/default/objects/Flight_Schedule__c/Flight_Schedule__c.object-meta.xml
<CustomObject>
    <description>Flight Schedule Master</description>
    <label>Flight Schedule</label>
    <nameField>
        <label>Flight Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flight Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Flight_Schedule__c/fields/Destination__c.field-meta.xml
<CustomField>
    <fullName>Destination__c</fullName>
    <label>Destination</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Flight_Schedule__c/fields/Origin_Airport__c.field-meta.xml
<CustomField>
    <fullName>Origin_Airport__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Origin Airport</label>
    <referenceTo>Transport__c</referenceTo>
    <relationshipLabel>Flight Schedules</relationshipLabel>
    <relationshipName>Flight_Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Linehaul__c/Linehaul__c.object-meta.xml
<CustomObject>
    <label>Master AWB</label>
    <nameField>
        <displayFormat>LH-{00000}</displayFormat>
        <label>Linehaul Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Master AWB</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Linehaul__c/fields/Destination__c.field-meta.xml
<CustomField>
    <fullName>Destination__c</fullName>
    <label>Destination</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Linehaul__c/fields/Origin__c.field-meta.xml
<CustomField>
    <fullName>Origin__c</fullName>
    <label>Origin</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Secure_Packaging__c/Secure_Packaging__c.object-meta.xml
<CustomObject>
    <label>Secure Packaging</label>
    <nameField>
        <label>Shipping Note Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Secure Packagings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Secure_Packaging__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Consumed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transport__c/Transport__c.object-meta.xml
<CustomObject>
    <description>Transport Master</description>
    <label>Transport</label>
    <nameField>
        <label>Airport/BVC Vehicle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/TMS_Lookup2.cls
/**
* @description       : 
* @author            : Imran
* @group             : 
* @last modified on  : 05-11-2023
* @last modified by  : Imran
**/
public class TMS_Lookup2 {
    @AuraEnabled(cacheable=true)
    public static String searchDB(String objectName, String fld_API_Text, String fld_API_Val, Integer lim,String fld_API_Search,String searchText,String RecordType, string originPort, string DestPort,String SecPackType,String CusId,String fld_API_Text1){
        Id RecTypeId;
        System.debug('11.CusId :'+CusId);
        System.debug('11.objectName :'+objectName);
        System.debug('11.fld_API_Text :'+fld_API_Text);
        System.debug('11.searchText :'+searchText);
        List<sObject> sobjList; 
            /*
        if(objectName=='Transport__c' && string.isNotBlank(RecordType)){
            RecTypeId = Schema.SObjectType.Transport__c.getRecordTypeInfosByName().get(RecordType).getRecordTypeId();
        }else */ if(objectName=='Account' && string.isNotBlank(RecordType)){
            RecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get(RecordType).getRecordTypeId();
        }
        // get Recprd type
        if(objectName=='Account' && RecordType =='Billing')
        {
            RecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Billing').getRecordTypeId();
        }      
        if(objectName=='Account' && RecordType =='Shipping')
        {
            RecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Shipping').getRecordTypeId();
        }      

                
//        List<sObject> sobjList;                        
        searchText='\'%' + String.escapeSingleQuotes(searchText.trim()) + '%\'';
                
        String query = 'SELECT '+fld_API_Text+' ,'+fld_API_Val;

        if(objectName=='Account' && RecordType =='Billing')
        {
           query += ' ,'+fld_API_Text1; 
        }         
                
          /*      
        if(objectName=='Flight_Schedule__c'){   
            query += ' ,Origin_Airport__c'; 
        } */
        query += ' FROM '+objectName ;               
        Id Packagingtype;
          /*      
        if(objectName=='Secure_Packaging__c' && string.isNotBlank(SecPackType)){
            Packagingtype = Schema.SObjectType.Secure_Packaging__c.getRecordTypeInfosByName().get(SecPackType).getRecordTypeId();
        } */
        query +=' WHERE ' +fld_API_Search+' LIKE '+searchText;
        
        string whereClause = '';
                if(objectName=='AddressBook__c')
                {
                    whereClause += 'AND Customer__c =\''+CusId+'\' ';
                    //Customer__c =\''+CusId+'\' ';
                }      
                
        system.debug('lokkupresp@@ '+originPort +''+ Destport);
                /*
        if(objectName=='Secure_Packaging__c' &&string.isNotBlank(Packagingtype)){
            string status = 'Available';
            whereClause += 'AND RecordTypeId=:Packagingtype AND Status__c=:status ';
        }else */ if(objectName=='Account' && String.isNotBlank(RecTypeId)){
            whereClause += 'AND RecordTypeId =:RecTypeId ';
        } /*else if(objectName=='Transport__c' && String.isNotBlank(RecTypeId)){
            whereClause += 'AND RecordTypeId =:RecTypeId ';
            if(RecordType =='BVC Vehicle'){
                whereClause += ' AND Is_Inactive__c =false ';
            }
        }else if(objectName=='Flight_Schedule__c' && string.isNotBlank(originPort)){
            whereClause += 'AND origin__c =:originPort ';
            if(string.isNotBlank(DestPort))
                whereClause += ' AND destination__c =:DestPort';    
        }   
        
        else if(objectName=='Linehaul__c' && string.isNotBlank(originPort) && string.isNotBlank(Destport)){ 
            whereClause += 'origin__c =: originport and destination__c =: destport ';
        } */
        if(whereClause.left(3)=='AND')
            whereClause = whereClause.substringAfter('AND');
        query += ' AND '+whereClause;                          
        query=  query.removeEnd('AND ');
        query += ' LIMIT '+lim;
        System.debug('query ===> '+query);
        try{
            sobjList = Database.query(query);
        }
        catch(exception e){
            throw new AuraHandledException('Error: '+e.getMessage());
        }
                
                
            
        List<ResultWrapper> lstRet = new List<ResultWrapper>();
        for(SObject s : sobjList){
            ResultWrapper obj = new ResultWrapper();
            obj.objName = objectName;
            obj.text = String.valueOf(s.get(fld_API_Text)); 
            obj.val = String.valueOf(s.get(fld_API_Val));
            if(objectName=='Account' && RecordType =='Billing'){
                 if(fld_API_Text1!=null){obj.text1 = String.valueOf(s.get(fld_API_Text1));}             
            }
            // if(fld_API_Text1!=null){obj.text1 = String.valueOf(s.get(fld_API_Text1));}            
            System.debug('Obj Val :'+obj.text);
            lstRet.add(obj);
        } 
        system.debug('lnokkupresp@@ '+JSON.serialize(lstRet));
        return JSON.serialize(lstRet) ;
    }
    
    public class ResultWrapper{
        public String objName {get;set;}
        public String text{get;set;}
        public String val{get;set;}
        public String text1{get;set;}
        
    }
}