force-app/main/default/objects/Account/recordTypes/Billing.recordType-meta.xml
<RecordType>
    <fullName>Billing</fullName>
    <active>true</active>
    <description>Record Type for Domestic Customers.</description>
    <label>Billing</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Shipping.recordType-meta.xml
<RecordType>
    <fullName>Shipping</fullName>
    <active>true</active>
    <description>Record Type for Shipping Customers.</description>
    <label>Shipping</label>
</RecordType>

force-app/main/default/objects/Active_Pincode__c/Active_Pincode__c.object-meta.xml
<CustomObject>
    <label>Active Pincode</label>
    <nameField>
        <label>Pincode</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Active Pincodes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Active_Pincode__c/fields/Hub__c.field-meta.xml
<CustomField>
    <fullName>Hub__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hub</label>
    <referenceTo>Hub__c</referenceTo>
    <relationshipLabel>Active Pincodes</relationshipLabel>
    <relationshipName>Active_Pincodes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AddressBook__c/AddressBook__c.object-meta.xml
<CustomObject>
    <description>Primarily stores multiple shipping and billing addresses.</description>
    <label>Address Book</label>
    <nameField>
        <label>Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AddressBook__c/fields/Active_Pincode__c.field-meta.xml
<CustomField>
    <fullName>Active_Pincode__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Active Pincode</label>
    <referenceTo>Active_Pincode__c</referenceTo>
    <relationshipLabel>Addresses (Active Pincode)</relationshipLabel>
    <relationshipName>Addresses1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AddressBook__c/recordTypes/Billing.recordType-meta.xml
<RecordType>
    <fullName>Billing</fullName>
    <active>true</active>
    <label>Billing</label>
</RecordType>

force-app/main/default/objects/AddressBook__c/recordTypes/Shipping.recordType-meta.xml
<RecordType>
    <fullName>Shipping</fullName>
    <active>true</active>
    <label>Shipping</label>
</RecordType>

force-app/main/default/objects/Hub__c/Hub__c.object-meta.xml
<CustomObject>
    <label>Hub</label>
    <nameField>
        <label>Hub Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hubs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Origin_Destination__c/Origin_Destination__c.object-meta.xml
<CustomObject>
    <label>Origin Destination</label>
    <nameField>
        <label>Origin Destination Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Origin Destination</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Origin_Destination__c/fields/DestinationCity__c.field-meta.xml
<CustomField>
    <fullName>DestinationCity__c</fullName>
    <label>Destination City</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Cities</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Origin_Destination__c/fields/Mode_Of_Service__c.field-meta.xml
<CustomField>
    <fullName>Mode_Of_Service__c</fullName>
    <label>Mode Of Service</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Within City</fullName>
                <default>true</default>
                <label>Within City</label>
            </value>
            <value>
                <fullName>City-to-City</fullName>
            </value>
            <value>
                <fullName>Express (City-to-City)</fullName>
            </value>
            <value>
                <fullName>Surface (City-to-City)</fullName>
            </value>
            <value>
                <fullName>Door-to-Airport</fullName>
            </value>
            <value>
                <fullName>Vaulting</fullName>
            </value>
            <value>
                <fullName>Special Service</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Origin_Destination__c/fields/OriginCity__c.field-meta.xml
<CustomField>
    <fullName>OriginCity__c</fullName>
    <label>Origin City</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Cities</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Shipment__c/Shipment__c.object-meta.xml
<CustomObject>
    <description>Shipment object stores shipments requested against a pickup.</description>
    <label>Shipment</label>
    <nameField>
        <displayFormat>ST-{0000000}</displayFormat>
        <label>Shipment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipment__c/fields/AddressBook__c.field-meta.xml
<CustomField>
    <fullName>AddressBook__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Address</label>
    <referenceTo>AddressBook__c</referenceTo>
    <relationshipLabel>Shipments</relationshipLabel>
    <relationshipName>Shipments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Customer_Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Customer_Product_Category__c</fullName>
    <label>BVC Service</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ValSHIP</fullName>
            </value>
            <value>
                <fullName>GoldSHIP</fullName>
            </value>
            <value>
                <fullName>SilverSHIP</fullName>
            </value>
            <value>
                <fullName>LuxeSHIP</fullName>
            </value>
            <value>
                <fullName>GenSHIP</fullName>
            </value>
            <value>
                <fullName>BATH</fullName>
            </value>
            <value>
                <fullName>eSHIP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TMS_ProductCodeHandler_Test.cls
@isTest
public class TMS_ProductCodeHandler_Test {
    public static testmethod void productNameTest(){
        Account BillingAcc = BVCL_TestDataFactory.createCustomer('BVCLBill Customer','Billing',true);
        Account ShipperAcc = BVCL_TestDataFactory.createCustomer('BVCLShipp Customer','Shipping',true);
        Hub__c DelhiHub = BVCL_TestDataFactory.CreateHub('Delhi', true, 'DELHI');
        Active_Pincode__c DelhiPin = BVCL_TestDataFactory.CreatePincode('110025', DelhiHub.id, 'Delhi', 'South', true);
        AddressBook__c ShipperAddress = BVCL_TestDataFactory.CreateAddress('Shipping',ShipperAcc.id,'Line 1',DelhiPin.id,'Delhi',true);
        
        Shipment__c Ship1 = BVCL_TestDataFactory.CreateShipment(BillingAcc.id, ShipperAcc.id, ShipperAddress.id, ShipperAcc.id, ShipperAddress.id, false);
        ship1.Customer_Product_Category__c = 'ValSHIP';
        insert Ship1; 
        test.startTest();
        AddressBook__c ShipperAddress2 = BVCL_TestDataFactory.CreateAddress('Shipping',ShipperAcc.id,'Line 1',DelhiPin.id,'Gurgaon',true);
        
        Origin_Destination__c od =new Origin_Destination__c(name='Delhi-Gurgaon',OriginCity__c='Delhi',DestinationCity__c='Gurgaon',Mode_Of_Service__c='Door-to-Airport');
        insert od;
        
        Shipment__c Ship2 = BVCL_TestDataFactory.CreateShipment(BillingAcc.id, ShipperAcc.id, ShipperAddress.id, ShipperAcc.id, ShipperAddress2.id, false);
        ship2.Customer_Product_Category__c = 'ValSHIP';
        insert Ship2;
        test.stopTest();
    }
}