force-app/main/default/objects/Account/recordTypes/Billing.recordType-meta.xml
<RecordType>
    <fullName>Billing</fullName>
    <active>true</active>
    <description>Record Type for Domestic Customers.</description>
    <label>Billing</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Shipping.recordType-meta.xml
<RecordType>
    <fullName>Shipping</fullName>
    <active>true</active>
    <description>Record Type for Shipping Customers.</description>
    <label>Shipping</label>
</RecordType>

force-app/main/default/objects/Active_Pincode__c/Active_Pincode__c.object-meta.xml
<CustomObject>
    <label>Active Pincode</label>
    <nameField>
        <label>Pincode</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Active Pincodes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Active_Pincode__c/fields/Hub__c.field-meta.xml
<CustomField>
    <fullName>Hub__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hub</label>
    <referenceTo>Hub__c</referenceTo>
    <relationshipLabel>Active Pincodes</relationshipLabel>
    <relationshipName>Active_Pincodes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AddressBook__c/AddressBook__c.object-meta.xml
<CustomObject>
    <description>Primarily stores multiple shipping and billing addresses.</description>
    <label>Address Book</label>
    <nameField>
        <label>Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AddressBook__c/fields/Active_Pincode__c.field-meta.xml
<CustomField>
    <fullName>Active_Pincode__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Active Pincode</label>
    <referenceTo>Active_Pincode__c</referenceTo>
    <relationshipLabel>Addresses (Active Pincode)</relationshipLabel>
    <relationshipName>Addresses1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AddressBook__c/fields/Pickup_Route_Number__c.field-meta.xml
<CustomField>
    <fullName>Pickup_Route_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pickup Route Number</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Pickup_Delivery_Route__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Pickup</value>
        </filterItems>
        <filterItems>
            <field>Pickup_Delivery_Route__c.Is_In_Active__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Pickup_Delivery_Route__c</referenceTo>
    <relationshipLabel>Addresses (Pickup Route Number)</relationshipLabel>
    <relationshipName>PickupRouteNumber</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AddressBook__c/recordTypes/Billing.recordType-meta.xml
<RecordType>
    <fullName>Billing</fullName>
    <active>true</active>
    <label>Billing</label>
</RecordType>

force-app/main/default/objects/AddressBook__c/recordTypes/Shipping.recordType-meta.xml
<RecordType>
    <fullName>Shipping</fullName>
    <active>true</active>
    <label>Shipping</label>
</RecordType>

force-app/main/default/objects/Hub__c/Hub__c.object-meta.xml
<CustomObject>
    <label>Hub</label>
    <nameField>
        <label>Hub Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hubs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pickup__c/Pickup__c.object-meta.xml
<CustomObject>
    <description>Pickup table stores pickup requests data raised by customers.</description>
    <label>Pickup</label>
    <nameField>
        <displayFormat>PKUP-{000000}</displayFormat>
        <label>Pickup Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pickups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Pickup__c/fields/BVC_Origin_Hub__c.field-meta.xml
<CustomField>
    <fullName>BVC_Origin_Hub__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BVC Origin Hub</label>
    <referenceTo>Hub__c</referenceTo>
    <relationshipLabel>Pickups</relationshipLabel>
    <relationshipName>Pickups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pickup__c/fields/Pickup_Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>Pickup_Assigned_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pickup Assigned To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Pickups3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pickup__c/fields/Pickup_Route_Number__c.field-meta.xml
<CustomField>
    <fullName>Pickup_Route_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pickup Route Number</label>
    <referenceTo>Pickup_Delivery_Route__c</referenceTo>
    <relationshipLabel>Pickups</relationshipLabel>
    <relationshipName>Pickups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pickup_Delivery_Route__c/Pickup_Delivery_Route__c.object-meta.xml
<CustomObject>
    <label>Pickup &amp; Delivery Route</label>
    <nameField>
        <label>Route Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pickup &amp; Delivery Routes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Pickup_Delivery_Route__c/fields/Hub__c.field-meta.xml
<CustomField>
    <fullName>Hub__c</fullName>
    <label>Hub</label>
    <referenceTo>Hub__c</referenceTo>
    <relationshipLabel>Pickup &amp; Delivery Routes</relationshipLabel>
    <relationshipName>Pickup_Delivery_Routes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Pickup_Delivery_Route__c/fields/Pickup_Route_Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>Pickup_Route_Assigned_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pickup Route Assigned To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Pickup_Delivery_Routes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TMS_PickupHandlerTest.cls
@isTest
public class TMS_PickupHandlerTest {
    @isTest public static void TestupdatePickUp(){

        Profile p = [SELECT Id FROM Profile WHERE Name='Operations Field Executive'];
        User u = new User(Alias = 'standt', Email='standarduser@testorg.com',
                          EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
                          LocaleSidKey='en_US', ProfileId = p.Id,
                          TimeZoneSidKey='America/Los_Angeles',
                          UserName='testuser@bvcl.com');
        insert u;
        Hub__c DelhiHub = BVCL_TestDataFactory.CreateHub('Delhi', true, 'DELHI');
        Pickup_Delivery_Route__c pd= new Pickup_Delivery_Route__c(Name='TestPickup',Pickup_Route_Assigned_To__c=u.Id
                                                                  ,Hub__c=DelhiHub.Id);
        insert pd; 
        Account BillingAcc = BVCL_TestDataFactory.createCustomer('BVCLBill Customer','Billing',true);
        Account ShipperAcc = BVCL_TestDataFactory.createCustomer('BVCLShipp Customer','Shipping',true);
        Active_Pincode__c DelhiPin = BVCL_TestDataFactory.CreatePincode('110025', DelhiHub.id, 'Delhi', 'South', true);
        AddressBook__c ShipperAddress = BVCL_TestDataFactory.CreateAddress('Shipping',ShipperAcc.id,'Line 1',DelhiPin.id,'Cityyy',true);
        //ShipperAddress.Pickup_Route_Number__c=pd.Id;
        update ShipperAddress; 
        Pickup__c pick = BVCL_TestDataFactory.CreatePickup(BillingAcc.id, ShipperAcc.id, ShipperAddress.id, false);
        pick.BVC_Origin_Hub__c = DelhiHub.id;
        pick.Pickup_Assigned_To__c = UserInfo.getUserId();
        insert pick;
        pick.Pickup_Assigned_To__c = u.id;
        update pick;  
      
     //  TMS_PickupHandler.getPickupRouteNumber(pd.Id);
     //  TMS_PickupHandler.getPickupRouteAssignedTo(pick.Pickup_Assigned_To__c);
           
    }
 
}