force-app/main/default/objects/Account/fields/Active_Contract__c.field-meta.xml
<CustomField>
    <fullName>Active_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Active Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Customers</relationshipLabel>
    <relationshipName>Customers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/PAN_Number_of_Entity__c.field-meta.xml
<CustomField>
    <fullName>PAN_Number_of_Entity__c</fullName>
    <label>PAN Number of Entity</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Customer_Email__c.field-meta.xml
<CustomField>
    <fullName>Primary_Customer_Email__c</fullName>
    <label>Primary Customer Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Consignee.recordType-meta.xml
<RecordType>
    <fullName>Consignee</fullName>
    <active>false</active>
    <description>Record Type for Consignee</description>
    <label>Consignee</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Shipping.recordType-meta.xml
<RecordType>
    <fullName>Shipping</fullName>
    <active>true</active>
    <description>Record Type for Shipping Customers.</description>
    <label>Shipping</label>
</RecordType>

force-app/main/default/objects/Contract/fields/Liability_Charges__c.field-meta.xml
<CustomField>
    <fullName>Liability_Charges__c</fullName>
    <label>Liability Charges</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Offline_Charges__c.field-meta.xml
<CustomField>
    <fullName>Offline_Charges__c</fullName>
    <label>Offline Charges</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Shipment_Date__c.field-meta.xml
<CustomField>
    <fullName>Shipment_Date__c</fullName>
    <label>Shipment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Shipment__c/Shipment__c.object-meta.xml
<CustomObject>
    <description>Shipment object stores shipments requested against a pickup.</description>
    <label>Shipment</label>
    <nameField>
        <displayFormat>ST-{0000000}</displayFormat>
        <label>Shipment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipment__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Shipments</relationshipLabel>
    <relationshipName>Shipments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Consignee_Name_TMS__c.field-meta.xml
<CustomField>
    <fullName>Consignee_Name_TMS__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Consignee Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Shipping</value>
        </filterItems>
        <filterItems>
            <field>Account.Customer_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Shipments (Consignee Name)</relationshipLabel>
    <relationshipName>Shipments4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Destination_Type__c.field-meta.xml
<CustomField>
    <fullName>Destination_Type__c</fullName>
    <label>Destination Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Online</fullName>
            </value>
            <value>
                <fullName>Offline</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Freight_Charges__c.field-meta.xml
<CustomField>
    <fullName>Freight_Charges__c</fullName>
    <label>Freight Charges</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Gross_weight_in_Gram__c.field-meta.xml
<CustomField>
    <fullName>Gross_weight_in_Gram__c</fullName>
    <formula>CASE( TEXT(Gross_Weight_UOM_TMS__c), &apos;KG&apos;, Gross_Weight__c * 1000,
				&apos;Carat&apos;, Gross_Weight__c * 0.20, Gross_Weight__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Gross weight in Gram</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Net_weight_in_Gram__c.field-meta.xml
<CustomField>
    <fullName>Net_weight_in_Gram__c</fullName>
    <formula>CASE( TEXT(Net_Weight_UOM_TMS__c), &apos;KG&apos;, Net_Weight__c * 1000,
				&apos;Carat&apos;, Net_Weight__c * 0.20, Net_Weight__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Net weight in Gram</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Offline_Charges__c.field-meta.xml
<CustomField>
    <fullName>Offline_Charges__c</fullName>
    <label>Offline Charges</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Product_Code__c.field-meta.xml
<CustomField>
    <fullName>Product_Code__c</fullName>
    <label>BVC Product Code</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Product_Description__c.field-meta.xml
<CustomField>
    <fullName>Product_Description__c</fullName>
    <label>Product Description</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Customer_Product_Category__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Machinery</fullName>
            </value>
            <value>
                <fullName>Packing Material</fullName>
            </value>
            <value>
                <fullName>Coloured &amp; Gem Stones</fullName>
            </value>
            <value>
                <fullName>Cut &amp; Polished Diamonds</fullName>
            </value>
            <value>
                <fullName>Diamond Jewellery</fullName>
                <label>DIAMOND JEWELLERY</label>
            </value>
            <value>
                <fullName>Dore Bar</fullName>
            </value>
            <value>
                <fullName>Gold Bar</fullName>
                <label>GOLD BAR</label>
            </value>
            <value>
                <fullName>Gold Coin</fullName>
            </value>
            <value>
                <fullName>Gold Jewellery</fullName>
                <label>GOLD JEWELLERY</label>
            </value>
            <value>
                <fullName>Platinum Jewellery</fullName>
            </value>
            <value>
                <fullName>Diamond Powder</fullName>
            </value>
            <value>
                <fullName>Imitation Jewellery</fullName>
            </value>
            <value>
                <fullName>Silver Bar</fullName>
            </value>
            <value>
                <fullName>Silver Coin</fullName>
            </value>
            <value>
                <fullName>Silver Jewellery</fullName>
                <label>SILVER JEWELLERY</label>
            </value>
            <value>
                <fullName>Rough Diamond</fullName>
                <label>ROUGH DIAMOND</label>
            </value>
            <value>
                <fullName>Silver Article</fullName>
                <label>SILVER ARTICLE</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Shipment_Date__c.field-meta.xml
<CustomField>
    <fullName>Shipment_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <description>This is the Shipment date for Domestic</description>
    <label>Shipment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Shipment_Type__c.field-meta.xml
<CustomField>
    <fullName>Shipment_Type__c</fullName>
    <label>Shipment Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Collect</fullName>
            </value>
            <value>
                <fullName>Prepaid</fullName>
            </value>
            <value>
                <fullName>All</fullName>
            </value>
            <value>
                <fullName>Intercity</fullName>
            </value>
            <value>
                <fullName>Forward</fullName>
            </value>
            <value>
                <fullName>RTO</fullName>
            </value>
            <value>
                <fullName>Reverse</fullName>
            </value>
            <value>
                <fullName>Intracity</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Shipment_Value__c.field-meta.xml
<CustomField>
    <fullName>Shipment_Value__c</fullName>
    <label>Shipment Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Shipper_Name_TMS__c.field-meta.xml
<CustomField>
    <fullName>Shipper_Name_TMS__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shipper Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Shipping, Shipping</value>
        </filterItems>
        <filterItems>
            <field>Account.Customer_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Shipments (Shipper Name)</relationshipLabel>
    <relationshipName>Shipments3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Shipping_Note_Number__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Note_Number__c</fullName>
    <description>This is the Domestic Shipping Note number</description>
    <label>Shipping Note Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Total_Charge__c.field-meta.xml
<CustomField>
    <fullName>Total_Charge__c</fullName>
    <label>Total Charge</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Weight_Charges__c.field-meta.xml
<CustomField>
    <fullName>Weight_Charges__c</fullName>
    <label>Weight Charges</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ST_ACR_Consumption__c/ST_ACR_Consumption__c.object-meta.xml
<CustomObject>
    <label>ACR Consumption</label>
    <nameField>
        <displayFormat>ACRC-{00000000}</displayFormat>
        <label>ACR Consumption  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ACR Consumption</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ST_ACR_Consumption__c/fields/BVC_Valuation_Charges__c.field-meta.xml
<CustomField>
    <fullName>BVC_Valuation_Charges__c</fullName>
    <label>BVC Valuation Charges</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ST_ACR_Consumption__c/fields/Destination_City__c.field-meta.xml
<CustomField>
    <fullName>Destination_City__c</fullName>
    <formula>Shipment__r.Destination_Address_Name__r.CITY__c</formula>
    <label>Destination City</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ST_ACR_Consumption__c/fields/Freight_Charges__c.field-meta.xml
<CustomField>
    <fullName>Freight_Charges__c</fullName>
    <label>Freight Charges</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ST_ACR_Consumption__c/fields/Liability_charges__c.field-meta.xml
<CustomField>
    <fullName>Liability_charges__c</fullName>
    <label>Liability charges</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ST_ACR_Consumption__c/fields/Offline_Charges__c.field-meta.xml
<CustomField>
    <fullName>Offline_Charges__c</fullName>
    <label>Offline Charges</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ST_ACR_Consumption__c/fields/Origin_City__c.field-meta.xml
<CustomField>
    <fullName>Origin_City__c</fullName>
    <formula>Shipment__r.Origin_Address_Name__r.CITY__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Origin City</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ST_ACR_Consumption__c/fields/Origin_Type__c.field-meta.xml
<CustomField>
    <fullName>Origin_Type__c</fullName>
    <label>Origin Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Online</fullName>
            </value>
            <value>
                <fullName>Offline</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ST_ACR_Consumption__c/fields/Product_Description__c.field-meta.xml
<CustomField>
    <fullName>Product_Description__c</fullName>
    <label>Product Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ST_ACR_Consumption__c/fields/Shipment_Date__c.field-meta.xml
<CustomField>
    <fullName>Shipment_Date__c</fullName>
    <label>Shipment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ST_ACR_Consumption__c/fields/Shipment_Type__c.field-meta.xml
<CustomField>
    <fullName>Shipment_Type__c</fullName>
    <label>Shipment Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Collect</fullName>
            </value>
            <value>
                <fullName>Prepaid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ST_ACR_Consumption__c/fields/Total_Charge__c.field-meta.xml
<CustomField>
    <fullName>Total_Charge__c</fullName>
    <label>Total Charge</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ST_ACR_Consumption__c/fields/Weight_Charges__c.field-meta.xml
<CustomField>
    <fullName>Weight_Charges__c</fullName>
    <label>Weight Charges</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/ACRReportBatch.cls
public class ACRReportBatch implements Database.Batchable<sObject>{
	public final String Query;
    public ACRReportBatch(){
          query='select id,name,Primary_Customer_Email__c, Active_Contract__c,PAN_Number_of_Entity__c,Active_Contract__r.ContractNumber,(select id,Shipping_Note_Number__c,Shipment_Date__c,Shipment_Value__c,Net_weight_in_Gram__c,Gross_weight_in_Gram__c,Product_Code__c,Product_Description__c, Shipper_Name_TMS__c,Consignee_Name_TMS__c ,Shipment_Type__c from Shipments__r),(SELECT id, Freight_Charges__c,Weight_Charges__c,Offline_Charges__c,Liability_charges__c,BVC_Valuation_Charges__c,Total_Charge__c,Origin_City__c,Origin_Type__c,Destination_City__c,Destination_type__c FROM ACR_Consumption__r) from Account where Customer_Category_Static__c =\'ACR\' and Active_Contract__c !=null';
              }
    public Database.QueryLocator start(Database.BatchableContext BC){
      return Database.getQueryLocator(query);
   	}
    public void execute(Database.BatchableContext BC, List<Account> scope){
        list<ContentDocumentLink> conLinkList= new list<ContentDocumentLink>();
        list<ContentVersion> ContVerList = new list<ContentVersion>();
        
        for(Account a:scope){
       	string header = 'customer name, PAN Number,Contract Number, contract amount, contract number,Shipping Note Number, Shipment Date, Shipment Value, Net Weight in Gram,Gross Weight in Gram, Freight Charges, Weight Charges, Offline Charges, Liability Charges, BVC Valuation Charges, Total Charges, BVC Product Code,Product Description,Shipper Account,Consignee Account, Origin City, Origin Type, Destination City, Dectination Type, Shipment Type  \n';
        string finalstr = header ;
        string recordString= null;
       // recordString= '"'+a.name+'","'+a.PAN_Number_of_Entity__c+'","'+a.Active_Contract__r.ContractNumber+'" \n';
        for(shipment__c ship:a.shipments__r){
              for(ST_ACR_Consumption__c acrcon :a.ACR_Consumption__r){
                 recordString = '"'+a.name+'","'+a.PAN_Number_of_Entity__c+'","'+a.Active_Contract__r.ContractNumber+'","'+ship.Shipping_Note_Number__c+'","'+ship.Shipping_Note_Number__c+'","'+ship.Shipment_Date__c+'","'+ship.Shipment_Value__c+'","'+ship.Net_weight_in_Gram__c+'","'+ship.Gross_weight_in_Gram__c+'","'+acrcon.Freight_Charges__c+'","'+acrcon.Weight_Charges__c+'","'+acrcon.Offline_Charges__c+'","'+acrcon.Liability_charges__c+'","'+acrcon.BVC_Valuation_Charges__c+'","'+acrcon.Total_Charge__c+'","'+ship.Product_Code__c+'","'+ship.Product_Description__c+'","'+ship.Shipper_Name_TMS__c+'","'+ship.Consignee_Name_TMS__c+'","'+acrcon.Origin_City__c+'","'+acrcon.Origin_Type__c +'","'+acrcon.Destination_City__c +'","'+acrcon.Destination_type__c+'","'+ship.Shipment_Type__c+'" \n';   
              system.debug('RecordString++++++'+recordString); 
				}
               }
           
         finalstr = finalstr +recordString;
        
     	ContentVersion conVer = new ContentVersion();
        conVer.ContentLocation = 'S'; // to use S specify this document is in Salesforce, to use E for external files
        conVer.PathOnClient = 'Consumption Details.csv'; // The files name, extension is very important here which will help the file in preview.
        conVer.Title = 'Consumption Details.csv'; // Display name of the files
        Blob textData = Blob.valueOf(finalstr);
        conVer.Customer__c= a.Id;   
        conVer.VersionData = textData;
        system.debug('before insertion++++++'+conVer);
        ContVerList.add(conVer);    //Insert ContentVersion
     
     	}
    try{
        insert ContVerList;
         system.debug('after insertion++++++'+ContVerList);
    }
     catch(exception ex){
         system.debug(ex.getMessage());
     }
        /*for(ContentVersion c:ContVerList){
            ContentDocumentLink conDocLink = New ContentDocumentLink();
            conDocLink.LinkedEntityId = c.Customer__c; // Specify RECORD ID here i.e Any Object ID (Standard Object/Custom Object)
            conDocLink.ContentDocumentId = c.ContentDocumentId;  //ContentDocumentId Id from ContentVersion
            conDocLink.shareType = 'V';
            conLinkList.add(conDocLink);
        }
        try{
        insert conLinkList;
         system.debug('after insertion++++++'+conLinkList);
    }
     catch(exception ex){
         system.debug(ex.getMessage());
     }*/
          
    }
    public void finish(Database.BatchableContext BC){
       
   }
}