force-app/main/default/objects/Account/fields/Billing_Address__c.field-meta.xml
<CustomField>
    <fullName>Billing_Address__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Billing Address</label>
    <referenceTo>AddressBook__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Is_Finance_Contact_Present__c.field-meta.xml
<CustomField>
    <fullName>Is_Finance_Contact_Present__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Finance Contact Present</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Address__c.field-meta.xml
<CustomField>
    <fullName>Primary_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Address</label>
    <referenceTo>AddressBook__c</referenceTo>
    <relationshipLabel>Customers</relationshipLabel>
    <relationshipName>Customers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Active_Pincode__c/Active_Pincode__c.object-meta.xml
<CustomObject>
    <label>Active Pincode</label>
    <nameField>
        <label>Pincode</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Active Pincodes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Active_Pincode__c/fields/Hub__c.field-meta.xml
<CustomField>
    <fullName>Hub__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hub</label>
    <referenceTo>Hub__c</referenceTo>
    <relationshipLabel>Active Pincodes</relationshipLabel>
    <relationshipName>Active_Pincodes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AddressBook__c/AddressBook__c.object-meta.xml
<CustomObject>
    <description>Primarily stores multiple shipping and billing addresses.</description>
    <label>Address Book</label>
    <nameField>
        <label>Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AddressBook__c/fields/Active_Pincode__c.field-meta.xml
<CustomField>
    <fullName>Active_Pincode__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Active Pincode</label>
    <referenceTo>Active_Pincode__c</referenceTo>
    <relationshipLabel>Addresses (Active Pincode)</relationshipLabel>
    <relationshipName>Addresses1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/AddressBook__c.field-meta.xml
<CustomField>
    <fullName>AddressBook__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AddressBook</label>
    <referenceTo>AddressBook__c</referenceTo>
    <relationshipLabel>People</relationshipLabel>
    <relationshipName>People</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Entity__c/Entity__c.object-meta.xml
<CustomObject>
    <description>BVC ENTITY MASTER</description>
    <label>Entity</label>
    <nameField>
        <label>Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Hub__c/Hub__c.object-meta.xml
<CustomObject>
    <label>Hub</label>
    <nameField>
        <label>Hub Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hubs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Hub__c/fields/ST_BVC_Billing_Entity__c.field-meta.xml
<CustomField>
    <fullName>ST_BVC_Billing_Entity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BVC Billing Entity</label>
    <referenceTo>blng__LegalEntity__c</referenceTo>
    <relationshipLabel>BVCHubs</relationshipLabel>
    <relationshipName>BVCHubs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Business_Type__c.field-meta.xml
<CustomField>
    <fullName>Business_Type__c</fullName>
    <label>Business Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ACR</fullName>
            </value>
            <value>
                <fullName>Non ACR</fullName>
            </value>
            <value>
                <fullName>Exhibition</fullName>
                <isActive>false</isActive>
                <label>Exhibition</label>
            </value>
            <value>
                <fullName>Shipment</fullName>
                <isActive>false</isActive>
                <label>Shipment</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/blng__BillingRule__c.field-meta.xml
<CustomField>
    <fullName>blng__BillingRule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing Rule</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>blng__BillingRule__c.blng__Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>blng__BillingRule__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/blng__RevenueRecognitionRule__c.field-meta.xml
<CustomField>
    <fullName>blng__RevenueRecognitionRule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Revenue Recognition Rule</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>blng__RevenueRecognitionRule__c.blng__Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>blng__RevenueRecognitionRule__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>RevenueRecognitionRuleProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/blng__TaxRule__c.field-meta.xml
<CustomField>
    <fullName>blng__TaxRule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tax Rule</label>
    <referenceTo>blng__TaxRule__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>TaxRulesProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ST_ACR_Standard_Price__c/ST_ACR_Standard_Price__c.object-meta.xml
<CustomObject>
    <label>ACR Standard Price</label>
    <nameField>
        <displayFormat>ACR-{0000}</displayFormat>
        <label>ACR Standard Price Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ACR Standard Price</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ST_ACR_Standard_Price__c/fields/ST_Product__c.field-meta.xml
<CustomField>
    <fullName>ST_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>ACR Standard Price</relationshipLabel>
    <relationshipName>ACR_Standard_Price</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ST_NonACR_Standard_Price__c/ST_NonACR_Standard_Price__c.object-meta.xml
<CustomObject>
    <label>NonACR Standard Price</label>
    <nameField>
        <label>Non  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NonACR Standard Prices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ST_NonACR_Standard_Price__c/fields/ST_Product__c.field-meta.xml
<CustomField>
    <fullName>ST_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>NonACR Standard Prices</relationshipLabel>
    <relationshipName>NonACR_Standard_Prices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CongaComposerCtrlTest.cls
@isTest
public class CongaComposerCtrlTest {
	@testSetup
    static void testSetup(){
        User userToCreate = [Select id from user where profile.name='System Administrator' Limit 1];
        Entity__c ent = TestUtility.createBVCEntity();
        insert ent;
        
        Active_Pincode__c pin = TestUtility.createPinCode();
        insert pin;
        
        blng__LegalEntity__c legEntity = TestUtility.createLegalEntity(ent);
        insert legEntity;
        
        List<Hub__c> branches = new  List<Hub__c>();
        Hub__c bvcBranch = TestUtility.createBVCBranch(legEntity, pin);
        branches.add(bvcBranch);
        insert branches;
        system.debug('Branches::Test Setup::'+branches);
        List<Account> accList = new List<Account>();
        Account nonAcrNonContractedAccount = TestUtility.createNonACRnonContractedAccount();
        
        
        accList.add(nonAcrNonContractedAccount);
        insert accList;
        
        Contact Con = TestUtility.createContact(accList[0]);
        con.FirstName = 'Lionel';
        con.Title = 'The Best';
        insert Con;
        
        Opportunity opp = TestUtility.createOpportunity(accList,con,ent)[0];
        List<Opportunity> oppList = new List<Opportunity>{opp};
        insert oppList;
        
        
        OpportunityContactRole opptyRole  = TestUtility.createOpportunityContactRole(opp,con,'Decision Maker');
        insert opptyRole;
            
        blng__BillingRule__c bRule = TestUtility.createBillingRule();
        insert bRule;        
        
        blng__RevenueRecognitionRule__c revRule = TestUtility.createRevenueRule();
        insert revRule;
        
        blng__TaxRule__c taxRule = TestUtility.createTaxRule();
        insert taxRule;
        
        List<Product2> prodList = new List<Product2>();
        Product2 prod = TestUtility.createACRProduct(bRule, revRule, taxRule);
        prodList.add(prod);
        
        
        Product2 optionProduct = TestUtility.createProduct(bRule, revRule, taxRule);
        prodList.add(optionProduct);
        insert prodList;
        
        SBQQ__ProductOption__c prodOption = TestUtility.createProductOption(prodList[0], prodList[1]);
        insert prodOption;
        
        Id stdPriceBookId = test.getStandardPricebookId();
        
        Pricebook2 pb = TestUtility.createPriceBook();
        insert pb;
        
        PricebookEntry standardACRPBE = new PricebookEntry(Pricebook2Id = stdPriceBookId, Product2Id = prodList[0].Id, UnitPrice = 1000, IsActive = true);
        insert standardACRPBE;
        
        PricebookEntry standardPBE = new PricebookEntry(Pricebook2Id = stdPriceBookId, Product2Id = prodList[1].Id, UnitPrice = 1000, IsActive = true);
        insert standardPBE;
        
        
        List<PricebookEntry> customACRPrices = TestUtility.createACRPricebookEntry(pb.Id,prodList);
        insert customACRPrices;
        
        
        List<AddressBook__c> blngAddress = TestUtility.createAddressBook(accList);
        insert blngAddress;
        
        accList[0].Billing_Address__c = blngAddress[0].Id;
        accList[0].Is_Finance_Contact_Present__c = true;
        accList[0].Primary_Address__c = blngAddress[0].Id;
        update accList[0];
        
        List<ST_ACR_Standard_Price__c> stdACRPrice = TestUtility.createACRStandardPrice(prodList);
        insert stdACRPrice;
        
        ST_NonACR_Standard_Price__c noAcrPrice = TestUtility.createNONACRStandardPrice(prodList[1]);
        insert noAcrPrice;
        
        
        
        
    }

    @isTest 
    static void acrQuoteMethod(){
        test.startTest();
        //List<SBQQ__Quote__c> quote = [SELECT Id From SBQQ__Quote__c where Business_Type__c = 'ACR' ];
        List<Opportunity> oppList = [select id,AccountId from Opportunity];
        Hub__c branch = [select id,ST_BVC_Billing_Entity__c from Hub__c Limit 1];
        Pricebook2 pbook = [select id from Pricebook2 where Name='BVC INR Price Book'];
        List<ST_ACR_Standard_Price__c> stdPriceList = [Select Id,ST_Product__c from ST_ACR_Standard_Price__c];
        List<PricebookEntry> pbEntries = [select id,Product2Id from PricebookEntry where Pricebook2Id =:pbook.Id];

        SBQQ__Quote__c quote = TestUtility.createACRQuote(pbook.Id, oppList, branch)[0];
        insert quote;
        
        List<SBQQ__QuoteLine__c> acrQuoteLines = TestUtility.createQuoteLines(quote.Id,pbEntries,stdPriceList);
        //insert acrQuoteLines;

        quote.SBQQ__Status__c = 'Approved';
        update quote;

        PageReference pageRef = Page.CongaVF;
        Test.setCurrentPage(pageRef);
        // put the lead id as a parameter
        ApexPages.currentPage().getParameters().put('Id',quote.Id);
        ApexPages.StandardController sc = new ApexPages.StandardController(quote);
        CongaComposerCtrl con = new CongaComposerCtrl(sc);
        con.congaReq();
        
        test.stopTest();
    }
    
    @isTest 
    static void nonApprovedQuoteMethod(){
        test.startTest();

        List<Opportunity> oppList = [select id,AccountId from Opportunity];
        Hub__c branch = [select id,ST_BVC_Billing_Entity__c from Hub__c Limit 1];
        Pricebook2 pbook = [select id from Pricebook2 where Name='BVC INR Price Book'];
        List<ST_ACR_Standard_Price__c> stdPriceList = [Select Id,ST_Product__c from ST_ACR_Standard_Price__c];
        List<PricebookEntry> pbEntries = [select id,Product2Id from PricebookEntry where Pricebook2Id =:pbook.Id];

        SBQQ__Quote__c quote = TestUtility.createACRQuote(pbook.Id, oppList, branch)[0];
        insert quote;
        
        List<SBQQ__QuoteLine__c> acrQuoteLines = TestUtility.createQuoteLines(quote.Id,pbEntries,stdPriceList);
        //insert acrQuoteLines;
        
        PageReference pageRef = Page.CongaVF;
        Test.setCurrentPage(pageRef);
        // put the lead id as a parameter
        ApexPages.currentPage().getParameters().put('Id',quote.Id);
        ApexPages.StandardController sc = new ApexPages.StandardController(quote);
        CongaComposerCtrl con = new CongaComposerCtrl(sc);
        con.congaReq();
        
        test.stopTest();
    }
    
    @isTest 
    static void nonContactRoleQuoteMethod(){
        test.startTest();
        List<Opportunity> oppList = [select id,AccountId from Opportunity];
        Hub__c branch = [select id,ST_BVC_Billing_Entity__c from Hub__c Limit 1];
        Pricebook2 pbook = [select id from Pricebook2 where Name='BVC INR Price Book'];
        List<ST_ACR_Standard_Price__c> stdPriceList = [Select Id,ST_Product__c from ST_ACR_Standard_Price__c];
        List<PricebookEntry> pbEntries = [select id,Product2Id from PricebookEntry where Pricebook2Id =:pbook.Id];

        SBQQ__Quote__c quote = TestUtility.createACRQuote(pbook.Id, oppList, branch)[0];
        insert quote;
        
        List<SBQQ__QuoteLine__c> acrQuoteLines = TestUtility.createQuoteLines(quote.Id,pbEntries,stdPriceList);
        //insert acrQuoteLines;

        List<OpportunityContactRole> oppRoles = [SELECT Role From OpportunityContactRole where Role = 'Decision Maker' ];
        oppRoles[0].Role = 'Authorised Signatory';
        update oppRoles;
        
        PageReference pageRef = Page.CongaVF;
        Test.setCurrentPage(pageRef);
        // put the lead id as a parameter
        ApexPages.currentPage().getParameters().put('Id',quote.Id);
        ApexPages.StandardController sc = new ApexPages.StandardController(quote);
        CongaComposerCtrl con = new CongaComposerCtrl(sc);
        con.congaReq();
        
        test.stopTest();
    }
}