force-app/main/default/objects/Account/fields/Billing_Cycle__c.field-meta.xml
<CustomField>
    <fullName>Billing_Cycle__c</fullName>
    <label>Billing Cycle</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01-31</fullName>
                <default>true</default>
                <label>01-31</label>
            </value>
            <value>
                <fullName>26-25</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Billing_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Billing_Frequency__c</fullName>
    <label>Billing Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Shipment</fullName>
                <default>true</default>
                <label>Shipment</label>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Forthnightly</fullName>
                <isActive>false</isActive>
                <label>Forthnightly</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Contract_Amount__c.field-meta.xml
<CustomField>
    <fullName>Contract_Amount__c</fullName>
    <formula>Active_Contract__r.Contract_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contract Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Contracted_ACR_Package__c.field-meta.xml
<CustomField>
    <fullName>Contracted_ACR_Package__c</fullName>
    <formula>Active_Contract__r.Contracted_ACR_Package__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contracted ACR Package</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Customer_Category__c.field-meta.xml
<CustomField>
    <fullName>Customer_Category__c</fullName>
    <label>Customer Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ACR Contracted</fullName>
            </value>
            <value>
                <fullName>Non ACR Contracted</fullName>
            </value>
            <value>
                <fullName>ACR Non Contracted</fullName>
            </value>
            <value>
                <fullName>Non Contracted</fullName>
                <default>true</default>
                <label>Non Contracted</label>
            </value>
            <value>
                <fullName>Non ACR</fullName>
                <isActive>false</isActive>
                <label>Non ACR</label>
            </value>
            <value>
                <fullName>Non ACR Non Contracted</fullName>
                <isActive>false</isActive>
                <label>Non ACR Non Contracted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/GST_Registered__c.field-meta.xml
<CustomField>
    <fullName>GST_Registered__c</fullName>
    <defaultValue>false</defaultValue>
    <label>GST Registered</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/KYC_Indicator_for_Domestic_Flag__c.field-meta.xml
<CustomField>
    <fullName>KYC_Indicator_for_Domestic_Flag__c</fullName>
    <defaultValue>false</defaultValue>
    <label>KYC Indicator for Domestic Flag</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/KYC_Status__c.field-meta.xml
<CustomField>
    <fullName>KYC_Status__c</fullName>
    <label>KYC Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>API Verified</fullName>
            </value>
            <value>
                <fullName>Verification Case Created</fullName>
            </value>
            <value>
                <fullName>Verification Failed</fullName>
            </value>
            <value>
                <fullName>Manually Verified</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Mobile__c.field-meta.xml
<CustomField>
    <fullName>Mobile__c</fullName>
    <label>Mobile</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account/fields/Name_As_Per_PAN_Manual_Input__c.field-meta.xml
<CustomField>
    <fullName>Name_As_Per_PAN_Manual_Input__c</fullName>
    <label>Name As Per PAN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Original_Contract_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Original_Contract_End_Date__c</fullName>
    <formula>Active_Contract__r.SBQQ__ExpirationDate__c</formula>
    <label>Original Contract End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/ST_Pricing_Type__c.field-meta.xml
<CustomField>
    <fullName>ST_Pricing_Type__c</fullName>
    <label>Pricing Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ST_Pricing_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Active_Pincode__c/Active_Pincode__c.object-meta.xml
<CustomObject>
    <label>Active Pincode</label>
    <nameField>
        <label>Pincode</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Active Pincodes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Active_Pincode__c/fields/Hub__c.field-meta.xml
<CustomField>
    <fullName>Hub__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hub</label>
    <referenceTo>Hub__c</referenceTo>
    <relationshipLabel>Active Pincodes</relationshipLabel>
    <relationshipName>Active_Pincodes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Business_Type__c.field-meta.xml
<CustomField>
    <fullName>Business_Type__c</fullName>
    <label>Business Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Business_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/BVC_Billing_Entity__c.field-meta.xml
<CustomField>
    <fullName>BVC_Billing_Entity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BVC Billing Entity</label>
    <referenceTo>blng__LegalEntity__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/BVC_Branch__c.field-meta.xml
<CustomField>
    <fullName>BVC_Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BVC Branch</label>
    <referenceTo>Hub__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/BVC_Entity__c.field-meta.xml
<CustomField>
    <fullName>BVC_Entity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BVC Entity</label>
    <referenceTo>Entity__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Contract_Amount__c.field-meta.xml
<CustomField>
    <fullName>Contract_Amount__c</fullName>
    <label>Contract Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Contract_Signed_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_Signed_Date__c</fullName>
    <label>Contract Signed Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Contracted_ACR_Package__c.field-meta.xml
<CustomField>
    <fullName>Contracted_ACR_Package__c</fullName>
    <label>Contracted ACR Package</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Original_Contract_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Original_Contract_End_Date__c</fullName>
    <label>Original Contract End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contract/fields/SBQQ__Order__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Entity__c/Entity__c.object-meta.xml
<CustomObject>
    <description>BVC ENTITY MASTER</description>
    <label>Entity</label>
    <nameField>
        <label>Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Hub__c/Hub__c.object-meta.xml
<CustomObject>
    <label>Hub</label>
    <nameField>
        <label>Hub Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hubs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Hub__c/fields/BVC_Entity__c.field-meta.xml
<CustomField>
    <fullName>BVC_Entity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BVC Entity</label>
    <referenceTo>Entity__c</referenceTo>
    <relationshipLabel>Hubs</relationshipLabel>
    <relationshipName>Hubs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Hub__c/fields/ST_BVC_Billing_Entity__c.field-meta.xml
<CustomField>
    <fullName>ST_BVC_Billing_Entity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BVC Billing Entity</label>
    <referenceTo>blng__LegalEntity__c</referenceTo>
    <relationshipLabel>BVCHubs</relationshipLabel>
    <relationshipName>BVCHubs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/Name_As_Per_Pan_Manual_Input__c.field-meta.xml
<CustomField>
    <fullName>Name_As_Per_Pan_Manual_Input__c</fullName>
    <label>PAN Number&apos;s Entity Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ExpireContractBatchTest.cls
@isTest
public class ExpireContractBatchTest {

    
    
    
    @testSetup
    static void activationTest(){
        User userToCreate = [Select id from user where profile.name='System Administrator' Limit 1];
        Entity__c ent = TestUtility.createBVCEntity();
        insert ent;
        
        Active_Pincode__c pin = TestUtility.createPinCode();
        insert pin;
        
        blng__LegalEntity__c legEntity = TestUtility.createLegalEntity(ent);
        insert legEntity;
        
        List<Hub__c> branches = new  List<Hub__c>();
        Hub__c bvcBranch = TestUtility.createBVCBranch(legEntity, pin);
        branches.add(bvcBranch);
        Hub__c originBranch = TestUtility.createBVCBranch(legEntity, pin);
        branches.add(originBranch);
        Hub__c destinationBranch = TestUtility.createBVCBranch(legEntity, pin);
        branches.add(destinationBranch);
        insert branches;
        Active_Pincode__c suratPin = TestUtility.createBengaluruPinCode(branches[1]);
        insert suratPin;
        Account acc = new Account();
        acc.name = 'non ACR Non Contracted Account1234321';
        /*acc.Last_Name__c = 'Last';
        acc.Mobile__c = '1234567889';*/
        acc.ST_Pricing_Type__c = 'Non ACR';
        acc.Customer_Category__c = 'Non ACR Contracted';
        acc.Billing_Frequency__c = 'Monthly';
        acc.Name_As_Per_PAN_Manual_Input__c = 'Lionesl Messi';
        acc.GST_Registered__c = true;
        acc.Billing_Cycle__c = '26-25';
        acc.KYC_Status__c = 'API Verified';
        acc.KYC_Indicator_for_Domestic_Flag__c = true;
        
        insert acc;

        Contract cont = new Contract(AccountId = acc.Id,
                                     //SBQQ__Order__c = o.Id,
                                     StartDate = System.today().addDays(-30),
                                     EndDate = System.today(),
                                     Original_Contract_End_Date__c = system.today().addDays(45),
                                     Contract_Signed_Date__c = system.today(),
                                     Business_Type__c = 'ACR',
                                     Status = 'Draft',
                                     Contracted_ACR_Package__c = 'Package 2 : 60K',
                                     Contract_Amount__c = 60000,
                                     BVC_Branch__c = branches[0].Id,
                                     BVC_Billing_Entity__c = branches[0].ST_BVC_Billing_Entity__c,
                                     BVC_Entity__c = branches[0].BVC_Entity__c);   
        
        insert cont;

        Contract con = [select Id, Status from Contract limit 1];
        con.Status = 'Activated';
        update con;
        
        Database.executeBatch(new ExpireContractBatch());
        
    }
    
    @isTest 
    static void scheduleBatchTest(){
        Test.startTest();
        String cronExpr = '0 0 0 15 12 ? 2022';
        ExpireContractBatch abs= new ExpireContractBatch();
        String jobId = System.schedule('myJobTestJobName', cronExpr, abs);
        abs.execute(null);
        Test.stopTest();
    }  
    @isTest 
    static void expireBatchTest(){
        Test.startTest();
        String cronExpr = '0 0 0 15 12 ? 2022';
        Contract con = [select Id, Status from Contract limit 1];
        con.EndDate = Date.Today().addDays(-2);
        update con;
        ExpireContractBatch abs= new ExpireContractBatch();
        String jobId = System.schedule('myJobTestJobName', cronExpr, abs);
        abs.execute(null);
        Test.stopTest();
    }   
}