force-app/main/default/objects/Account/fields/Billing_Address__c.field-meta.xml
<CustomField>
    <fullName>Billing_Address__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Billing Address</label>
    <referenceTo>AddressBook__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/GSTIN__c.field-meta.xml
<CustomField>
    <fullName>GSTIN__c</fullName>
    <label>GSTIN</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Active_Pincode__c/Active_Pincode__c.object-meta.xml
<CustomObject>
    <label>Active Pincode</label>
    <nameField>
        <label>Pincode</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Active Pincodes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Active_Pincode__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Cities</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Active_Pincode__c/fields/Hub__c.field-meta.xml
<CustomField>
    <fullName>Hub__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hub</label>
    <referenceTo>Hub__c</referenceTo>
    <relationshipLabel>Active Pincodes</relationshipLabel>
    <relationshipName>Active_Pincodes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AddressBook__c/AddressBook__c.object-meta.xml
<CustomObject>
    <description>Primarily stores multiple shipping and billing addresses.</description>
    <label>Address Book</label>
    <nameField>
        <label>Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AddressBook__c/fields/Active_Pincode__c.field-meta.xml
<CustomField>
    <fullName>Active_Pincode__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Active Pincode</label>
    <referenceTo>Active_Pincode__c</referenceTo>
    <relationshipLabel>Addresses (Active Pincode)</relationshipLabel>
    <relationshipName>Addresses1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AddressBook__c/fields/ADDRESS1__c.field-meta.xml
<CustomField>
    <fullName>ADDRESS1__c</fullName>
    <label>Address Line 1</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AddressBook__c/fields/ADDRESS2__c.field-meta.xml
<CustomField>
    <fullName>ADDRESS2__c</fullName>
    <label>Address Line 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AddressBook__c/fields/CITY__c.field-meta.xml
<CustomField>
    <fullName>CITY__c</fullName>
    <label>City</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AddressBook__c/fields/COUNTRY__c.field-meta.xml
<CustomField>
    <fullName>COUNTRY__c</fullName>
    <label>Country</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AddressBook__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Customer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Customer_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Addresses</relationshipLabel>
    <relationshipName>Addresses</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AddressBook__c/fields/Dealer_Type__c.field-meta.xml
<CustomField>
    <fullName>Dealer_Type__c</fullName>
    <label>Dealer Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unregistered</fullName>
            </value>
            <value>
                <fullName>Regular</fullName>
            </value>
            <value>
                <fullName>SEZ</fullName>
            </value>
            <value>
                <fullName>SEZ Unit</fullName>
                <isActive>false</isActive>
                <label>SEZ Unit</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AddressBook__c/fields/GST_Registered_Status__c.field-meta.xml
<CustomField>
    <fullName>GST_Registered_Status__c</fullName>
    <label>GST Registered Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>Unregistered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AddressBook__c/fields/PINCODE__c.field-meta.xml
<CustomField>
    <fullName>PINCODE__c</fullName>
    <label>Pincode</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AddressBook__c/fields/STATE__c.field-meta.xml
<CustomField>
    <fullName>STATE__c</fullName>
    <label>State</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Base_Quote_Settings__c/Base_Quote_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Base Quote Settings</label>
</CustomObject>

force-app/main/default/objects/Base_Quote_Settings__c/fields/Base_QuoteId__c.field-meta.xml
<CustomField>
    <fullName>Base_QuoteId__c</fullName>
    <label>Base QuoteId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Base_Quote_Settings__c/fields/Quote_Business_Type__c.field-meta.xml
<CustomField>
    <fullName>Quote_Business_Type__c</fullName>
    <label>Quote Business Type</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/AddressBook__c.field-meta.xml
<CustomField>
    <fullName>AddressBook__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AddressBook</label>
    <referenceTo>AddressBook__c</referenceTo>
    <relationshipLabel>People</relationshipLabel>
    <relationshipName>People</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Entity__c/Entity__c.object-meta.xml
<CustomObject>
    <description>BVC ENTITY MASTER</description>
    <label>Entity</label>
    <nameField>
        <label>Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Entity__c/fields/GSTIN__c.field-meta.xml
<CustomField>
    <fullName>GSTIN__c</fullName>
    <label>GSTIN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Hub__c/Hub__c.object-meta.xml
<CustomObject>
    <label>Hub</label>
    <nameField>
        <label>Hub Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hubs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Hub__c/fields/BVC_Entity__c.field-meta.xml
<CustomField>
    <fullName>BVC_Entity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BVC Entity</label>
    <referenceTo>Entity__c</referenceTo>
    <relationshipLabel>Hubs</relationshipLabel>
    <relationshipName>Hubs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Hub__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <externalId>true</externalId>
    <label>City</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Hub__c/fields/Hub_Address_Line_1__c.field-meta.xml
<CustomField>
    <fullName>Hub_Address_Line_1__c</fullName>
    <label>Hub Address Line 1</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Hub__c/fields/Hub_Address_Line_2__c.field-meta.xml
<CustomField>
    <fullName>Hub_Address_Line_2__c</fullName>
    <label>Hub Address Line 2</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Hub__c/fields/Hub_Pincode__c.field-meta.xml
<CustomField>
    <fullName>Hub_Pincode__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hub Pincode</label>
    <referenceTo>Active_Pincode__c</referenceTo>
    <relationshipLabel>Hubs</relationshipLabel>
    <relationshipName>Hubs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Hub__c/fields/ST_BVC_Billing_Entity__c.field-meta.xml
<CustomField>
    <fullName>ST_BVC_Billing_Entity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BVC Billing Entity</label>
    <referenceTo>blng__LegalEntity__c</referenceTo>
    <relationshipLabel>BVCHubs</relationshipLabel>
    <relationshipName>BVCHubs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Business_Type__c.field-meta.xml
<CustomField>
    <fullName>Business_Type__c</fullName>
    <label>Business Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ACR</fullName>
            </value>
            <value>
                <fullName>Non ACR</fullName>
            </value>
            <value>
                <fullName>Exhibition</fullName>
                <isActive>false</isActive>
                <label>Exhibition</label>
            </value>
            <value>
                <fullName>Shipment</fullName>
                <isActive>false</isActive>
                <label>Shipment</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/BVC_Entity__c.field-meta.xml
<CustomField>
    <fullName>BVC_Entity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BVC Entity</label>
    <referenceTo>Entity__c</referenceTo>
    <relationshipLabel>Deals</relationshipLabel>
    <relationshipName>Deals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/blng__BillingRule__c.field-meta.xml
<CustomField>
    <fullName>blng__BillingRule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing Rule</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>blng__BillingRule__c.blng__Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>blng__BillingRule__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/blng__RevenueRecognitionRule__c.field-meta.xml
<CustomField>
    <fullName>blng__RevenueRecognitionRule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Revenue Recognition Rule</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>blng__RevenueRecognitionRule__c.blng__Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>blng__RevenueRecognitionRule__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>RevenueRecognitionRuleProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/blng__TaxRule__c.field-meta.xml
<CustomField>
    <fullName>blng__TaxRule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tax Rule</label>
    <referenceTo>blng__TaxRule__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>TaxRulesProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/BVC_Entity__c.field-meta.xml
<CustomField>
    <fullName>BVC_Entity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BVC Entity</label>
    <referenceTo>Entity__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ST_NonACR_Standard_Price__c/ST_NonACR_Standard_Price__c.object-meta.xml
<CustomObject>
    <label>NonACR Standard Price</label>
    <nameField>
        <label>Non  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NonACR Standard Prices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ST_NonACR_Standard_Price__c/fields/ST_Gross_Weight_Slabs__c.field-meta.xml
<CustomField>
    <fullName>ST_Gross_Weight_Slabs__c</fullName>
    <label>Gross Weight Slabs</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ST_Gross_Weight_Slabs</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/CreateQuoteControllerTest.cls
@isTest
public class CreateQuoteControllerTest {
    @testSetup
    static void testSetup(){
        Entity__c ent = TestUtility.createBVCEntity();
        insert ent;
        
        Active_Pincode__c pin = TestUtility.createPinCode();
        insert pin;
        
        blng__LegalEntity__c legEntity = TestUtility.createLegalEntity(ent);
        insert legEntity;
        
        List<Hub__c> branches = new  List<Hub__c>();
        Hub__c bvcBranch = TestUtility.createBVCBranch(legEntity, pin);
        branches.add(bvcBranch);
        Hub__c originBranch = TestUtility.createBVCBranch(legEntity, pin);
        branches.add(originBranch);
        Hub__c destinationBranch = TestUtility.createBVCBranch(legEntity, pin);
        branches.add(destinationBranch);
        insert branches;
        system.debug('Branches::Test Setup::'+branches);
        List<Account> accList = new List<Account>();
        
        Account nonAcrNonContractedAccount = TestUtility.createNonACRnonContractedAccount();
        accList.add(nonAcrNonContractedAccount);
        Account nonACRContractedAccount = TestUtility.createNonACRnonContractedAccount();
        nonACRContractedAccount.Name = 'Non ACR Contracted Account';
        accList.add(nonACRContractedAccount);
        insert accList;
        
        Contact Con = TestUtility.createContact(accList[0]);
        insert Con;
        
        AccountContactRelation relation = [SELECT Id,AccountId,Roles FROM AccountContactRelation WHERE AccountId IN :accList LIMIT 1];//TestUtility.createAccountContactRelation(accList[0],con);
        relation.Roles = 'Finance; Invoice Recepient';
        update relation;
        
        List<Opportunity> oppList = TestUtility.createOpportunity(accList,Con,ent);
        insert oppList;
          
        blng__BillingRule__c bRule = TestUtility.createBillingRule();
        insert bRule;        
        
        blng__RevenueRecognitionRule__c revRule = TestUtility.createRevenueRule();
        insert revRule;
        
        blng__TaxRule__c taxRule = TestUtility.createTaxRule();
        insert taxRule;
        
        List<Product2> prodList = new List<Product2>();
        Product2 prod = TestUtility.createACRProduct(bRule, revRule, taxRule);
        prodList.add(prod);
        
        
        Product2 optionProduct = TestUtility.createProduct(bRule, revRule, taxRule);
        optionProduct.Name = 'Gold Surface C2C';
        Product2 valProduct = TestUtility.createValProduct(bRule, revRule, taxRule);
        valProduct.Name = 'SilverSHIP Express C2C';
        prodList.add(valProduct);
        prodList.add(optionProduct);
        insert prodList;
        
        SBQQ__ProductOption__c prodOption = TestUtility.createProductOption(prodList[0], prodList[1]);
        insert prodOption;
        
        Id stdPriceBookId = test.getStandardPricebookId();
        
        Pricebook2 pb = TestUtility.createPriceBook();
        insert pb;
        
        PricebookEntry standardACRPBE = new PricebookEntry(Pricebook2Id = stdPriceBookId, Product2Id = prodList[0].Id, UnitPrice = 1000, IsActive = true);
        insert standardACRPBE;
        
        PricebookEntry standardPBE = new PricebookEntry(Pricebook2Id = stdPriceBookId, Product2Id = prodList[1].Id, UnitPrice = 1000, IsActive = true);
        insert standardPBE;
        
        PricebookEntry standardvalPBE = new PricebookEntry(Pricebook2Id = stdPriceBookId, Product2Id = prodList[2].Id, UnitPrice = 1000, IsActive = true);
        insert standardvalPBE;
        
        
        List<PricebookEntry> customACRPrices = TestUtility.createACRPricebookEntry(pb.Id,prodList);
        insert customACRPrices;
        
        
        List<AddressBook__c> blngAddress = TestUtility.createAddressBook(accList);
        insert blngAddress;
        
        accList[0].Billing_Address__c = blngAddress[0].Id;
        update accList[0];
        
        List<ST_ACR_Standard_Price__c> stdACRPrice = TestUtility.createACRStandardPrice(prodList);
        insert stdACRPrice;
        
        ST_NonACR_Standard_Price__c nonAcrPrice = TestUtility.createNONACRStandardPrice(prodList[1]);
        insert nonAcrPrice;
         ST_NonACR_Standard_Price__c nonAcrPrice2 = TestUtility.createNONACRStandardPrice(prodList[2]);
        insert nonAcrPrice2;
        
        
        
        
    }
    
  @isTest
    public static void quoteTestMethod(){
        test.startTest();
        List<ST_NonACR_Standard_Price__c> nonAcrPrice = [SELECT Id FROM ST_NonACR_Standard_Price__c LIMIT 2];
        Pricebook2 pb = TestUtility.createPriceBook();
        insert pb;
        List<PricebookEntry> customACRPrices = [SELECT Id,Product2Id FROM PricebookEntry];
         AddressBook__c blngAddress = [SELECT Id,ADDRESS1__c,ADDRESS2__c,STATE__c,COUNTRY__c,
                                     PINCODE__c,CITY__c,Customer__c,Dealer_Type__c,GST_Registered_Status__c,
                                     GSTIN__c FROM AddressBook__c LIMIT 1];
        List<Hub__c> branch = [SELECT Id,Hub_Address_Line_1__c,Hub_Address_Line_2__c,
                               Hub_Pincode__c,ST_BVC_Billing_Entity__c,BVC_Entity__c
                               FROM Hub__c ];
        List<Opportunity> oppList = [SELECT Id,AccountId FROm Opportunity];
        
        List<SBQQ__Quote__c> quotes = TestUtility.createACRQuote(pb.Id, oppList, branch[0]);
        quotes[0].Business_Type__c = 'ACR';
         quotes[0].SBQQ__Status__c = 'Draft';
        quotes[0].SBQQ__StartDate__c = System.today();
        
		CreateQuoteController.CreateBVCQuote(quotes[0]);
        
        try{
            List<SBQQ__Quote__c> quotesNew = TestUtility.createACRQuote(pb.Id, oppList, branch[0]);
        quotesNew[0].Business_Type__c = null;
         
            CreateQuoteController.CreateBVCQuote(quotes[0]);
            
        }catch(Exception e){
            System.debug('Message  '+e.getMessage());
        }
        test.stopTest();
    }
    @isTest
    static void cloneQuoteRelatedTestMethod(){
        test.startTest();
        ST_NonACR_Standard_Price__c nonAcrPrice = [SELECT Id FROM ST_NonACR_Standard_Price__c LIMIT 1];
        Pricebook2 pb = TestUtility.createPriceBook();
        insert pb;
        List<PricebookEntry> customACRPrices = [SELECT Id,Product2Id FROM PricebookEntry];
         AddressBook__c blngAddress = [SELECT Id,ADDRESS1__c,ADDRESS2__c,STATE__c,COUNTRY__c,
                                     PINCODE__c,CITY__c,Customer__c,Dealer_Type__c,GST_Registered_Status__c,
                                     GSTIN__c FROM AddressBook__c LIMIT 1];
        List<Hub__c> branch = [SELECT Id,Hub_Address_Line_1__c,Hub_Address_Line_2__c,
                               Hub_Pincode__c,ST_BVC_Billing_Entity__c,BVC_Entity__c
                               FROM Hub__c ];
        List<Opportunity> oppList = [SELECT Id,AccountId FROm Opportunity];
        
        List<SBQQ__Quote__c> quotes = TestUtility.createACRQuote(pb.Id, oppList, branch[0]);
        quotes[0].Business_Type__c = 'Non ACR';
         quotes[0].SBQQ__Status__c = 'Draft';
        
        insert quotes;
        system.debug('Quotes>>>'+quotes);
        /*List<SBQQ__QuoteLine__c> quoteLines = new List<SBQQ__QuoteLine__c>();
        quoteLines.addAll(TestUtility.createnonACRQuoteLines(quotes[0].Id,customACRPrices,nonAcrPrice));
        quoteLines[0].ST_Gross_Weight_Slabs__c = '';
        insert quoteLines;*/
        Base_Quote_Settings__c baseQuote= new Base_Quote_Settings__c();
		baseQuote.Name = 'Non ACR';
        baseQuote.Base_QuoteId__c = quotes[0].Id;
        baseQuote.Quote_Business_Type__c = 'Non ACR';
        insert baseQuote;
        
        try{
            List<SBQQ__Quote__c> quotesNew = TestUtility.createACRQuote(pb.Id, oppList, branch[0]);
        	quotesNew[0].Business_Type__c = 'Non ACR';
             quotesNew[0].SBQQ__Status__c = 'Draft';
            quotesNew[0].SBQQ__StartDate__c = System.today();
         
            CreateQuoteController.CreateBVCQuote(quotesNew[0]);
            
        }catch(Exception e){
            System.debug('Message  '+e.getMessage());
        }
       
        
        
        test.stopTest();
    }
    
    @isTest
    static void cloneWithoutQuoteTestMethod(){
        test.startTest();
        ST_NonACR_Standard_Price__c nonAcrPrice = [SELECT Id FROM ST_NonACR_Standard_Price__c LIMIT 1];
        Pricebook2 pb = TestUtility.createPriceBook();
        insert pb;
        List<PricebookEntry> customACRPrices = [SELECT Id,Product2Id FROM PricebookEntry];
         AddressBook__c blngAddress = [SELECT Id,ADDRESS1__c,ADDRESS2__c,STATE__c,COUNTRY__c,
                                     PINCODE__c,CITY__c,Customer__c,Dealer_Type__c,GST_Registered_Status__c,
                                     GSTIN__c FROM AddressBook__c LIMIT 1];
        List<Hub__c> branch = [SELECT Id,Hub_Address_Line_1__c,Hub_Address_Line_2__c,
                               Hub_Pincode__c,ST_BVC_Billing_Entity__c,BVC_Entity__c
                               FROM Hub__c ];
        List<Opportunity> oppList = [SELECT Id,AccountId FROm Opportunity];
        
        List<SBQQ__Quote__c> quotes = TestUtility.createACRQuote(pb.Id, oppList, branch[0]);
        quotes[0].Business_Type__c = 'Non ACR';
         quotes[0].SBQQ__Status__c = 'Draft';
        
        insert quotes;
        system.debug('Quotes>>>'+quotes);
        
        try{
            List<SBQQ__Quote__c> quotesNew = TestUtility.createACRQuote(pb.Id, oppList, branch[0]);
        	quotesNew[0].Business_Type__c = 'Non ACR';
             quotesNew[0].SBQQ__Status__c = 'Draft';
            quotesNew[0].SBQQ__StartDate__c = System.today();
         
            CreateQuoteController.CreateBVCQuote(quotesNew[0]);
            
        }catch(Exception e){
            System.debug('Message  '+e.getMessage());
        }
       
        
        
        test.stopTest();
    }
    //exhibition
      @isTest
    static void cloneQuoteexhibition(){
        test.startTest();
        ST_NonACR_Standard_Price__c nonAcrPrice = [SELECT Id FROM ST_NonACR_Standard_Price__c LIMIT 1];
        Pricebook2 pb = TestUtility.createPriceBook();
        insert pb;
        List<PricebookEntry> customACRPrices = [SELECT Id,Product2Id FROM PricebookEntry];
         AddressBook__c blngAddress = [SELECT Id,ADDRESS1__c,ADDRESS2__c,STATE__c,COUNTRY__c,
                                     PINCODE__c,CITY__c,Customer__c,Dealer_Type__c,GST_Registered_Status__c,
                                     GSTIN__c FROM AddressBook__c LIMIT 1];
        List<Hub__c> branch = [SELECT Id,Hub_Address_Line_1__c,Hub_Address_Line_2__c,
                               Hub_Pincode__c,ST_BVC_Billing_Entity__c,BVC_Entity__c
                               FROM Hub__c ];
        List<Opportunity> oppList = [SELECT Id,AccountId FROm Opportunity];
        
        	ST_Exhibition__c newexb = TestUtility.createExhibition();
        newexb.Name = 'ABC exhibition';
        newexb.ST_Active__c = true;
        insert newexb;
       
        List<SBQQ__Quote__c> quotes = TestUtility.createACRQuote(pb.Id, oppList, branch[0]);
        quotes[0].Business_Type__c = 'Exhibition';
         quotes[0].SBQQ__Status__c = 'Draft';
        quotes[0].Exhibition__c =newexb.Id;
        
        insert quotes;
        system.debug('Quotes>>>'+quotes);
        /*List<SBQQ__QuoteLine__c> quoteLines = new List<SBQQ__QuoteLine__c>();
        quoteLines.addAll(TestUtility.createnonACRQuoteLines(quotes[0].Id,customACRPrices,nonAcrPrice));
        quoteLines[0].ST_Gross_Weight_Slabs__c = '';
        insert quoteLines;*/
        Base_Quote_Settings__c baseQuote= new Base_Quote_Settings__c();
		baseQuote.Name = newexb.Id;
        baseQuote.Base_QuoteId__c = quotes[0].Id;
        baseQuote.Quote_Business_Type__c = 'Exhibition';
        insert baseQuote;
        
        try{
            List<SBQQ__Quote__c> quotesNew = TestUtility.createACRQuote(pb.Id, oppList, branch[0]);
        	quotesNew[0].Business_Type__c = 'Exhibition';
             quotesNew[0].SBQQ__Status__c = 'Draft';
            quotesNew[0].SBQQ__StartDate__c = System.today();
            quotesNew[0].Exhibition__c =newexb.Id;
            CreateQuoteController.CreateBVCQuote(quotesNew[0]);
            
        }catch(Exception e){
            System.debug('Message  '+e.getMessage());
        }
       
        
        
        test.stopTest();
    }
  
}