force-app/main/default/objects/Account/fields/Billing_Address__c.field-meta.xml
<CustomField>
    <fullName>Billing_Address__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Billing Address</label>
    <referenceTo>AddressBook__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Billing_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Billing_Frequency__c</fullName>
    <label>Billing Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Shipment</fullName>
                <default>true</default>
                <label>Shipment</label>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Forthnightly</fullName>
                <isActive>false</isActive>
                <label>Forthnightly</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Is_Finance_Contact_Present__c.field-meta.xml
<CustomField>
    <fullName>Is_Finance_Contact_Present__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Finance Contact Present</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Mobile__c.field-meta.xml
<CustomField>
    <fullName>Mobile__c</fullName>
    <label>Mobile</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Address__c.field-meta.xml
<CustomField>
    <fullName>Primary_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Address</label>
    <referenceTo>AddressBook__c</referenceTo>
    <relationshipLabel>Customers</relationshipLabel>
    <relationshipName>Customers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Customer_Email__c.field-meta.xml
<CustomField>
    <fullName>Primary_Customer_Email__c</fullName>
    <label>Primary Customer Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Billing.recordType-meta.xml
<RecordType>
    <fullName>Billing</fullName>
    <active>true</active>
    <description>Record Type for Domestic Customers.</description>
    <label>Billing</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Shipping.recordType-meta.xml
<RecordType>
    <fullName>Shipping</fullName>
    <active>true</active>
    <description>Record Type for Shipping Customers.</description>
    <label>Shipping</label>
</RecordType>

force-app/main/default/objects/Active_Pincode__c/Active_Pincode__c.object-meta.xml
<CustomObject>
    <label>Active Pincode</label>
    <nameField>
        <label>Pincode</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Active Pincodes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Active_Pincode__c/fields/Hub__c.field-meta.xml
<CustomField>
    <fullName>Hub__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hub</label>
    <referenceTo>Hub__c</referenceTo>
    <relationshipLabel>Active Pincodes</relationshipLabel>
    <relationshipName>Active_Pincodes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AddressBook__c/AddressBook__c.object-meta.xml
<CustomObject>
    <description>Primarily stores multiple shipping and billing addresses.</description>
    <label>Address Book</label>
    <nameField>
        <label>Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AddressBook__c/fields/Active_Pincode__c.field-meta.xml
<CustomField>
    <fullName>Active_Pincode__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Active Pincode</label>
    <referenceTo>Active_Pincode__c</referenceTo>
    <relationshipLabel>Addresses (Active Pincode)</relationshipLabel>
    <relationshipName>Addresses1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AddressBook__c/fields/Pincode_TMS__c.field-meta.xml
<CustomField>
    <fullName>Pincode_TMS__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pincode</label>
    <referenceTo>Active_Pincode__c</referenceTo>
    <relationshipLabel>Addresses</relationshipLabel>
    <relationshipName>Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AddressBook__c/recordTypes/Billing.recordType-meta.xml
<RecordType>
    <fullName>Billing</fullName>
    <active>true</active>
    <label>Billing</label>
</RecordType>

force-app/main/default/objects/AddressBook__c/recordTypes/Shipping.recordType-meta.xml
<RecordType>
    <fullName>Shipping</fullName>
    <active>true</active>
    <label>Shipping</label>
</RecordType>

force-app/main/default/objects/Contact/fields/AddressBook__c.field-meta.xml
<CustomField>
    <fullName>AddressBook__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AddressBook</label>
    <referenceTo>AddressBook__c</referenceTo>
    <relationshipLabel>People</relationshipLabel>
    <relationshipName>People</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Shipment__c.field-meta.xml
<CustomField>
    <fullName>Shipment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shipment</label>
    <referenceTo>Shipment__c</referenceTo>
    <relationshipLabel>People</relationshipLabel>
    <relationshipName>People</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/blng__BillingRule__c.field-meta.xml
<CustomField>
    <fullName>blng__BillingRule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing Rule</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>blng__BillingRule__c.blng__Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>blng__BillingRule__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/blng__RevenueRecognitionRule__c.field-meta.xml
<CustomField>
    <fullName>blng__RevenueRecognitionRule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Revenue Recognition Rule</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>blng__RevenueRecognitionRule__c.blng__Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>blng__RevenueRecognitionRule__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>RevenueRecognitionRuleProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/blng__TaxRule__c.field-meta.xml
<CustomField>
    <fullName>blng__TaxRule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tax Rule</label>
    <referenceTo>blng__TaxRule__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>TaxRulesProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipment__c/Shipment__c.object-meta.xml
<CustomObject>
    <description>Shipment object stores shipments requested against a pickup.</description>
    <label>Shipment</label>
    <nameField>
        <displayFormat>ST-{0000000}</displayFormat>
        <label>Shipment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipment__c/fields/AddressBook__c.field-meta.xml
<CustomField>
    <fullName>AddressBook__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Address</label>
    <referenceTo>AddressBook__c</referenceTo>
    <relationshipLabel>Shipments</relationshipLabel>
    <relationshipName>Shipments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Bill_To_Account__c.field-meta.xml
<CustomField>
    <fullName>Bill_To_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bill Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Shipments (Bill To Account)</relationshipLabel>
    <relationshipName>Shipments2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Billing_Address__c.field-meta.xml
<CustomField>
    <fullName>Billing_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing Address</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AddressBook__c.Customer__c</field>
            <operation>equals</operation>
            <valueField>$Source.Billing_Account__c</valueField>
        </filterItems>
        <filterItems>
            <field>AddressBook__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Billing</value>
        </filterItems>
        <filterItems>
            <field>AddressBook__c.Is_Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>AddressBook__c</referenceTo>
    <relationshipLabel>Shipments (Billing Address)</relationshipLabel>
    <relationshipName>Shipments3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/BillTo_Party_Address__c.field-meta.xml
<CustomField>
    <fullName>BillTo_Party_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bill To Party Address</label>
    <referenceTo>AddressBook__c</referenceTo>
    <relationshipLabel>Shipments (Bill To Party Address)</relationshipLabel>
    <relationshipName>BVCShipments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Gross_Weight__c.field-meta.xml
<CustomField>
    <fullName>Gross_Weight__c</fullName>
    <description>The shipment weight to be used for all kind of shipments</description>
    <label>BVC Gross Weight</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Origin_Address_Name__c.field-meta.xml
<CustomField>
    <fullName>Origin_Address_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Origin Address Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Shipper_Name_TMS__c</field>
            <operation>equals</operation>
            <valueField>AddressBook__c.Customer__c</valueField>
        </filterItems>
        <filterItems>
            <field>AddressBook__c.Is_Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AddressBook__c</referenceTo>
    <relationshipLabel>Shipments (Origin Address Name)</relationshipLabel>
    <relationshipName>Shipments1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Shipment_Date__c.field-meta.xml
<CustomField>
    <fullName>Shipment_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <description>This is the Shipment date for Domestic</description>
    <label>Shipment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ST_ACR_Standard_Price__c/ST_ACR_Standard_Price__c.object-meta.xml
<CustomObject>
    <label>ACR Standard Price</label>
    <nameField>
        <displayFormat>ACR-{0000}</displayFormat>
        <label>ACR Standard Price Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ACR Standard Price</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ST_ACR_Standard_Price__c/fields/ST_Destination__c.field-meta.xml
<CustomField>
    <fullName>ST_Destination__c</fullName>
    <label>Destination</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ST_ACR_Standard_Price__c/fields/ST_Freight_on_Invoice_Value__c.field-meta.xml
<CustomField>
    <fullName>ST_Freight_on_Invoice_Value__c</fullName>
    <label>Freight on Invoice Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/ST_ACR_Standard_Price__c/fields/ST_Origin__c.field-meta.xml
<CustomField>
    <fullName>ST_Origin__c</fullName>
    <label>Origin</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ST_NonACR_Standard_Price__c/ST_NonACR_Standard_Price__c.object-meta.xml
<CustomObject>
    <label>NonACR Standard Price</label>
    <nameField>
        <label>Non  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NonACR Standard Prices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ST_NonACR_Standard_Price__c/fields/ST_Destination__c.field-meta.xml
<CustomField>
    <fullName>ST_Destination__c</fullName>
    <label>Destination</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ST_NonACR_Standard_Price__c/fields/ST_Freight_on_Invoice_Value__c.field-meta.xml
<CustomField>
    <fullName>ST_Freight_on_Invoice_Value__c</fullName>
    <label>Freight on Invoice Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/ST_NonACR_Standard_Price__c/fields/ST_Gross_Weight_Slabs__c.field-meta.xml
<CustomField>
    <fullName>ST_Gross_Weight_Slabs__c</fullName>
    <label>Gross Weight Slabs</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ST_Gross_Weight_Slabs</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/PlatformUserBatchTest.cls
@isTest
public class PlatformUserBatchTest {

    @testSetup
    static void testSetup(){
        
       test.startTest();
        Entity__c ent = TestUtility.createBVCEntity();
        insert ent;
        
        Active_Pincode__c pin = TestUtility.createPinCode();
        insert pin;
        
        blng__LegalEntity__c legEntity = TestUtility.createLegalEntity(ent);
        insert legEntity;
        
        List<Hub__c> branches = new  List<Hub__c>();
        Hub__c bvcBranch = TestUtility.createBVCBranch(legEntity, pin);
        branches.add(bvcBranch);
        Hub__c originBranch = TestUtility.createBVCBranch(legEntity, pin);
        branches.add(originBranch);
        Hub__c destinationBranch = TestUtility.createBVCBranch(legEntity, pin);
        branches.add(destinationBranch);
        insert branches;
        Active_Pincode__c bengaluruPin = TestUtility.createBengaluruPinCode(branches[1]);
        insert bengaluruPin;
        system.debug('BEngalurur Pin:::'+bengaluruPin);
        system.debug('Branches::Test Setup::'+branches);
        List<Account> accList = new List<Account>();
        
               
        Account nonAcrNonContractedAccount = TestUtility.createNonACRnonContractedAccount();
        nonAcrNonContractedAccount.Name = 'Test Account';
        nonAcrNonContractedAccount.Email__c='gvj@dfg.com'; 
        nonAcrNonContractedAccount.Last_Name__c='hbiuhm';
        nonAcrNonContractedAccount.Phone='1234567891';
        nonAcrNonContractedAccount.Mobile__c='4567892345'; 
        nonAcrNonContractedAccount.Primary_Customer_Email__c='testre@rr.com';
        accList.add(nonAcrNonContractedAccount);
        insert accList;
        
        Contact Con = TestUtility.createContact(accList[0]);
        insert Con;
        
        AccountContactRelation relation = [SELECT Id,AccountId,ContactId,Contact.Email,Roles FROM AccountContactRelation WHERE AccountId IN :accList LIMIT 1];//TestUtility.createAccountContactRelation(accList[0],con);
        relation.Roles = 'Finance; Invoice Recepient';
        update relation;
        
        List<Opportunity> oppList = TestUtility.createOpportunity(accList,con,ent);
        insert oppList;
        
        blng__BillingRule__c bRule = TestUtility.createBillingRule();
        insert bRule;        
        
        blng__RevenueRecognitionRule__c revRule = TestUtility.createRevenueRule();
        insert revRule;
        
        blng__TaxRule__c taxRule = TestUtility.createTaxRule();
        insert taxRule;
        
        List<Product2> prodList = new List<Product2>();
        Product2 prod = TestUtility.createACRProduct(bRule, revRule, taxRule);
        prodList.add(prod);
        
        
        Product2 optionProduct = TestUtility.createProduct(bRule, revRule, taxRule);
        prodList.add(optionProduct);
        
        Product2 valProduct = TestUtility.createValProduct(bRule, revRule, taxRule);
        prodList.add(valProduct);
        insert prodList;
        
        SBQQ__ProductOption__c prodOption = TestUtility.createProductOption(prodList[0], prodList[1]);
        insert prodOption;
        
        Id stdPriceBookId = test.getStandardPricebookId();
        
        Pricebook2 pb = TestUtility.createPriceBook();
        insert pb;
        
        PricebookEntry standardACRPBE = new PricebookEntry(Pricebook2Id = stdPriceBookId, Product2Id = prodList[0].Id, UnitPrice = 1000, IsActive = true);
        insert standardACRPBE;
        
        PricebookEntry standardPBE = new PricebookEntry(Pricebook2Id = stdPriceBookId, Product2Id = prodList[1].Id, UnitPrice = 1000, IsActive = true);
        insert standardPBE;
        
        PricebookEntry standarValdPBE = new PricebookEntry(Pricebook2Id = stdPriceBookId, Product2Id = prodList[2].Id, UnitPrice = 1000, IsActive = true);
        insert standarValdPBE;
        
        
        List<PricebookEntry> customACRPrices = TestUtility.createACRPricebookEntry(pb.Id,prodList);
        insert customACRPrices;
        
        
        List<AddressBook__c> blngAddress = TestUtility.createAddressBook(accList);
        AddressBook__c destiAddressBook = TestUtility.destinationAddress(accList[0]);
        AddressBook__c originAddressBook = TestUtility.originAddress(accList[0]);
        originAddressBook.Pincode_TMS__c = bengaluruPin.Id;
        blngAddress.add(destiAddressBook);
        blngAddress.add(originAddressBook);
        insert blngAddress;
        
        accList[0].Billing_Address__c = blngAddress[0].Id;
        accList[0].Billing_Address__c = blngAddress[0].Id;
        accList[0].Is_Finance_Contact_Present__c = true;
        accList[0].Primary_Address__c = blngAddress[0].Id;
        update accList[0];
        //update accList[0];
        
        List<ST_ACR_Standard_Price__c> stdACRPrice = TestUtility.createACRStandardPrice(prodList);
        insert stdACRPrice;
        
        List<ST_NonACR_Standard_Price__c> nonACRPriceList = new List<ST_NonACR_Standard_Price__c>();
        ST_NonACR_Standard_Price__c nonAcrPrice1 = TestUtility.createNONACRStandardPrice(prodList[1]);
        nonACRPriceList.add(nonAcrPrice1);
        
        ST_NonACR_Standard_Price__c nonAcrPrice2 = TestUtility.createNONACRStandardPrice(prodList[2]);
        nonAcrPrice2.ST_Destination__c = 'Bengaluru';
        nonAcrPrice2.ST_Origin__c = 'Mumbai';
        nonAcrPrice2.ST_Freight_on_Invoice_Value__c = 0.01;
        nonACRPrice2.ST_Gross_Weight_Slabs__c = '';
        nonACRPriceList.add(nonAcrPrice2);
        insert nonACRPriceList;
        Account shipperAccount = TestUtility.createShipperAccount();
        insert shipperAccount;
        AddressBook__c shipperAddress = BVCL_TestDataFactory.CreateAddress('Shipping',shipperAccount.id,'Line 1',bengaluruPin.id,'Bengaluru',true);
        Shipment__c ship1 = BVCL_TestDataFactory.createShipment(accList[0].id, shipperAccount.id, ShipperAddress.id, shipperAccount.id, ShipperAddress.id, false);
        ship1.Shipment_Date__c = system.today();
        ship1.Gross_Weight__c = 8000;
        insert ship1;
        
        test.stopTest();
         
        
        
    }
    @isTest
    private static void methodTest(){
        test.startTest();
        //sam
        Account acc1=TestUtility.createNonACRnonContractedAccount();
        insert acc1;
                
    	Shipment__c ship = [SELECT Id,Bill_To_Account__c,Shipment_Date__c,Bill_To_Account__r.Billing_Frequency__c,BillTo_Party_Address__c,Origin_Address_Name__c,Destination_Address_Name__c,Bill_To_Account__r.Active_contract__c,
                            Bill_To_Account__r.Customer_Category__c,Bill_To_Account__r.Contract_End_Date__c,Bill_To_Account__r.Contracted_ACR_Package__c,Bill_To_Account__r.Balance_Amount__c,Shipment_Value__c,
                            Shipment_Number__c,Shipping_Note_Number__c,Origin_Hub__c,Bill_To_Account__r.Name,Origin_Hub__r.ST_BVC_Billing_Entity__c,Product_Code__c,Gross_Weight__c,Status__c,Ready_for_Billing__c,Liability_Cover_By_BVC__c,
                            Origin_Type__c,Destination_Type__c,platform_User__c FROM Shipment__c  LIMIT 1];
        system.debug('Shipment Non ACR Non Contracted::Test::Class::'+ship.Bill_To_Account__r.Billing_Frequency__c);
       
        ship.Liability_Cover_By_BVC__c = 'Yes';
        ship.Next_Billing_Date__c = system.today().adddays(3);
        ship.Status__c = 'Verified for Billing';
        ship.Product_Code__c = 'GOLD-EX-C2C';
        update ship;
        
        Map<String,Schema.SObjectType> schemaMap = Schema.getGlobalDescribe();
        Map<String,Schema.SObjectField> fieldMap = schemaMap.get('Shipment__c').getDescribe().fields.getMap();
        List<String> fieldNames = new List<String>();
        
        for(String fieldName : fieldMap.keySet()) {
            Schema.DescribeFieldResult fieldDescribe = fieldMap.get(fieldName).getDescribe();
            
            fieldNames.add(fieldName);
            
        } 
        string query = 'SELECT '+String.join(fieldNames , ' , ')+' FROM Shipment__c WHERE Id = \''+String.valueOf(ship.Id)+'\'';
        List<Shipment__c> ships = Database.query(query);
        Set<Id> ids = new Set<Id>{ship.Id};
        List<Shipment__c> shipments = new List<Shipment__c>();
        shipments.addAll(ships);
            
		 PlatformUserBatch cb = new PlatformUserBatch(ids);
            cb.execute(null,shipments);
        PlatformUserBatch.fakeMethod();
         test.stopTest();
    }
}