force-app/main/default/objects/Account/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/PAN_Number_of_Entity__c.field-meta.xml
<CustomField>
    <fullName>PAN_Number_of_Entity__c</fullName>
    <label>PAN Number of Entity</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Customer_Email__c.field-meta.xml
<CustomField>
    <fullName>Primary_Customer_Email__c</fullName>
    <label>Primary Customer Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Billing.recordType-meta.xml
<RecordType>
    <fullName>Billing</fullName>
    <active>true</active>
    <description>Record Type for Domestic Customers.</description>
    <label>Billing</label>
</RecordType>

force-app/main/default/classes/Send_Report_AttachementTest.cls
@isTest
public class Send_Report_AttachementTest {
@testSetup static void testDataSetup(){
         
        RecordType rec=[SELECT id FROM RecordType WHERE name = 'Billing' and sobjecttype ='Account'];
         Account acc= new Account();
        acc.Name='Test1';
        acc.Last_Name__c='Test';
        acc.RecordTypeId=rec.id;
        acc.PAN_Number_of_Entity__c='546gtyhu78';
        acc.Primary_Customer_Email__c='test1@bvc.com';
        insert acc;
      }
    @istest static void createAnnexureAccountTest1(){
       Send_Report_Attachement.fMethod();
    }
}