force-app/main/default/objects/Digital_Shipping_Label__c/Digital_Shipping_Label__c.object-meta.xml
<CustomObject>
    <label>Digital Shipping Label</label>
    <nameField>
        <label>Digital Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Digital Shipping Label</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Digital_Shipping_Label__c/fields/Shipment__c.field-meta.xml
<CustomField>
    <fullName>Shipment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shipment</label>
    <referenceTo>Shipment__c</referenceTo>
    <relationshipLabel>Digital Shipping Label</relationshipLabel>
    <relationshipName>Digital_Shipping_Label</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Digital_Shipping_Label__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Consumed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Digital_Shipping_Label__c/fields/Status_Identifier__c.field-meta.xml
<CustomField>
    <fullName>Status_Identifier__c</fullName>
    <label>Status Identifier</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Order/fields/Shipment__c.field-meta.xml
<CustomField>
    <fullName>Shipment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shipment</label>
    <referenceTo>Shipment__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipment__c/Shipment__c.object-meta.xml
<CustomObject>
    <description>Shipment object stores shipments requested against a pickup.</description>
    <label>Shipment</label>
    <nameField>
        <displayFormat>ST-{0000000}</displayFormat>
        <label>Shipment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipment__c/fields/Origin_Hub__c.field-meta.xml
<CustomField>
    <fullName>Origin_Hub__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Origin Hub</label>
    <referenceTo>Hub__c</referenceTo>
    <relationshipLabel>Shipments</relationshipLabel>
    <relationshipName>HubShipments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Shipping_Note_Number__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Note_Number__c</fullName>
    <description>This is the Domestic Shipping Note number</description>
    <label>Shipping Note Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Pending Billing</fullName>
            </value>
            <value>
                <fullName>Verified For Billing</fullName>
            </value>
            <value>
                <fullName>Picked for Billing</fullName>
            </value>
            <value>
                <fullName>ACR Consumed</fullName>
            </value>
            <value>
                <fullName>Billed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TMS_UpdateShipment_ShippingNoteNo.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 08-24-2021
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public without sharing class TMS_UpdateShipment_ShippingNoteNo { 
    
    @invocableMethod
    public static void updateShippingNoteNo ( List<Shipment__c> shipmentList) {

        List<Shipment__c> shipmentToUpdate = new List<Shipment__c>();
        List<Digital_Shipping_Label__c> securePackagingList = new List<Digital_Shipping_Label__c>();
        Map<Digital_Shipping_Label__c,Shipment__c> mapOfSecurePack = new Map<Digital_Shipping_Label__c,Shipment__c>();
        /*Set<Id> hubIdSet = new Set<Id> ();

        for(Shipment__c shipmentRecord :  shipmentList){
            hubIdSet.Add(shipmentRecord.Origin_Hub__c);
        } 

        System.debug('====== hubIdSet =========== '+hubIdSet);*/

        Digital_Shipping_Label__c [] securePackaging = [
            SELECT Id, Name, Status__c,Status_Identifier__c FROM Digital_Shipping_Label__c WHERE Status__c = 'Available'
            ORDER BY Status_Identifier__c ASC  LIMIT 1000
            //AND Allocated_To_Hub__c IN: hubIdSet
        ]; 

        System.debug('===================  securePackaging ========'+securePackaging.size());


        if(securePackaging.size() > 0 && shipmentList.size() <= securePackaging.size() ) { 
            for(Integer i = 0; i < shipmentList.size(); i++) {
                mapOfSecurePack.put(securePackaging[i],shipmentList[i] );
            }
            for(Digital_Shipping_Label__c sp1 : mapOfSecurePack.keyset()) {
                if(mapOfSecurePack.containsKey(sp1)) {

                    Shipment__c tempShipment = new Shipment__c();
                    tempShipment.Id = mapOfSecurePack.get(sp1).Id;
                    tempShipment.Shipping_Note_Number__c = sp1.Name;
                    shipmentToUpdate.add(tempShipment);
                    
                    Digital_Shipping_Label__c tempsbag = new Digital_Shipping_Label__c();
                    tempsbag.Id = sp1.Id;
                    tempsbag.Status__c = 'Consumed';
                    tempsbag.Shipment__c = tempShipment.Id;
                    securePackagingList.add(tempsbag);
                }
                
            }
        }
        
        if(shipmentToUpdate.size()>0 && securePackagingList.size() > 0){
            Database.SaveResult[] saveResultList = Database.update(shipmentToUpdate, false);
            system.debug('-------myupdate----'+saveResultList);
            Database.SaveResult[] saveResultList1 = Database.update(securePackagingList, false);
            system.debug('-------myupdate1----'+saveResultList1);
        }
    }
}