force-app/main/default/objects/Shipment__c/Shipment__c.object-meta.xml
<CustomObject>
    <description>Shipment object stores shipments requested against a pickup.</description>
    <label>Shipment</label>
    <nameField>
        <displayFormat>ST-{0000000}</displayFormat>
        <label>Shipment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipment__c/fields/Bill_to_1__c.field-meta.xml
<CustomField>
    <fullName>Bill_to_1__c</fullName>
    <label>Bill to</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Shipper</fullName>
                <default>true</default>
                <label>Shipper</label>
            </value>
            <value>
                <fullName>Consignee</fullName>
            </value>
            <value>
                <fullName>Third Party</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Invoice_Calculated_Amount__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Calculated_Amount__c</fullName>
    <label>Invoice Calculated Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/ShipmentsTriggerTest.cls
@isTest(SeeAllData=false)
public class ShipmentsTriggerTest {
    
    public static testMethod void ShipmentsTriggerTestMethod(){
        List<Shipment__c> newShipList= new List<shipment__c>();
        List<Shipment__c> oldShipList = new List<Shipment__c>();
       shipment__c newShip = new Shipment__c();
         newShip.Bill_to_1__c = 'shipper';
          newShipList.add(newShip);
        test.startTest();
           insert newShipList;
       
         newShip=[select id,Bill_to_1__c,Invoice_Calculated_Amount__c from shipment__c where id=:newShip.id];
         newShip.Bill_to_1__c = 'consignee';
         newShip.Invoice_Calculated_Amount__c = 43;
            oldShipList.add(newShip);

            update oldShipList;
        
        newship=[select id,Bill_to_1__c from shipment__c where Bill_to_1__c ='consignee'];
        delete newship;
        
        newship=[select id,Bill_to_1__c from shipment__c where Bill_to_1__c ='consignee' ALL ROWS];
        undelete newship;
        test.stopTest();
               
        
    }
	    

}