force-app/main/default/objects/Delivery__c/Delivery__c.object-meta.xml
<CustomObject>
    <label>Delivery</label>
    <nameField>
        <displayFormat>D-{0000000}</displayFormat>
        <label>Delivery Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deliveries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery__c/fields/Actual_Delivery_Date_and_Time__c.field-meta.xml
<CustomField>
    <fullName>Actual_Delivery_Date_and_Time__c</fullName>
    <label>Actual Delivery Date and Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Delivery__c/fields/Consignee_Name__c.field-meta.xml
<CustomField>
    <fullName>Consignee_Name__c</fullName>
    <label>Consignee Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Delivery__c/fields/Delivered_To_Person__c.field-meta.xml
<CustomField>
    <fullName>Delivered_To_Person__c</fullName>
    <label>Delivered To Person</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Delivery__c/fields/Number_of_Secure_Bag__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Secure_Bag__c</fullName>
    <formula>Shipment__r.Number_of_Secure_Bags__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Number of Secure Bag</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Delivery__c/fields/Shipment__c.field-meta.xml
<CustomField>
    <fullName>Shipment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shipment</label>
    <referenceTo>Shipment__c</referenceTo>
    <relationshipLabel>Deliveries</relationshipLabel>
    <relationshipName>Deliveries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Delivery__c/fields/Shipping_Note_Number__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Note_Number__c</fullName>
    <formula>Shipment__r.Shipping_Note_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Shipping Note Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Delivery__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
                <default>true</default>
                <label>Assigned</label>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Secure_Bag__c/Secure_Bag__c.object-meta.xml
<CustomObject>
    <label>Secure Bag</label>
    <nameField>
        <displayFormat>SB-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Secure Bags</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Secure_Bag__c/fields/Current_Scan_Loction__c.field-meta.xml
<CustomField>
    <fullName>Current_Scan_Loction__c</fullName>
    <label>Current Scan Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
            </value>
            <value>
                <fullName>Out for Pickup</fullName>
            </value>
            <value>
                <fullName>Picked Up</fullName>
            </value>
            <value>
                <fullName>Origin Hub</fullName>
            </value>
            <value>
                <fullName>Origin Port</fullName>
            </value>
            <value>
                <fullName>Transit Hub</fullName>
            </value>
            <value>
                <fullName>Transit Port</fullName>
            </value>
            <value>
                <fullName>Destination Port</fullName>
            </value>
            <value>
                <fullName>Destination Hub</fullName>
            </value>
            <value>
                <fullName>Out for Delivery</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Secure_Bag__c/fields/Secure_Bag__c.field-meta.xml
<CustomField>
    <fullName>Secure_Bag__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Secure Bag</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Secure_Packaging__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Secure Bag</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Secure_Packaging__c</referenceTo>
    <relationshipLabel>Secure Bags</relationshipLabel>
    <relationshipName>Secure_Bags</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Secure_Bag__c/fields/Secure_Packaging_Identifier__c.field-meta.xml
<CustomField>
    <fullName>Secure_Packaging_Identifier__c</fullName>
    <formula>Secure_Bag__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Secure Packaging Identifier</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Secure_Bag__c/fields/Shipment__c.field-meta.xml
<CustomField>
    <fullName>Shipment__c</fullName>
    <label>Shipment</label>
    <referenceTo>Shipment__c</referenceTo>
    <relationshipLabel>Secure Bags</relationshipLabel>
    <relationshipName>SecureBags</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Shipment__c/Shipment__c.object-meta.xml
<CustomObject>
    <description>Shipment object stores shipments requested against a pickup.</description>
    <label>Shipment</label>
    <nameField>
        <displayFormat>ST-{0000000}</displayFormat>
        <label>Shipment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipment__c/fields/Actual_Delivery_Date_and_Time__c.field-meta.xml
<CustomField>
    <fullName>Actual_Delivery_Date_and_Time__c</fullName>
    <label>Actual Delivery Date and Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Consignee_Designation__c.field-meta.xml
<CustomField>
    <fullName>Consignee_Designation__c</fullName>
    <label>Consignee Designation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Destination_Address_Name__c.field-meta.xml
<CustomField>
    <fullName>Destination_Address_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Destination Address Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Consignee_Name_TMS__c</field>
            <operation>equals</operation>
            <valueField>AddressBook__c.Customer__c</valueField>
        </filterItems>
        <filterItems>
            <field>AddressBook__c.Is_Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>AddressBook__c</referenceTo>
    <relationshipLabel>Shipment Delivery</relationshipLabel>
    <relationshipName>ShipmentsDelivery</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Shipping_Note_Number__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Note_Number__c</fullName>
    <description>This is the Domestic Shipping Note number</description>
    <label>Shipping Note Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Pending Billing</fullName>
            </value>
            <value>
                <fullName>Verified For Billing</fullName>
            </value>
            <value>
                <fullName>Picked for Billing</fullName>
            </value>
            <value>
                <fullName>ACR Consumed</fullName>
            </value>
            <value>
                <fullName>Billed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Tracking_Status__c.field-meta.xml
<CustomField>
    <fullName>Tracking_Status__c</fullName>
    <label>Tracking Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
                <default>true</default>
                <label>Created</label>
            </value>
            <value>
                <fullName>Out for Pickup</fullName>
            </value>
            <value>
                <fullName>Picked Up</fullName>
            </value>
            <value>
                <fullName>Origin Hub</fullName>
            </value>
            <value>
                <fullName>Origin Port</fullName>
            </value>
            <value>
                <fullName>Transit Hub</fullName>
            </value>
            <value>
                <fullName>Transit Port</fullName>
            </value>
            <value>
                <fullName>Destination Port</fullName>
            </value>
            <value>
                <fullName>Destination Hub</fullName>
            </value>
            <value>
                <fullName>Out for Delivery</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Out of Linehaul</fullName>
            </value>
            <value>
                <fullName>Linehaul Deposit</fullName>
            </value>
            <value>
                <fullName>Linehaul In-Transit</fullName>
            </value>
            <value>
                <fullName>Linehaul Retrieved</fullName>
            </value>
            <value>
                <fullName>At Destination Airport</fullName>
                <isActive>false</isActive>
                <label>At Destination Airport</label>
            </value>
            <value>
                <fullName>At Origin Airport</fullName>
                <isActive>false</isActive>
                <label>At Origin Airport</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <isActive>false</isActive>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>In Transit</fullName>
                <isActive>false</isActive>
                <label>In Transit</label>
            </value>
            <value>
                <fullName>Source Hub</fullName>
                <isActive>false</isActive>
                <label>Source Hub</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Shipment_Tracking__c/Shipment_Tracking__c.object-meta.xml
<CustomObject>
    <label>Tracking</label>
    <nameField>
        <displayFormat>STN-{000000}</displayFormat>
        <label>Shipment Tracking Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tracking</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipment_Tracking__c/fields/Shipment__c.field-meta.xml
<CustomField>
    <fullName>Shipment__c</fullName>
    <label>Shipment</label>
    <referenceTo>Shipment__c</referenceTo>
    <relationshipLabel>Tracking</relationshipLabel>
    <relationshipName>Shipment_Trackings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TSM_SignatureHelper.cls
/**
* @description       : 
* @author            : ChangeMeIn@UserSettingsUnder.SFDoc   //Rafi Khan
* @group             : 
* @last modified on  : 03-21-2022                           // 29-05-2023
* @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc   //rafi.khan@bvclogistics.com
* Update with Respect to tracking API - 07-01-2022
**/
public without sharing class TSM_SignatureHelper { 
    
    @AuraEnabled(cacheable=true)
    public static Delivery__c getshipmetID(Id recId){    
        List<Delivery__c> lstship  = [Select Id,Shipment__r.Id from Delivery__c where Id =:recId];
        return lstship[0];
    }
    
    /*@AuraEnabled(cacheable=true)
public static String getshipmetID(Id recId){    
List<Delivery__c> lstship  = [Select Id, Shipment__r.Id from Delivery__c where Id =:recId];
return lstship[0].Shipment__r.Id; 
}*/
    
    @AuraEnabled
    public static void saveSign(String strSignElement,Id recId, Delivery__c deliveryData, List<Shipment_Tracking__c> trackingList){  
        String consigneeName = '';
        String consigneeDesignation = '';
        Boolean isWindow = false;
        if(deliveryData != null){
            consigneeName = deliveryData.Consignee_Name__c;
            consigneeDesignation = deliveryData.Consignee_Designation__c; 
        }
        
        
        ContentVersion cVersion = new ContentVersion();
        Id conDocument;
        
        cVersion.ContentLocation = 'S';  
        cVersion.PathOnClient = 'Signature-'+System.now() +'.png'; 
        cVersion.Origin = 'H';  
        cVersion.Title = 'Signature-'+System.now() +'.png'; 
        cVersion.VersionData = EncodingUtil.base64Decode(strSignElement); 
        Insert cVersion;
        
        if(cVersion.Id != null){
            conDocument = [SELECT ContentDocumentId FROM ContentVersion WHERE Id =:cVersion.Id].ContentDocumentId;
        } 
        
        if(trackingList.size() > 0){
            updateOtherShipment(conDocument,trackingList, consigneeName, consigneeDesignation,false);
        }
        
    }
    
    public static void updateOtherShipment( String contentDocId , List<Shipment_Tracking__c> trackingList , String consigneeName , String consigneeDesignation, Boolean isWindow){ 
        try{
            List<Shipment__c> updateDeliveryList = new List<Shipment__c>();
            set<String> shipmentId = new Set<String>();
            //set<Id> deliveryId = new Set<Id>();
            
            List<ContentDocumentLink> contentDocumentList = new List<ContentDocumentLink>();
            for(Shipment_Tracking__c track : trackingList){
                shipmentId.add(track.shipment__c);
            }
            
            
            // added by Rafi Khan line 66 to 149
            // Delivery and Shipment marks as delivered only if all secure bags of related shipment get delivered 
            List<Secure_Bag__c> secureBagList = [
                SELECT Id, Name , Shipment__c,Shipment__r.Tracking_Status__c, Shipping_Note_Number__c, Shipment__r.Destination_Address_Name__c, Secure_Packaging_Identifier__c , Current_Scan_Loction__c
                FROM Secure_Bag__c 
                WHERE Current_Scan_Loction__c = 'Delivered' AND
                Shipment__c IN: shipmentId]; 
            
            Map<String,List<Secure_Bag__c>> shipAndSecBagMap = new Map<String,List<Secure_Bag__c>>();
            if(secureBagList.size()>0){
                for(Secure_Bag__c secBagObj:secureBagList){
                    if(shipAndSecBagMap.containsKey(secBagObj.Shipment__c)){                        
                        List<Secure_Bag__c> tmpSecBag = shipAndSecBagMap.get(secBagObj.Shipment__c);                        
                        tmpSecBag.add(secBagObj);                        
                        shipAndSecBagMap.put(secBagObj.Shipment__c,tmpSecBag);
                    }else{                        
                        List<Secure_Bag__c> bagLsit = new List<Secure_Bag__c>();
                        bagLsit.add(secBagObj);                        
                        shipAndSecBagMap.put(secBagObj.Shipment__c,bagLsit);
                    }                
                }
            }
                        
            Map<String,List<Secure_Bag__c>> tmpShipAndSecBagMap = new Map<String,List<Secure_Bag__c>>();
            List<Secure_Bag__c> secureBagList1 = [
                SELECT Id, Name , Shipment__c,Shipment__r.Tracking_Status__c, Shipping_Note_Number__c, Shipment__r.Destination_Address_Name__c, Secure_Packaging_Identifier__c , Current_Scan_Loction__c
                FROM Secure_Bag__c 
                WHERE Shipment__c IN: shipmentId];
            
            if(secureBagList1.size()>0){
                for(Secure_Bag__c secBagObj:secureBagList1){
                    if(tmpShipAndSecBagMap.containsKey(secBagObj.Shipment__c)){
                        List<Secure_Bag__c> tmpSecBag = tmpShipAndSecBagMap.get(secBagObj.Shipment__c);
                        tmpSecBag.add(secBagObj);
                        tmpShipAndSecBagMap.put(secBagObj.Shipment__c,tmpSecBag);
                    }else{
                        List<Secure_Bag__c> bagLsit = new List<Secure_Bag__c>();
                        bagLsit.add(secBagObj);
                        tmpShipAndSecBagMap.put(secBagObj.Shipment__c,bagLsit);
                    }
                }
            }
           
            Map<String,Delivery__c> shipDelMap = new Map<String,Delivery__c>();
            List<Delivery__c> deliveryList = new List<Delivery__c>();
            deliveryList = [SELECT Id,Name,Status__c,Shipment__c,Number_of_Secure_Bag__c 
                            FROM Delivery__c WHERE Shipment__c IN: shipmentId ];
            if(deliveryList.size()>0){
                for(Delivery__c delObj :deliveryList){
                    shipDelMap.put(delObj.Shipment__c,delObj);
                }
                
            }
            
            List<Delivery__c> deliveryListToUpdate = new  List<Delivery__c>();
            for(String strId :shipmentId){

                if(shipAndSecBagMap.containsKey(strId) && tmpShipAndSecBagMap.containsKey(strId)){
                   
                    if(shipAndSecBagMap.get(strId).size() == tmpShipAndSecBagMap.get(strId).size()){ 
                       
                        Delivery__c delObjs = new Delivery__c();
                        delObjs = shipDelMap.get(strId);
                        if(delObjs.Status__c=='Accepted'){
                            Delivery__c tmpDel = new Delivery__c(); 
                            tmpDel.Status__c ='Delivered';
                            tmpDel.Shipment__c = strId;
                            tmpDel.Id = delObjs.Id;
                            tmpDel.Consignee_Name__c = consigneeName;
                            tmpDel.Consignee_Designation__c = consigneeDesignation;
                            tmpDel.Delivered_To_Person__c = consigneeName;
                            tmpDel.Actual_Delivery_Date_and_Time__c = System.now();  
                            deliveryListToUpdate.add(tmpDel);
                        }
                       
                    }//end of If conditions  
                }
                
            }
            
            if(deliveryListToUpdate.size()>0){
                update deliveryListToUpdate;
            }
            // Added Code by Rafi Khan Ends here
            
            
            for(Id linkedEntity : shipmentId){
                ContentDocumentLink cDocLink = new ContentDocumentLink();
                cDocLink.ContentDocumentId = contentDocId; 
                cDocLink.LinkedEntityId = linkedEntity; 
                cDocLink.ShareType = 'V'; 
                cDocLink.Visibility = 'AllUsers';
                contentDocumentList.add(cDocLink);
                
                Shipment__c delivery = new Shipment__c();
                delivery.Id = linkedEntity; 
                delivery.Consignee_Name__c = consigneeName; 
                delivery.Consignee_Designation__c = consigneeDesignation; 
                delivery.Delivered_To_Person__c = consigneeName;
                //delivery.Actual_Delivery_Date_and_Time__c = System.now();  
                updateDeliveryList.add(delivery);
                
            }
            
            if(contentDocumentList.size() > 0){
                Upsert contentDocumentList;
                
                if(updateDeliveryList.size() > 0 ){
                    Update updateDeliveryList;
                }
            } 
            
        }
        catch(Exception ex){
            System.debug('Error occure Line Number '+ex.getLineNumber());
            System.debug('Error occure Message '+ex.getMessage());
            
        }
    }
    
    public  void GetCoverage(){
        integer i = 0;
         i++;
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;

    }
    
    
}