force-app/main/default/objects/Pickup__c/Pickup__c.object-meta.xml
<CustomObject>
    <description>Pickup table stores pickup requests data raised by customers.</description>
    <label>Pickup</label>
    <nameField>
        <displayFormat>PKUP-{000000}</displayFormat>
        <label>Pickup Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pickups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Pickup__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Billing</value>
        </filterItems>
        <filterItems>
            <field>Account.ParentId</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <filterItems>
            <field>Account.Customer_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Pickups</relationshipLabel>
    <relationshipName>Pickups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pickup__c/fields/Customer_Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Customer_Product_Category__c</fullName>
    <label>BVC Service</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ValSHIP</fullName>
            </value>
            <value>
                <fullName>GoldSHIP</fullName>
            </value>
            <value>
                <fullName>SilverSHIP</fullName>
            </value>
            <value>
                <fullName>LuxeSHIP</fullName>
            </value>
            <value>
                <fullName>GenSHIP</fullName>
            </value>
            <value>
                <fullName>ExhibiSHIP</fullName>
                <isActive>false</isActive>
                <label>ExhibiSHIP</label>
            </value>
            <value>
                <fullName>Gold Bars</fullName>
                <isActive>false</isActive>
                <label>Gold Bars</label>
            </value>
            <value>
                <fullName>Gold Coins</fullName>
                <isActive>false</isActive>
                <label>Gold Coins</label>
            </value>
            <value>
                <fullName>Gold Jewellery</fullName>
                <isActive>false</isActive>
                <label>Gold Jewellery</label>
            </value>
            <value>
                <fullName>Silver Bricks</fullName>
                <isActive>false</isActive>
                <label>Silver Bricks</label>
            </value>
            <value>
                <fullName>Silver Jewellery</fullName>
                <isActive>false</isActive>
                <label>Silver Jewellery</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pickup__c/fields/Destination_Address_Name__c.field-meta.xml
<CustomField>
    <fullName>Destination_Address_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Destination Address Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AddressBook__c.Is_Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AddressBook__c</referenceTo>
    <relationshipLabel>Pickups (Destination Address Name)</relationshipLabel>
    <relationshipName>Pickups3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pickup__c/fields/Shipment__c.field-meta.xml
<CustomField>
    <fullName>Shipment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shipment</label>
    <referenceTo>Shipment__c</referenceTo>
    <relationshipLabel>Pickups</relationshipLabel>
    <relationshipName>Pickups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pickup__c/fields/Shipper_Address__c.field-meta.xml
<CustomField>
    <fullName>Shipper_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shipper Address</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AddressBook__c.Is_Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>AddressBook__c.Customer__c</field>
            <operation>equals</operation>
            <valueField>$Source.Shipper_Name__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AddressBook__c</referenceTo>
    <relationshipLabel>Pickups (Shipper Address)</relationshipLabel>
    <relationshipName>Pickups2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pickup__c/fields/Shipper_Name__c.field-meta.xml
<CustomField>
    <fullName>Shipper_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shipping Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Shipping</value>
        </filterItems>
        <filterItems>
            <field>Account.Customer_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Pickups (Shipper Name)</relationshipLabel>
    <relationshipName>ShipperName</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pickup__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Pickup Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Pickup Cancelled</fullName>
            </value>
            <value>
                <fullName>Update Successfully</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Secure_Bag__c/Secure_Bag__c.object-meta.xml
<CustomObject>
    <label>Secure Bag</label>
    <nameField>
        <displayFormat>SB-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Secure Bags</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Secure_Bag__c/fields/Shipment__c.field-meta.xml
<CustomField>
    <fullName>Shipment__c</fullName>
    <label>Shipment</label>
    <referenceTo>Shipment__c</referenceTo>
    <relationshipLabel>Secure Bags</relationshipLabel>
    <relationshipName>SecureBags</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Secure_Packaging__c/Secure_Packaging__c.object-meta.xml
<CustomObject>
    <label>Secure Packaging</label>
    <nameField>
        <label>Shipping Note Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Secure Packagings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Secure_Packaging__c/fields/Shipment__c.field-meta.xml
<CustomField>
    <fullName>Shipment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shipment</label>
    <referenceTo>Shipment__c</referenceTo>
    <relationshipLabel>Secure Packagings</relationshipLabel>
    <relationshipName>Secure_Packagings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Secure_Packaging__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Consumed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Shipment__c/Shipment__c.object-meta.xml
<CustomObject>
    <description>Shipment object stores shipments requested against a pickup.</description>
    <label>Shipment</label>
    <nameField>
        <displayFormat>ST-{0000000}</displayFormat>
        <label>Shipment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipment__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND 2 AND 3 AND 4</booleanFilter>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Billing</value>
        </filterItems>
        <filterItems>
            <field>Account.ParentId</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <filterItems>
            <field>Account.KYC_Indicator_for_Domestic_Flag__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Account.Customer_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Shipments (Customer)</relationshipLabel>
    <relationshipName>ShipmentsCustomer</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Customer_Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Customer_Product_Category__c</fullName>
    <label>BVC Service</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ValSHIP</fullName>
            </value>
            <value>
                <fullName>GoldSHIP</fullName>
            </value>
            <value>
                <fullName>SilverSHIP</fullName>
            </value>
            <value>
                <fullName>LuxeSHIP</fullName>
            </value>
            <value>
                <fullName>GenSHIP</fullName>
            </value>
            <value>
                <fullName>BATH</fullName>
            </value>
            <value>
                <fullName>eSHIP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Destination_Address_Name__c.field-meta.xml
<CustomField>
    <fullName>Destination_Address_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Destination Address Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Consignee_Name_TMS__c</field>
            <operation>equals</operation>
            <valueField>AddressBook__c.Customer__c</valueField>
        </filterItems>
        <filterItems>
            <field>AddressBook__c.Is_Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>AddressBook__c</referenceTo>
    <relationshipLabel>Shipment Delivery</relationshipLabel>
    <relationshipName>ShipmentsDelivery</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Destination_Pincode__c.field-meta.xml
<CustomField>
    <fullName>Destination_Pincode__c</fullName>
    <label>Destination Pincode</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Number_of_Packages__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Packages__c</fullName>
    <label>Number of Packages</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Origin_Pincode__c.field-meta.xml
<CustomField>
    <fullName>Origin_Pincode__c</fullName>
    <label>Origin Pincode</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Pickup__c.field-meta.xml
<CustomField>
    <fullName>Pickup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pickup</label>
    <referenceTo>Pickup__c</referenceTo>
    <relationshipLabel>Shipments</relationshipLabel>
    <relationshipName>Shipments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Shipper_Address__c.field-meta.xml
<CustomField>
    <fullName>Shipper_Address__c</fullName>
    <description>This is a field for all businesses</description>
    <label>Shipper Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Shipping_Note_Number__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Note_Number__c</fullName>
    <description>This is the Domestic Shipping Note number</description>
    <label>Shipping Note Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shipment_Tracking__c/Shipment_Tracking__c.object-meta.xml
<CustomObject>
    <label>Tracking</label>
    <nameField>
        <displayFormat>STN-{000000}</displayFormat>
        <label>Shipment Tracking Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tracking</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipment_Tracking__c/fields/Shipment__c.field-meta.xml
<CustomField>
    <fullName>Shipment__c</fullName>
    <label>Shipment</label>
    <referenceTo>Shipment__c</referenceTo>
    <relationshipLabel>Tracking</relationshipLabel>
    <relationshipName>Shipment_Trackings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TMS_ScanningBarCodeWithoutShipment.cls
/**
* @description       : 
* @author            : ChangeMeIn@UserSettingsUnder.SFDoc
* @group             : 
* @last modified on  : 12-11-2021
* @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
* Modifications Log 
* Ver   Date         Author                               Modification
* 1.0   07-16-2021   ChangeMeIn@UserSettingsUnder.SFDoc   Initial Version
**/
public without sharing class TMS_ScanningBarCodeWithoutShipment {
    
    @AuraEnabled
    public static Shipment__c shipmentRecordGet(String shippingNoteNumber, String pickupID){
        try {
            
            //System.debug('=============pickupID: ' + pickupID);
            //System.debug('=============shippingNoteNumber: ' + shippingNoteNumber);
            Shipment__c  shipmentRecord = new Shipment__c();
            
            Shipment__c [] tempDate = [
                
                SELECT ID, Name, Origin_Pincode__c,Number_of_Packages__c,Destination_Pincode__c,Customer_Product_Category__c,Shipping_Note_Number__c  
                FROM Shipment__c  
                WHERE Shipping_Note_Number__c =: shippingNoteNumber AND 
                Pickup__c =: pickupID  
                WITH SECURITY_ENFORCED LIMIT 1];
            
            //System.debug('=============tempDate: ' + tempDate);
            
            return tempDate.size() > 0 ? tempDate[0] : null;
            
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    
    @AuraEnabled
    public static Shipment__c createShipmentRecord(Shipment__c shipmentRecord , String   pickupId, String sNoteNumber  ){
         try {
        
        //System.debug('======createShipmentRecord======'+shipmentRecord);   
        //System.debug('======pickupId======'+pickupId); 
        //System.debug('======pickupId======'+sNoteNumber);
        //System.debug('dest: '+shipmentRecord.Destination_Address_Name__c);
        
        Pickup__c [] pickupRecord = [SELECT Customer__c, Shipper_Address__c, Shipper_Name__c 
                                     FROM Pickup__c 
                                     WHERE Id =:pickupId 
                                     WITH SECURITY_ENFORCED
                                    ];
        
        // Secure_Packaging__c
        
        Secure_Packaging__c securePackagingRecord = [ 
            SELECT Id, Name, Shipment__c,Status__c, RecordType.Name   
            FROM Secure_Packaging__c 
            WHERE Name =: sNoteNumber LIMIT 1
            
        ];
        
        if(securePackagingRecord != null){
            
            if(securePackagingRecord.RecordType.Name == 'Shipping Label' && securePackagingRecord.Status__c == 'Available'){
                if(shipmentRecord != null && pickupRecord != null){ 
                    shipmentRecord.Customer__c=  pickupRecord[0].Customer__c;
                    shipmentRecord.Pickup__c = pickupRecord[0].Id;
                    shipmentRecord.Shipping_Note_Number__c = sNoteNumber;
                    shipmentRecord.Origin_Address_Name__c = pickupRecord[0].Shipper_Address__c;
                    shipmentRecord.Shipper_Name_TMS__c = pickupRecord[0].Shipper_Name__c;
                    shipmentRecord.Shipment_Created_Through__c = 'Mobile App';
                    
                    Database.insert(shipmentRecord); 
                    
                    securePackagingRecord.Status__c = 'Consumed';
                    securePackagingRecord.Shipment__c = shipmentRecord.Id;
                    if(shipmentRecord.Id != null){
                        Database.Update(securePackagingRecord);
                    } 
                }
            }else{
                throw new AuraHandledException('shipping label is tagged with another pickup request.');
            } 
        } 
        
        
        //System.debug('======shipmentRecord======'+shipmentRecord);
        return shipmentRecord; 
        
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        } 
        
    }
    
    @AuraEnabled
    public static Secure_Bag__c createSecureBagRecords(String bagId , String shipmentID ) {
        
        //System.debug('=============== bagId ======= : '+bagId);
        //System.debug('=============== secureBag ======= : '+shipmentID);
        try { 
            Secure_Bag__c secureBag = new Secure_Bag__c();
            
            Secure_Packaging__c securePackaging = [
                SELECT Id, Name, Shipment__c,Status__c, RecordType.Name  
                FROM Secure_Packaging__c 
                WHERE Name =: bagId AND RecordType.Name ='Secure Bag' LIMIT 1
            ];
            
            if(securePackaging != null && securePackaging.Status__c == 'Available' ){ 
                if(shipmentID != null && shipmentID != ''  && shipmentID != 'null'){
                    secureBag.Shipment__c = shipmentID;
                    secureBag.Current_Scan_Loction__c = 'Picked Up';
                    secureBag.Current_Scan_Date_and_Time__c =DateTime.now();
                    secureBag.Secure_Bag__c =  securePackaging.Id; 
                    
                } 
                
                if(secureBag != null){
                    Database.insert(secureBag); 
                    securePackaging.Status__c = 'Consumed'; 
                    securePackaging.Shipment__c = shipmentID;
                    Database.update(securePackaging); 
                }
                
            } else{
                throw new AuraHandledException('Secure Bag is tagged with another shipmment.');
            } 
            
            return secureBag;
            
        } catch (Exception e) {
            //System.debug('=============== Exception ======= : '+e);
            throw new AuraHandledException(e.getMessage());
            
        }
    }
    
    @AuraEnabled
    public static void createTrackingRecord(Shipment_Tracking__c shipmentTrackingRecord , String shipmentId , List<Secure_Bag__c> secureBaglist){
        try {
            
            //System.debug('=========secureBaglist=========='+secureBaglist);
            if(shipmentTrackingRecord != null){  
                shipmentTrackingRecord.Shipment__c = shipmentId != null ? shipmentId : '';
                shipmentTrackingRecord.Scan_Time__c = DateTime.now(); 
                shipmentTrackingRecord.Location__c = 'Picked Up'; 
                Database.insert(shipmentTrackingrecord); 
                
                if(shipmentTrackingrecord.Id != null ){
                    for(Secure_Bag__c secureBag : secureBaglist){
                        secureBag.Tracking__c = shipmentTrackingrecord.Id;
                    }
                    
                    Database.update(secureBaglist);
                }
            }
            
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    } 
    
    
    public class SecureBagWrapper{
        
        @AuraEnabled
        public String bagId{get;set;} 
        
        @AuraEnabled
        public Secure_Bag__c secureBag {get;set;}
        
        
    }
}