force-app/main/default/objects/Pickup__c/Pickup__c.object-meta.xml
<CustomObject>
    <description>Pickup table stores pickup requests data raised by customers.</description>
    <label>Pickup</label>
    <nameField>
        <displayFormat>PKUP-{000000}</displayFormat>
        <label>Pickup Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pickups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Pickup__c/fields/Customer_Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Customer_Product_Category__c</fullName>
    <label>BVC Service</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ValSHIP</fullName>
            </value>
            <value>
                <fullName>GoldSHIP</fullName>
            </value>
            <value>
                <fullName>SilverSHIP</fullName>
            </value>
            <value>
                <fullName>LuxeSHIP</fullName>
            </value>
            <value>
                <fullName>GenSHIP</fullName>
            </value>
            <value>
                <fullName>ExhibiSHIP</fullName>
                <isActive>false</isActive>
                <label>ExhibiSHIP</label>
            </value>
            <value>
                <fullName>Gold Bars</fullName>
                <isActive>false</isActive>
                <label>Gold Bars</label>
            </value>
            <value>
                <fullName>Gold Coins</fullName>
                <isActive>false</isActive>
                <label>Gold Coins</label>
            </value>
            <value>
                <fullName>Gold Jewellery</fullName>
                <isActive>false</isActive>
                <label>Gold Jewellery</label>
            </value>
            <value>
                <fullName>Silver Bricks</fullName>
                <isActive>false</isActive>
                <label>Silver Bricks</label>
            </value>
            <value>
                <fullName>Silver Jewellery</fullName>
                <isActive>false</isActive>
                <label>Silver Jewellery</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pickup__c/fields/Shipment__c.field-meta.xml
<CustomField>
    <fullName>Shipment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shipment</label>
    <referenceTo>Shipment__c</referenceTo>
    <relationshipLabel>Pickups</relationshipLabel>
    <relationshipName>Pickups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pickup__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Pickup Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Pickup Cancelled</fullName>
            </value>
            <value>
                <fullName>Update Successfully</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Secure_Bag__c/Secure_Bag__c.object-meta.xml
<CustomObject>
    <label>Secure Bag</label>
    <nameField>
        <displayFormat>SB-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Secure Bags</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Secure_Bag__c/fields/Current_Scan_Date_and_Time__c.field-meta.xml
<CustomField>
    <fullName>Current_Scan_Date_and_Time__c</fullName>
    <label>Current Scan Date and Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Secure_Bag__c/fields/Current_Scan_Loction__c.field-meta.xml
<CustomField>
    <fullName>Current_Scan_Loction__c</fullName>
    <label>Current Scan Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
            </value>
            <value>
                <fullName>Out for Pickup</fullName>
            </value>
            <value>
                <fullName>Picked Up</fullName>
            </value>
            <value>
                <fullName>Origin Hub</fullName>
            </value>
            <value>
                <fullName>Origin Port</fullName>
            </value>
            <value>
                <fullName>Transit Hub</fullName>
            </value>
            <value>
                <fullName>Transit Port</fullName>
            </value>
            <value>
                <fullName>Destination Port</fullName>
            </value>
            <value>
                <fullName>Destination Hub</fullName>
            </value>
            <value>
                <fullName>Out for Delivery</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Secure_Bag__c/fields/Secure_Bag__c.field-meta.xml
<CustomField>
    <fullName>Secure_Bag__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Secure Bag</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Secure_Packaging__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Secure Bag</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Secure_Packaging__c</referenceTo>
    <relationshipLabel>Secure Bags</relationshipLabel>
    <relationshipName>Secure_Bags</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Secure_Bag__c/fields/Shipment__c.field-meta.xml
<CustomField>
    <fullName>Shipment__c</fullName>
    <label>Shipment</label>
    <referenceTo>Shipment__c</referenceTo>
    <relationshipLabel>Secure Bags</relationshipLabel>
    <relationshipName>SecureBags</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Secure_Bag__c/fields/Tracking__c.field-meta.xml
<CustomField>
    <fullName>Tracking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tracking</label>
    <referenceTo>Shipment_Tracking__c</referenceTo>
    <relationshipLabel>Secure Bags</relationshipLabel>
    <relationshipName>Secure_Bags</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Secure_Packaging__c/Secure_Packaging__c.object-meta.xml
<CustomObject>
    <label>Secure Packaging</label>
    <nameField>
        <label>Shipping Note Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Secure Packagings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Secure_Packaging__c/fields/Shipment__c.field-meta.xml
<CustomField>
    <fullName>Shipment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shipment</label>
    <referenceTo>Shipment__c</referenceTo>
    <relationshipLabel>Secure Packagings</relationshipLabel>
    <relationshipName>Secure_Packagings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Secure_Packaging__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Consumed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Shipment__c/Shipment__c.object-meta.xml
<CustomObject>
    <description>Shipment object stores shipments requested against a pickup.</description>
    <label>Shipment</label>
    <nameField>
        <displayFormat>ST-{0000000}</displayFormat>
        <label>Shipment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipment__c/fields/Customer_Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Customer_Product_Category__c</fullName>
    <label>BVC Service</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ValSHIP</fullName>
            </value>
            <value>
                <fullName>GoldSHIP</fullName>
            </value>
            <value>
                <fullName>SilverSHIP</fullName>
            </value>
            <value>
                <fullName>LuxeSHIP</fullName>
            </value>
            <value>
                <fullName>GenSHIP</fullName>
            </value>
            <value>
                <fullName>BATH</fullName>
            </value>
            <value>
                <fullName>eSHIP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Destination_Pincode__c.field-meta.xml
<CustomField>
    <fullName>Destination_Pincode__c</fullName>
    <label>Destination Pincode</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Number_of_Packages__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Packages__c</fullName>
    <label>Number of Packages</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Origin_Pincode__c.field-meta.xml
<CustomField>
    <fullName>Origin_Pincode__c</fullName>
    <label>Origin Pincode</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Scan_Time__c.field-meta.xml
<CustomField>
    <fullName>Scan_Time__c</fullName>
    <label>Scan Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Shipping_Note_Number__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Note_Number__c</fullName>
    <description>This is the Domestic Shipping Note number</description>
    <label>Shipping Note Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Pending Billing</fullName>
            </value>
            <value>
                <fullName>Verified For Billing</fullName>
            </value>
            <value>
                <fullName>Picked for Billing</fullName>
            </value>
            <value>
                <fullName>ACR Consumed</fullName>
            </value>
            <value>
                <fullName>Billed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Shipment_Tracking__c/Shipment_Tracking__c.object-meta.xml
<CustomObject>
    <label>Tracking</label>
    <nameField>
        <displayFormat>STN-{000000}</displayFormat>
        <label>Shipment Tracking Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tracking</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipment_Tracking__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
                <default>true</default>
                <label>Created</label>
            </value>
            <value>
                <fullName>Out for Pickup</fullName>
            </value>
            <value>
                <fullName>Picked Up</fullName>
            </value>
            <value>
                <fullName>Origin Hub</fullName>
            </value>
            <value>
                <fullName>Origin Port</fullName>
            </value>
            <value>
                <fullName>Transit Hub</fullName>
            </value>
            <value>
                <fullName>Transit Port</fullName>
            </value>
            <value>
                <fullName>Destination Port</fullName>
            </value>
            <value>
                <fullName>Destination Hub</fullName>
            </value>
            <value>
                <fullName>Out for Delivery</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Out of Linehaul</fullName>
            </value>
            <value>
                <fullName>Linehaul Deposit</fullName>
            </value>
            <value>
                <fullName>Linehaul In-Transit</fullName>
            </value>
            <value>
                <fullName>Linehaul Retrieved</fullName>
            </value>
            <value>
                <fullName>Airline Deposited</fullName>
            </value>
            <value>
                <fullName>AWB Booked</fullName>
            </value>
            <value>
                <fullName>AWB Finalized</fullName>
            </value>
            <value>
                <fullName>Flight Arrived</fullName>
            </value>
            <value>
                <fullName>Flight Departed</fullName>
            </value>
            <value>
                <fullName>On-Route Airport</fullName>
            </value>
            <value>
                <fullName>Pre-Flight at Airport</fullName>
            </value>
            <value>
                <fullName>Pre-Retrieval at Airport</fullName>
            </value>
            <value>
                <fullName>Retrieved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Shipment_Tracking__c/fields/Scan_Time__c.field-meta.xml
<CustomField>
    <fullName>Scan_Time__c</fullName>
    <label>Scan Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Shipment_Tracking__c/fields/Shipment__c.field-meta.xml
<CustomField>
    <fullName>Shipment__c</fullName>
    <label>Shipment</label>
    <referenceTo>Shipment__c</referenceTo>
    <relationshipLabel>Tracking</relationshipLabel>
    <relationshipName>Shipment_Trackings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TMS_AddSecureBagOnShipment.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 12-11-2021
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
 * Modifications Log 
 * Ver   Date         Author                               Modification
 * 1.0   07-16-2021   ChangeMeIn@UserSettingsUnder.SFDoc   Initial Version
**/
public without sharing class TMS_AddSecureBagOnShipment {
     
    @AuraEnabled
    public static Shipment__c shipmentRecordGet(String shipmentRecordId){
        try { 

            //System.debug('=============shippingNoteNumber: ' + shipmentRecordId);
            Shipment__c  shipmentRecord = new Shipment__c();

            Shipment__c [] tempDate = [
                SELECT ID, Name, Origin_Pincode__c,Number_of_Packages__c,Destination_Pincode__c,Customer_Product_Category__c,Shipping_Note_Number__c  
                FROM Shipment__c  
                WHERE Id =: shipmentRecordId
                LIMIT 1];

            //System.debug('=============tempDate: ' + tempDate);

            return tempDate.size() > 0 ? tempDate[0] : null;

        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    

    @AuraEnabled
    public static Secure_Bag__c createSecureBagRecords(String bagId , String shipmentID ) {

        //System.debug('=============== bagId ======= : '+bagId);
        //System.debug('=============== secureBag ======= : '+shipmentID);
        try { 
            Secure_Bag__c secureBag = new Secure_Bag__c();

            Secure_Packaging__c securePackaging = [
                SELECT Id, Name, Shipment__c,Status__c, RecordType.Name  
                FROM Secure_Packaging__c 
                WHERE Name =: bagId AND RecordType.Name ='Secure Bag' LIMIT 1
            ];

            if(securePackaging != null && securePackaging.Status__c == 'Available' ){ 
                if(shipmentID != null && shipmentID != ''  && shipmentID != 'null'){
                    secureBag.Shipment__c = shipmentID;
                    secureBag.Current_Scan_Loction__c = 'Picked Up';
                    secureBag.Current_Scan_Date_and_Time__c =DateTime.now();
                    secureBag.Secure_Bag__c =  securePackaging.Id; 
    
                } 

                if(secureBag != null){
                    Database.insert(secureBag); 
                    securePackaging.Status__c = 'Consumed'; 
                    securePackaging.Shipment__c = shipmentID; 
                    Database.update(securePackaging); 
                }

            } else{
                throw new AuraHandledException('Secure Bag is tagged with another shipmment.');
            } 

            return secureBag;

        } catch (Exception e) {
            //System.debug('line: '+e.getLineNumber()+' err: '+e);
            throw new AuraHandledException(e.getMessage());
            
        }
    }

    @AuraEnabled
    public static void createTrackingRecord(Shipment_Tracking__c shipmentTrackingRecord , String shipmentId , List<Secure_Bag__c> secureBaglist){
        try {

            System.debug('=========secureBaglist=========='+secureBaglist);
            if(shipmentTrackingRecord != null){  
                shipmentTrackingRecord.Shipment__c = shipmentId != null ? shipmentId : '';
                shipmentTrackingRecord.Scan_Time__c = DateTime.now(); 
                shipmentTrackingRecord.Location__c = 'Picked Up'; 
                Database.insert(shipmentTrackingrecord); 

                if(shipmentTrackingrecord.Id != null ){
                    for(Secure_Bag__c secureBag : secureBaglist){
                        secureBag.Tracking__c = shipmentTrackingrecord.Id;
                    }

                    Database.update(secureBaglist);
                }
            }
            
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    } 

    @AuraEnabled
    public static void updateshipmentAndPickup( String shipmentId  ){
       // try {

            //System.debug('=========shipmentId=========='+shipmentId);
            if(shipmentId != null && shipmentId != ''){  
                Shipment__c shipmentRecord = new Shipment__c();
                shipmentRecord.Id = shipmentId;
                shipmentRecord.Tracking_Status__c = 'Picked Up';
                Database.update(shipmentRecord);
                
                Pickup__c [] pickupRecord  = [SELECT Id, Shipment__c , Pickup_Status__c FROM Pickup__c WHERE Shipment__c =: shipmentId LIMIT 1];

                if(pickupRecord.size() > 0){
                    Pickup__c pickup = new Pickup__c();
                    pickup.Id = pickupRecord[0].Id;
                    pickup.Pickup_Status__c = 'Completed';
                    Database.update(pickup);
                }
            }
            
    //    } catch (Exception e) {
    //        throw new AuraHandledException(e.getMessage());
    //    }
    }

    
    public class SecureBagWrapper{

        @AuraEnabled
        public String bagId{get;set;} 

        @AuraEnabled
        public Secure_Bag__c secureBag {get;set;}
        
        
    }
}