force-app/main/default/objects/Origin_Destination__c/Origin_Destination__c.object-meta.xml
<CustomObject>
    <label>Origin Destination</label>
    <nameField>
        <label>Origin Destination Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Origin Destination</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Origin_Destination__c/fields/Destination_State__c.field-meta.xml
<CustomField>
    <fullName>Destination_State__c</fullName>
    <label>Destination State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Jammu And Kashmir</fullName>
            </value>
            <value>
                <fullName>Himachal Pradesh</fullName>
            </value>
            <value>
                <fullName>Punjab</fullName>
            </value>
            <value>
                <fullName>Chandigarh</fullName>
            </value>
            <value>
                <fullName>Uttarakhand</fullName>
            </value>
            <value>
                <fullName>Haryana</fullName>
            </value>
            <value>
                <fullName>Delhi</fullName>
            </value>
            <value>
                <fullName>Rajasthan</fullName>
            </value>
            <value>
                <fullName>Uttar Pradesh</fullName>
            </value>
            <value>
                <fullName>Bihar</fullName>
            </value>
            <value>
                <fullName>Sikkim</fullName>
            </value>
            <value>
                <fullName>Arunachal Pradesh</fullName>
            </value>
            <value>
                <fullName>Nagaland</fullName>
            </value>
            <value>
                <fullName>Manipur</fullName>
            </value>
            <value>
                <fullName>Mizoram</fullName>
            </value>
            <value>
                <fullName>Tripura</fullName>
            </value>
            <value>
                <fullName>Meghalaya</fullName>
            </value>
            <value>
                <fullName>Assam</fullName>
            </value>
            <value>
                <fullName>West Bengal</fullName>
            </value>
            <value>
                <fullName>Jharkhand</fullName>
            </value>
            <value>
                <fullName>Orissa</fullName>
            </value>
            <value>
                <fullName>Chhattisgarh</fullName>
            </value>
            <value>
                <fullName>Madhya Pradesh</fullName>
            </value>
            <value>
                <fullName>Gujarat</fullName>
            </value>
            <value>
                <fullName>Daman And Diu</fullName>
            </value>
            <value>
                <fullName>Dadra And Nagar Have</fullName>
            </value>
            <value>
                <fullName>Maharashtra</fullName>
            </value>
            <value>
                <fullName>Karnataka</fullName>
            </value>
            <value>
                <fullName>Goa</fullName>
            </value>
            <value>
                <fullName>Lakshadweep</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Origin_Destination__c/fields/DestinationCity__c.field-meta.xml
<CustomField>
    <fullName>DestinationCity__c</fullName>
    <label>Destination City</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Cities</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Origin_Destination__c/fields/Is_State_to_State__c.field-meta.xml
<CustomField>
    <fullName>Is_State_to_State__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is State to State</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Origin_Destination__c/fields/Mode_Of_Service__c.field-meta.xml
<CustomField>
    <fullName>Mode_Of_Service__c</fullName>
    <label>Mode Of Service</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Within City</fullName>
                <default>true</default>
                <label>Within City</label>
            </value>
            <value>
                <fullName>City-to-City</fullName>
            </value>
            <value>
                <fullName>Express (City-to-City)</fullName>
            </value>
            <value>
                <fullName>Surface (City-to-City)</fullName>
            </value>
            <value>
                <fullName>Door-to-Airport</fullName>
            </value>
            <value>
                <fullName>Vaulting</fullName>
            </value>
            <value>
                <fullName>Special Service</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Origin_Destination__c/fields/Origin_State__c.field-meta.xml
<CustomField>
    <fullName>Origin_State__c</fullName>
    <label>Origin State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Jammu And Kashmir</fullName>
            </value>
            <value>
                <fullName>Himachal Pradesh</fullName>
            </value>
            <value>
                <fullName>Punjab</fullName>
            </value>
            <value>
                <fullName>Chandigarh</fullName>
            </value>
            <value>
                <fullName>Uttarakhand</fullName>
            </value>
            <value>
                <fullName>Haryana</fullName>
            </value>
            <value>
                <fullName>Delhi</fullName>
            </value>
            <value>
                <fullName>Rajasthan</fullName>
            </value>
            <value>
                <fullName>Uttar Pradesh</fullName>
            </value>
            <value>
                <fullName>Bihar</fullName>
            </value>
            <value>
                <fullName>Sikkim</fullName>
            </value>
            <value>
                <fullName>Arunachal Pradesh</fullName>
            </value>
            <value>
                <fullName>Nagaland</fullName>
            </value>
            <value>
                <fullName>Manipur</fullName>
            </value>
            <value>
                <fullName>Mizoram</fullName>
            </value>
            <value>
                <fullName>Tripura</fullName>
            </value>
            <value>
                <fullName>Meghalaya</fullName>
            </value>
            <value>
                <fullName>Assam</fullName>
            </value>
            <value>
                <fullName>West Bengal</fullName>
            </value>
            <value>
                <fullName>Jharkhand</fullName>
            </value>
            <value>
                <fullName>Orissa</fullName>
            </value>
            <value>
                <fullName>Chhattisgarh</fullName>
            </value>
            <value>
                <fullName>Madhya Pradesh</fullName>
            </value>
            <value>
                <fullName>Gujarat</fullName>
            </value>
            <value>
                <fullName>Daman And Diu</fullName>
            </value>
            <value>
                <fullName>Dadra And Nagar Have</fullName>
            </value>
            <value>
                <fullName>Maharashtra</fullName>
            </value>
            <value>
                <fullName>Karnataka</fullName>
            </value>
            <value>
                <fullName>Goa</fullName>
            </value>
            <value>
                <fullName>Lakshadweep</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Origin_Destination__c/fields/OriginCity__c.field-meta.xml
<CustomField>
    <fullName>OriginCity__c</fullName>
    <label>Origin City</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Cities</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Origin_Destination__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Name</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Origin Destination</relationshipLabel>
    <relationshipName>Origin_Destination</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Origin_Destination__c/fields/State_Mode_of_Service__c.field-meta.xml
<CustomField>
    <fullName>State_Mode_of_Service__c</fullName>
    <label>State Mode of Service</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Within City</fullName>
            </value>
            <value>
                <fullName>City-to-City</fullName>
            </value>
            <value>
                <fullName>Express (City-to-City)</fullName>
            </value>
            <value>
                <fullName>Surface (City-to-City)</fullName>
            </value>
            <value>
                <fullName>Door-to-Airport</fullName>
            </value>
            <value>
                <fullName>Vaulting</fullName>
            </value>
            <value>
                <fullName>Special Service</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Name_Code__mdt/Product_Name_Code__mdt.object-meta.xml
<CustomObject>
    <label>Product Name &amp; Code</label>
    <pluralLabel>Product Name &amp; Code</pluralLabel>
</CustomObject>

force-app/main/default/objects/Product_Name_Code__mdt/fields/Product_Code__c.field-meta.xml
<CustomField>
    <fullName>Product_Code__c</fullName>
    <label>Product Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shipment__c/Shipment__c.object-meta.xml
<CustomObject>
    <description>Shipment object stores shipments requested against a pickup.</description>
    <label>Shipment</label>
    <nameField>
        <displayFormat>ST-{0000000}</displayFormat>
        <label>Shipment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipment__c/fields/BVC_Product_Name__c.field-meta.xml
<CustomField>
    <fullName>BVC_Product_Name__c</fullName>
    <label>BVC Product Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Customer_Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Customer_Product_Category__c</fullName>
    <label>BVC Service</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ValSHIP</fullName>
            </value>
            <value>
                <fullName>GoldSHIP</fullName>
            </value>
            <value>
                <fullName>SilverSHIP</fullName>
            </value>
            <value>
                <fullName>LuxeSHIP</fullName>
            </value>
            <value>
                <fullName>GenSHIP</fullName>
            </value>
            <value>
                <fullName>BATH</fullName>
            </value>
            <value>
                <fullName>eSHIP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Destination_Address_City__c.field-meta.xml
<CustomField>
    <fullName>Destination_Address_City__c</fullName>
    <formula>TEXT(Destination_Address_Name__r.Active_Pincode__r.City__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Destination Address City</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Destination_Address_State__c.field-meta.xml
<CustomField>
    <fullName>Destination_Address_State__c</fullName>
    <formula>Destination_Address_Name__r.STATE__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Destination Address State</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/IsExhibition__c.field-meta.xml
<CustomField>
    <fullName>IsExhibition__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Exhibition?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Origin_Address_City__c.field-meta.xml
<CustomField>
    <fullName>Origin_Address_City__c</fullName>
    <formula>TEXT(Origin_Address_Name__r.Active_Pincode__r.City__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Origin Address City</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Origin_Address_State__c.field-meta.xml
<CustomField>
    <fullName>Origin_Address_State__c</fullName>
    <formula>Origin_Address_Name__r.STATE__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Origin Address State</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Product_Code__c.field-meta.xml
<CustomField>
    <fullName>Product_Code__c</fullName>
    <label>BVC Product Code</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product__c.Product_Category__c</field>
            <operation>notEqual</operation>
            <value>Master</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Shipments (Product Name)</relationshipLabel>
    <relationshipName>Shipments1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/State_Logic_Check__c.field-meta.xml
<CustomField>
    <fullName>State_Logic_Check__c</fullName>
    <formula>IF( Origin_Address_City__c == Destination_Address_City__c ,&apos;With-In-City&apos;,IF((Origin_Address_City__c == Destination_Address_City__c) &amp;&amp; (Origin_Address_State__c == Destination_Address_State__c),&apos;With-In-City&apos;,&apos;&apos;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>State Logic Check</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TMS_ProductCodeHandler.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 03-09-2022
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public class TMS_ProductCodeHandler {
    public static void UpdateProductDetails(List<Shipment__c> ShipList){
        Set<String> OriginCitySet = new Set<String>();
        Set<String> DestinationCitySet = new Set<String>();
        for(Shipment__c sh:ShipList){
            OriginCitySet.add(sh.Origin_Address_City__c);
            DestinationCitySet.add(sh.Destination_Address_City__c);
        }
        Map<String,Product_Name_Code__mdt> NameCodeMap = new Map<String,Product_Name_Code__mdt>();
        String defaultProduct = '';
        for(Product_Name_Code__mdt mdt :[select MasterLabel,Product_Name__c,Product_Code__c,Is_Default__c FROM Product_Name_Code__mdt ]){
            NameCodeMap.put(mdt.MasterLabel, mdt);
            if(mdt.Is_Default__c)
                defaultProduct = mdt.MasterLabel;
        }
        //System.debug('OriginCitySet: '+OriginCitySet);
        //System.debug('DestinationCitySet: '+DestinationCitySet);
        List<Origin_Destination__c> OD_PAirs = [select OriginCity__c,DestinationCity__c, Is_State_to_State__c,Destination_State__c, Origin_State__c, State_Mode_of_Service__c, Mode_Of_Service__c 
                                                FROM Origin_Destination__c 
                                                WHERE (Mode_Of_Service__c!=null AND OriginCity__c=:OriginCitySet AND DestinationCity__c=:DestinationCitySet) OR (Is_State_to_State__c = true) LIMIT 5000];
        Map<String,string> OD_PairMAp = new Map<string,string>();
        ////System.debug('OD_PAirs>>'+OD_PAirs.size());
        if(OD_PAirs != null && OD_PAirs.size()>0){
            for(Origin_Destination__c od:OD_PAirs){
                if(od.Is_State_to_State__c){
                    OD_PairMAp.put(od.Origin_State__c + od.Destination_State__c, od.State_Mode_of_Service__c);
                }else{
                    OD_PairMAp.put(od.OriginCity__c + od.DestinationCity__c, od.Mode_Of_Service__c);
                }
                
            }
        }
        if(NameCodeMap !=null && NameCodeMap.size()>0){
            for(Shipment__c sh:ShipList){
                String BVC_Service = '';
                if(sh.IsExhibition__c)
                    BVC_Service = 'ExhibiSHIP';
                else
                    BVC_Service = sh.Customer_Product_Category__c;
                
                string serviceMode = '';
                if(sh.State_Logic_Check__c== 'With-In-City'){
                    serviceMode = 'Within City';
                }
                
                if(sh.State_Logic_Check__c != 'With-In-City' && OD_PairMAp!=null && OD_PairMAp.containsKey(sh.Origin_Address_State__c+sh.Destination_Address_State__c)){
                    serviceMode = OD_PairMAp.get(sh.Origin_Address_State__c+sh.Destination_Address_State__c);

                }else if(sh.State_Logic_Check__c != 'With-In-City' && OD_PairMAp!=null && OD_PairMAp.containsKey(sh.Origin_Address_City__c+sh.Destination_Address_City__c)){
                    serviceMode = OD_PairMAp.get(sh.Origin_Address_City__c+sh.Destination_Address_City__c);

                } else if(string.isBlank(serviceMode)){
                    serviceMode = defaultProduct;
                }
                
                if(string.isNotBlank(serviceMode) && NameCodeMap.containsKey(serviceMode)){
                    sh.BVC_Product_Name__c = BVC_Service + ' ' + NameCodeMap.get(serviceMode).Product_Name__c;
                    sh.Product_Code__c = BVC_Service.toUpperCase().remove('SHIP') + '-' +NameCodeMap.get(serviceMode).Product_Code__c;
                }
                
                System.debug('===sh.Product_Code__c=='+sh.Product_Code__c);
                System.debug('===sh.BVC_Product_Name__c=='+sh.BVC_Product_Name__c);
            }
        }
    }
}