force-app/main/default/objects/External_Contract_Shipment__c/External_Contract_Shipment__c.object-meta.xml
<CustomObject>
    <label>External Contract Shipment</label>
    <nameField>
        <displayFormat>ECS-{000000}</displayFormat>
        <label>Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>External Contract Shipments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/External_Contract_Shipment__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>External Contract Shipments</relationshipLabel>
    <relationshipName>External_Contract_Shipments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/External_Contract_Shipment__c/fields/Shipment__c.field-meta.xml
<CustomField>
    <fullName>Shipment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shipment</label>
    <referenceTo>Shipment__c</referenceTo>
    <relationshipLabel>External Contract Shipments</relationshipLabel>
    <relationshipName>External_Contract_Shipments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Shipment__c.field-meta.xml
<CustomField>
    <fullName>Shipment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shipment</label>
    <referenceTo>Shipment__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Shipment_Status_Static__c.field-meta.xml
<CustomField>
    <fullName>Shipment_Status_Static__c</fullName>
    <label>Shipment Status(Static)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ACR Consumed</fullName>
            </value>
            <value>
                <fullName>Billed</fullName>
            </value>
            <value>
                <fullName>Picked For Billing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/recordTypes/Shipment.recordType-meta.xml
<RecordType>
    <fullName>Shipment</fullName>
    <active>true</active>
    <label>Shipment</label>
</RecordType>

force-app/main/default/objects/Shipment__c/Shipment__c.object-meta.xml
<CustomObject>
    <description>Shipment object stores shipments requested against a pickup.</description>
    <label>Shipment</label>
    <nameField>
        <displayFormat>ST-{0000000}</displayFormat>
        <label>Shipment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipment__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Shipments</relationshipLabel>
    <relationshipName>Shipments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Pending Billing</fullName>
            </value>
            <value>
                <fullName>Verified For Billing</fullName>
            </value>
            <value>
                <fullName>Picked for Billing</fullName>
            </value>
            <value>
                <fullName>ACR Consumed</fullName>
            </value>
            <value>
                <fullName>Billed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ECSSShipmentUpdateBatch.cls
public class ECSSShipmentUpdateBatch implements Database.Batchable<sObject>,Database.stateful{
    Set<Id> ids = new Set<Id>();
    public ECSSShipmentUpdateBatch(Set<Id> ids){
        this.ids = ids;
    }
    String query = 'SELECT Id,Name,Order__c,Shipment__c FROM External_Contract_Shipment__c WHERE Id IN :ids ORDER BY Name';
    public Database.QueryLocator Start(Database.BatchableContext bc){
        return Database.getQueryLocator(query); 
    }
    public void execute(Database.BatchableContext bc , List<External_Contract_Shipment__c> ecShipments){
        List<Shipment__c> ships = new List<Shipment__c>();
        List<Order> orders = new List<Order>();
        if(ecShipments.size() > 0 && ecShipments != null){
            for(External_Contract_Shipment__c ecs : ecShipments){
                Shipment__c ship = new Shipment__c(Id = ecs.Shipment__c,Status__c = 'Billed');
                ships.add(ship);
                Order o = new Order(Id = ecs.Order__c,Shipment_Status_Static__c = 'Billed');
                orders.add(o);
            }
            Database.SaveResult[] lsr = Database.update(ships,false);
            for(Database.SaveResult result : lsr){
                if(result.isSuccess()){
                    system.debug('Shipment with Id :'+result.getId()+' Successfully Updated');
                }
                else{
                    for(Database.Error err : result.getErrors()){
                        System.debug('The following error has occurred.');                    
                        System.debug(err.getStatusCode() + ': ' + err.getMessage());
                        System.debug('Ship fields that affected this error: ' + err.getFields());
                    }
                }
            }
            
            
            Database.SaveResult[] lsrs = Database.update(orders,false);
            for(Database.SaveResult result : lsrs){
                if(result.isSuccess()){
                    system.debug('Orders with Id :'+result.getId()+' Successfully Updated');
                }
                else{
                    for(Database.Error err : result.getErrors()){
                        System.debug('The following error has occurred.');                    
                        System.debug(err.getStatusCode() + ': ' + err.getMessage());
                        System.debug('Order fields that affected this error: ' + err.getFields());
                    }
                }
            }
        }
    }
    
    public void finish(Database.BatchableContext bc){
        
    }
}