force-app/main/default/objects/Airline_API__mdt/Airline_API__mdt.object-meta.xml
<CustomObject>
    <description>Used for Airline API of Indigo, Spice-Jet, Go and Air Asia credentials.</description>
    <label>Airline API</label>
    <pluralLabel>Airline APIs</pluralLabel>
</CustomObject>

force-app/main/default/objects/AWB_Number__c/AWB_Number__c.object-meta.xml
<CustomObject>
    <label>AWB Number</label>
    <nameField>
        <displayFormat>AWB-{00000}</displayFormat>
        <label>AWB Number Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AWB Numbers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AWB_Number__c/fields/Linehaul_Tracking__c.field-meta.xml
<CustomField>
    <fullName>Linehaul_Tracking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Linehaul Tracking</label>
    <referenceTo>Linehaul_Tracking__c</referenceTo>
    <relationshipLabel>AWB Numbers</relationshipLabel>
    <relationshipName>AWB_Numbers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Linehaul__c/Linehaul__c.object-meta.xml
<CustomObject>
    <label>Master AWB</label>
    <nameField>
        <displayFormat>LH-{00000}</displayFormat>
        <label>Linehaul Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Master AWB</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Linehaul_Tracking__c/Linehaul_Tracking__c.object-meta.xml
<CustomObject>
    <label>Linehaul Tracking</label>
    <nameField>
        <displayFormat>LT-{00000}</displayFormat>
        <label>Linehaul Tracking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Linehaul Tracking</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Linehaul_Tracking__c/fields/Airport_Code__c.field-meta.xml
<CustomField>
    <fullName>Airport_Code__c</fullName>
    <label>Airport Code</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Linehaul_Tracking__c/fields/AWB_Number__c.field-meta.xml
<CustomField>
    <fullName>AWB_Number__c</fullName>
    <label>AWB Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Linehaul_Tracking__c/fields/Event_Datetime__c.field-meta.xml
<CustomField>
    <fullName>Event_Datetime__c</fullName>
    <label>Event Datetime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Linehaul_Tracking__c/fields/Flight_Detail__c.field-meta.xml
<CustomField>
    <fullName>Flight_Detail__c</fullName>
    <label>Flight Detail</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Linehaul_Tracking__c/fields/Linehaul_Name__c.field-meta.xml
<CustomField>
    <fullName>Linehaul_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Linehaul Name</label>
    <referenceTo>Linehaul__c</referenceTo>
    <relationshipLabel>Linehaul Tracking</relationshipLabel>
    <relationshipName>Linehaul_Tracking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Linehaul_Tracking__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AWB Booked</fullName>
            </value>
            <value>
                <fullName>AWB Finalized</fullName>
            </value>
            <value>
                <fullName>On-Route Airport</fullName>
            </value>
            <value>
                <fullName>Airline Deposited</fullName>
            </value>
            <value>
                <fullName>Pre-Flight at Airport</fullName>
            </value>
            <value>
                <fullName>Flight Departed</fullName>
            </value>
            <value>
                <fullName>Flight Arrived</fullName>
            </value>
            <value>
                <fullName>Pre-Retrieval at Airport</fullName>
            </value>
            <value>
                <fullName>Retrieved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Linehaul_Tracking__c/fields/Status_Id__c.field-meta.xml
<CustomField>
    <fullName>Status_Id__c</fullName>
    <label>Status Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Linehaul_Tracking__c/fields/Weight__c.field-meta.xml
<CustomField>
    <fullName>Weight__c</fullName>
    <label>Weight</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Track_AWB_SpiceJetHelper.cls
public class Track_AWB_SpiceJetHelper {

    public static List<Linehaul_Tracking__c> trackAWBspicejet(List<Linehaul__c> awbList,Map<String,String> awbStatusMap){
         String status = '';
       
        List<Linehaul_Tracking__c> insertLinehaulTrack	= new List<Linehaul_Tracking__c>();
        
      //get Airline_API__mdt  custom metadata where DeveloperName  is Spice_Jet_Track_AWB
            Airline_API__mdt[] spiceJetAirlineTrack = [SELECT Endpoint__c FROM Airline_API__mdt WHERE DeveloperName = 'Spice_Jet_Track_AWB'];
      //create variables to store metadata values
            String endpointtrack = spiceJetAirlineTrack[0].Endpoint__c;
            String body = '';
            String mode = 'BVC';
    // send http GET request to the endpoint containing  AWB_Number__c from linehaul record         
            for(Linehaul__c awblinehaul : awbList){
                Http http = new Http();
            Http httptrack = new Http();
        HttpRequest requesttrack = new HttpRequest();
        body = endpointtrack+awblinehaul.AWB_Number__c+'&mode='+mode;
        requesttrack.setEndpoint(body);
        requesttrack.setMethod('GET');
        system.debug('Body of Track AWB=== '+body);
       
        HttpResponse responsetrack= http.send(requesttrack);
            if(responsetrack.getStatusCode() != 200){
               System.debug('The status code returned was not expected: ' + responsetrack.getStatusCode() + ' ' + responsetrack.getStatus());

            }
            else{
        // deserialize response stored in  responsetrack  variable and store that deserialized data in trackwrapper  variable of wrapper class      
                SpicejetTrackAWBwrapper trackwrapper =  SpicejetTrackAWBwrapper.parse(responsetrack.getBody());
               system.debug('trackwrapper==='+trackwrapper);
                system.debug('trackwrapper==='+trackwrapper.Result.Task_tracker);
                for(SpicejetTrackAWBwrapper.Task_tracker getStatus :  trackwrapper.Result.Task_tracker){
        // create Linehaul_Tracking__c record from the repsonse 
                    Linehaul_Tracking__c lineTrackrecord = new Linehaul_Tracking__c();
                    
                    if(awbStatusMap.size() > 0 && awbStatusMap.containsKey(getStatus.status_detail)){
                    lineTrackrecord.Status__c = awbStatusMap.get(getStatus.status_detail);
                    }
                   
                    lineTrackrecord.Status_Id__c = string.valueOf(getStatus.status_id);
                    lineTrackrecord.Airport_Code__c = getStatus.airport_code;
             		lineTrackrecord.Flight_Detail__c = getStatus.flight_details;
        	      	 lineTrackrecord.Event_Datetime__c	=	DateTime.valueOf(string.valueof(getStatus.event_date_time));
                    lineTrackrecord.Weight__c = getStatus.weight;
                    system.debug('Linehaul record found'+awblinehaul.Id);
                  	lineTrackrecord.Linehaul_Name__c = awblinehaul.Id;
                    insertLinehaulTrack.add(lineTrackrecord);
                }
            }
        }
     
        return insertLinehaulTrack;
    }
}